-- DataSmart Govern - data-sync 执行运行日志表。
--
-- 设计说明：
-- 1. data_sync_execution 负责保存某次执行的当前状态快照，例如 RUNNING/SUCCEEDED/FAILED、累计读写数和租约；
-- 2. data_sync_execution_log 负责保存某次执行的阶段时间线，例如入队、认领、计划生成、创建 channel、批次同步、checkpoint、终态；
-- 3. data_sync_object_execution 负责保存对象/分片账本，例如某张表或某个 ID_RANGE 分片是否成功、失败和可重试。
--
-- 低敏边界：
-- 本表禁止保存 SQL 正文、连接串、账号、密码、token、样本行、字段值、真实分片边界和内部 endpoint。
-- 如需更细粒度的工程日志，应进入 observability 日志系统；如需用户可见的执行证据，则使用本表。

CREATE TABLE IF NOT EXISTS data_sync_execution_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    sync_task_id BIGINT NOT NULL,
    execution_id BIGINT NOT NULL,
    log_stage VARCHAR(64) NOT NULL,
    log_level VARCHAR(16) NOT NULL DEFAULT 'INFO',
    event_type VARCHAR(96) NOT NULL,
    event_status VARCHAR(32) NOT NULL DEFAULT 'PROGRESS',
    message VARCHAR(500) NOT NULL,
    detail_summary VARCHAR(2000),
    executor_id VARCHAR(128),
    work_unit_type VARCHAR(64),
    object_execution_id BIGINT,
    object_ordinal INTEGER,
    shard_or_partition VARCHAR(128),
    records_read BIGINT NOT NULL DEFAULT 0,
    records_written BIGINT NOT NULL DEFAULT 0,
    failed_record_count BIGINT NOT NULL DEFAULT 0,
    completed_work_units INTEGER,
    succeeded_work_units INTEGER,
    failed_work_units INTEGER,
    progress_percent NUMERIC(7, 2),
    speed_rows_per_second NUMERIC(18, 2) NOT NULL DEFAULT 0,
    event_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    trace_id VARCHAR(128),
    payload_policy VARCHAR(256) NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_data_sync_execution_log_level CHECK (log_level IN ('INFO', 'WARN', 'ERROR')),
    CONSTRAINT ck_data_sync_execution_log_counts CHECK (
        records_read >= 0
        AND records_written >= 0
        AND failed_record_count >= 0
        AND speed_rows_per_second >= 0
        AND (completed_work_units IS NULL OR completed_work_units >= 0)
        AND (succeeded_work_units IS NULL OR succeeded_work_units >= 0)
        AND (failed_work_units IS NULL OR failed_work_units >= 0)
        AND (progress_percent IS NULL OR (progress_percent >= 0 AND progress_percent <= 100))
    )
);

COMMENT ON TABLE data_sync_execution_log IS
    '数据同步执行运行日志表，记录某次 execution 的阶段时间线、低敏结果、进度计数和速度，用于运行历史详情展示、排障、Agent 解释和运维审计';
COMMENT ON COLUMN data_sync_execution_log.log_stage IS
    '执行阶段，例如 QUEUE、CLAIM、PRECHECK、PLAN、CHANNEL、OBJECT、SHARD、REMOTE_BATCH、CHECKPOINT、COMPLETE、FAILED';
COMMENT ON COLUMN data_sync_execution_log.log_level IS
    '日志级别：INFO 正常推进，WARN 可恢复或需要关注，ERROR 执行失败或 fail-closed';
COMMENT ON COLUMN data_sync_execution_log.event_type IS
    '细粒度事件类型，例如 EXECUTION_QUEUED、WORKER_CLAIMED、RUN_ONCE_BATCH_COMPLETED、OBJECT_SUCCEEDED';
COMMENT ON COLUMN data_sync_execution_log.event_status IS
    '事件结果，例如 STARTED、PROGRESS、SUCCEEDED、FAILED、SKIPPED、BLOCKED、RETRYING';
COMMENT ON COLUMN data_sync_execution_log.message IS
    '面向用户的中文短消息，应说明发生了什么，不应只保存内部状态码';
COMMENT ON COLUMN data_sync_execution_log.detail_summary IS
    '低敏详情摘要，可保存数量、策略、建议和问题码，禁止保存 SQL、连接串、凭据、样本行、真实 where 条件或完整异常栈';
COMMENT ON COLUMN data_sync_execution_log.work_unit_type IS
    '工作单元类型，例如 OBJECT 或 PARTITION_SHARD，用于关联对象/分片页签';
COMMENT ON COLUMN data_sync_execution_log.object_execution_id IS
    '对象/分片账本 ID，关联 data_sync_object_execution.id';
COMMENT ON COLUMN data_sync_execution_log.object_ordinal IS
    '对象映射顺序号，从 0 开始，用于定位第几条对象映射或分片';
COMMENT ON COLUMN data_sync_execution_log.shard_or_partition IS
    '分片低敏标识，例如 id-range-0000；禁止保存真实 min/max 边界';
COMMENT ON COLUMN data_sync_execution_log.records_read IS
    '记录该阶段看到的累计读取数，不一定等同于 execution 表的最终值';
COMMENT ON COLUMN data_sync_execution_log.records_written IS
    '记录该阶段看到的累计写入数，不一定等同于 execution 表的最终值';
COMMENT ON COLUMN data_sync_execution_log.failed_record_count IS
    '记录该阶段看到的累计失败记录数或低敏失败计数';
COMMENT ON COLUMN data_sync_execution_log.completed_work_units IS
    '当前已完成对象/分片工作单元数；普通单表任务可为空';
COMMENT ON COLUMN data_sync_execution_log.progress_percent IS
    '执行进度百分比。对象/分片总数已知时可计算；总量未知的单表 run-once 可为空或终态为 100';
COMMENT ON COLUMN data_sync_execution_log.speed_rows_per_second IS
    '写入速度估算，单位行/秒。用于运行历史页面展示同步速度，不作为精确性能基准';
COMMENT ON COLUMN data_sync_execution_log.event_time IS
    '事件发生时间，用于按时间线展示运行日志';
COMMENT ON COLUMN data_sync_execution_log.payload_policy IS
    '载荷安全策略说明，标记本行是低敏产品日志而不是原始执行日志';

CREATE INDEX IF NOT EXISTS idx_data_sync_execution_log_execution_time
    ON data_sync_execution_log (execution_id, event_time, id);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_log_task_time
    ON data_sync_execution_log (sync_task_id, event_time, id);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_log_stage
    ON data_sync_execution_log (execution_id, log_stage, event_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_log_level
    ON data_sync_execution_log (execution_id, log_level, event_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_log_scope_time
    ON data_sync_execution_log (tenant_id, project_id, event_time, id);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_log_object
    ON data_sync_execution_log (object_execution_id, event_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_log_retention
    ON data_sync_execution_log (event_time, id);
