-- DataSmart Govern - data-sync 执行策略与执行策略快照。
--
-- 设计说明：
-- 1. data_sync_execution_policy 是“管理员可配置的执行资源策略”，不再让普通任务创建向导暴露 channel、
--    shardCount、retry、timeout 等运行时细节。
-- 2. data_sync_execution_policy_snapshot 是“某次 execution 实际生效策略快照”，用于解释历史运行为什么使用了
--    channel=4、timeout=600s、targetRowsPerShard=200000 等参数。管理员后续修改策略不会改写历史解释。
-- 3. 运行时生效优先级由服务层保证：任务级覆盖 > 项目级策略 > 数据源/连接器策略 > 系统默认策略。
-- 4. 本迁移只保存低敏执行策略，不保存 SQL、where 原文、连接串、账号、密码、token 或真实分片边界值。

CREATE TABLE IF NOT EXISTS data_sync_execution_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    scope_type VARCHAR(32) NOT NULL,
    scope_key VARCHAR(160) NOT NULL,
    scope_name VARCHAR(160),
    policy_code VARCHAR(96) NOT NULL,
    policy_name VARCHAR(160) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    datasource_id BIGINT,
    connector_type VARCHAR(64),
    connector_role VARCHAR(16) NOT NULL DEFAULT 'ANY',
    sync_task_id BIGINT,
    target_rows_per_shard BIGINT,
    min_shard_count INTEGER,
    max_shard_count INTEGER,
    max_channel INTEGER,
    task_group_size INTEGER,
    read_batch_size INTEGER,
    write_batch_size INTEGER,
    commit_interval_records INTEGER,
    timeout_seconds INTEGER,
    max_retry_count INTEGER,
    max_dirty_record_count BIGINT,
    max_dirty_record_ratio NUMERIC(12, 6),
    priority INTEGER NOT NULL DEFAULT 100,
    description VARCHAR(1000),
    created_by BIGINT,
    updated_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_data_sync_execution_policy_scope UNIQUE (tenant_id, scope_type, scope_key, policy_code),
    CONSTRAINT ck_data_sync_execution_policy_scope CHECK (
        scope_type IN ('SYSTEM', 'PROJECT', 'CONNECTOR', 'DATASOURCE', 'TASK')
    ),
    CONSTRAINT ck_data_sync_execution_policy_connector_role CHECK (
        connector_role IN ('ANY', 'SOURCE', 'TARGET')
    ),
    CONSTRAINT ck_data_sync_execution_policy_positive_numbers CHECK (
        COALESCE(target_rows_per_shard, 1) > 0
        AND COALESCE(min_shard_count, 1) > 0
        AND COALESCE(max_shard_count, 1) > 0
        AND COALESCE(max_channel, 1) > 0
        AND COALESCE(task_group_size, 1) > 0
        AND COALESCE(read_batch_size, 1) > 0
        AND COALESCE(write_batch_size, 1) > 0
        AND COALESCE(commit_interval_records, 1) > 0
        AND COALESCE(timeout_seconds, 1) > 0
        AND COALESCE(max_retry_count, 0) >= 0
        AND COALESCE(max_dirty_record_count, 0) >= 0
        AND COALESCE(max_dirty_record_ratio, 0) >= 0
    )
);

COMMENT ON TABLE data_sync_execution_policy IS
'数据同步执行策略表，保存系统默认、项目、连接器、数据源和任务级执行资源策略，由管理员或运营维护。';
COMMENT ON COLUMN data_sync_execution_policy.scope_type IS
'策略作用域：SYSTEM 全局默认，PROJECT 项目级，CONNECTOR 连接器类型级，DATASOURCE 数据源级，TASK 任务级覆盖。';
COMMENT ON COLUMN data_sync_execution_policy.scope_key IS
'作用域稳定键，例如 SYSTEM、PROJECT:101、CONNECTOR:SOURCE:MYSQL、DATASOURCE:23、TASK:1001。';
COMMENT ON COLUMN data_sync_execution_policy.connector_role IS
'连接器策略作用方向：SOURCE 限制读取端，TARGET 限制写入端，ANY 同时适用于两端。';
COMMENT ON COLUMN data_sync_execution_policy.target_rows_per_shard IS
'自动 splitPk 分片目标行数。系统会用 rowCount / targetRowsPerShard 估算分片数，再按 min/max 裁剪。';
COMMENT ON COLUMN data_sync_execution_policy.max_channel IS
'本策略允许的最大并发通道数。真实 channel 会再与分片数、源端策略、目标端策略取安全下限。';
COMMENT ON COLUMN data_sync_execution_policy.task_group_size IS
'每个 TaskGroup 容纳的分片数量，用于把大量分片分批调度，避免一次性压垮源库或目标库。';
COMMENT ON COLUMN data_sync_execution_policy.max_dirty_record_ratio IS
'脏数据比例阈值，超过后应进入失败分片重试或人工修复，不适合逐行 replay。';

CREATE INDEX IF NOT EXISTS idx_data_sync_execution_policy_scope
    ON data_sync_execution_policy (tenant_id, scope_type, scope_key, enabled, priority);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_policy_project
    ON data_sync_execution_policy (tenant_id, project_id, enabled, priority);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_policy_connector
    ON data_sync_execution_policy (tenant_id, connector_type, connector_role, enabled, priority);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_policy_datasource
    ON data_sync_execution_policy (tenant_id, datasource_id, connector_role, enabled, priority);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_policy_task
    ON data_sync_execution_policy (tenant_id, sync_task_id, enabled, priority);

CREATE TABLE IF NOT EXISTS data_sync_execution_policy_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    sync_task_id BIGINT NOT NULL,
    execution_id BIGINT NOT NULL,
    policy_code_summary VARCHAR(500),
    resolution_order VARCHAR(200) NOT NULL,
    target_rows_per_shard BIGINT,
    resolved_shard_count INTEGER,
    resolved_channel INTEGER,
    task_group_size INTEGER,
    read_batch_size INTEGER,
    write_batch_size INTEGER,
    commit_interval_records INTEGER,
    timeout_seconds INTEGER,
    max_retry_count INTEGER,
    max_dirty_record_count BIGINT,
    max_dirty_record_ratio NUMERIC(12, 6),
    snapshot_json TEXT NOT NULL,
    payload_policy VARCHAR(160) NOT NULL DEFAULT 'LOW_SENSITIVE_EXECUTION_POLICY_SNAPSHOT_NO_SQL_NO_CREDENTIALS',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_data_sync_execution_policy_snapshot UNIQUE (sync_task_id, execution_id)
);

COMMENT ON TABLE data_sync_execution_policy_snapshot IS
'数据同步执行策略快照表，保存某次 execution 实际生效的低敏策略，用于历史排障与审计解释。';
COMMENT ON COLUMN data_sync_execution_policy_snapshot.snapshot_json IS
'低敏策略快照 JSON，只包含策略编号、作用域、批大小、超时、重试、脏数据阈值、自动分片结果等信息。';
COMMENT ON COLUMN data_sync_execution_policy_snapshot.resolved_shard_count IS
'本次执行自动解析后的分片数。非分片任务可为空。';
COMMENT ON COLUMN data_sync_execution_policy_snapshot.resolved_channel IS
'本次执行实际采用的 channel 上限。普通 run-once 表示执行策略推荐值，分片 fan-out 表示真实有界并发。';

CREATE INDEX IF NOT EXISTS idx_data_sync_execution_policy_snapshot_execution
    ON data_sync_execution_policy_snapshot (execution_id);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_policy_snapshot_task_time
    ON data_sync_execution_policy_snapshot (sync_task_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_policy_snapshot_project_time
    ON data_sync_execution_policy_snapshot (tenant_id, project_id, create_time DESC);

INSERT INTO data_sync_execution_policy
(tenant_id, project_id, scope_type, scope_key, scope_name, policy_code, policy_name, enabled,
 target_rows_per_shard, min_shard_count, max_shard_count, max_channel, task_group_size,
 read_batch_size, write_batch_size, commit_interval_records, timeout_seconds, max_retry_count,
 max_dirty_record_count, max_dirty_record_ratio, priority, description, create_time, update_time)
VALUES
(0, NULL, 'SYSTEM', 'SYSTEM', '全局默认策略', 'SYSTEM_DEFAULT', '全局默认执行策略', TRUE,
 200000, 1, 64, 4, 8,
 512, 256, 256, 600, 0,
 100, 0.010000, 10,
 '系统默认策略：普通用户不需要配置分片、并发、批大小、超时、重试和脏数据阈值，运行时会以该策略作为兜底。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (tenant_id, scope_type, scope_key, policy_code) DO NOTHING;

INSERT INTO data_sync_execution_policy
(tenant_id, project_id, scope_type, scope_key, scope_name, policy_code, policy_name, enabled,
 connector_type, connector_role, max_channel, read_batch_size, priority, description, create_time, update_time)
VALUES
(0, NULL, 'CONNECTOR', 'CONNECTOR:SOURCE:MYSQL', 'MySQL 源端默认读取策略', 'MYSQL_SOURCE_DEFAULT',
 'MySQL 源端默认读取策略', TRUE, 'MYSQL', 'SOURCE', 4, 1000, 30,
 'MySQL 作为源端时默认限制最大读取并发和读取批大小，避免大表同步时把业务库连接池打满。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (tenant_id, scope_type, scope_key, policy_code) DO NOTHING;

INSERT INTO data_sync_execution_policy
(tenant_id, project_id, scope_type, scope_key, scope_name, policy_code, policy_name, enabled,
 connector_type, connector_role, write_batch_size, commit_interval_records, priority, description, create_time, update_time)
VALUES
(0, NULL, 'CONNECTOR', 'CONNECTOR:TARGET:POSTGRESQL', 'PostgreSQL 目标端默认写入策略', 'POSTGRESQL_TARGET_DEFAULT',
 'PostgreSQL 目标端默认写入策略', TRUE, 'POSTGRESQL', 'TARGET', 1000, 1000, 30,
 'PostgreSQL 作为目标端时默认放大写入批次和提交间隔，兼顾吞吐与事务日志压力。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (tenant_id, scope_type, scope_key, policy_code) DO NOTHING;
