-- DataSmart Govern - data-sync PostgreSQL 基线。
--
-- 设计原则：
-- 1. 本脚本只创建 data-sync 微服务自己的控制面事实表，例如模板、任务、执行、checkpoint、错误样本、
--    事故、审计、幂等记录和 task-management receipt outbox。
-- 2. 源端/目标端客户数据库的连接串、账号、密码和密钥仍由 datasource-management 管理；
--    data-sync 表中只保存 datasourceId、低敏 connector type、对象名、状态、计数和审计摘要。
-- 3. 暂不创建外键和级联删除。同步执行、checkpoint、错误样本、事故和审计都属于生产证据，
--    商业化环境中经常需要独立保留、归档或按保留期清理，不能因为主对象删除而自动消失。
-- 4. MySQL AUTO_INCREMENT 转为 PostgreSQL GENERATED BY DEFAULT AS IDENTITY。
--    BY DEFAULT 允许后续存量迁移脚手架导入原始 ID，再通过 sequence 校正继续使用自增。
-- 5. JSON 配置暂按 TEXT 存储，保持 Java 实体 String 映射稳定；后续若升级 JSONB，需要同步 TypeHandler、
--    查询 SQL、迁移脚本 checksum 和历史数据转换策略。

CREATE TABLE IF NOT EXISTS data_sync_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    source_datasource_id BIGINT NOT NULL,
    target_datasource_id BIGINT NOT NULL,
    source_schema_name VARCHAR(128),
    source_object_name VARCHAR(128),
    target_schema_name VARCHAR(128),
    target_object_name VARCHAR(128),
    source_connector_type VARCHAR(64),
    target_connector_type VARCHAR(64),
    sync_mode VARCHAR(64) NOT NULL,
    write_strategy VARCHAR(64) NOT NULL DEFAULT 'APPEND',
    primary_key_field VARCHAR(128),
    incremental_field VARCHAR(128),
    field_mapping_config TEXT,
    filter_config TEXT,
    partition_config TEXT,
    retry_policy TEXT,
    timeout_policy TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT,
    updated_by BIGINT,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_data_sync_template_tenant_non_negative CHECK (tenant_id >= 0),
    CONSTRAINT ck_data_sync_template_datasource_pair CHECK (source_datasource_id > 0 AND target_datasource_id > 0)
);

COMMENT ON TABLE data_sync_template IS '数据同步模板表，保存可复用的低敏同步配置，不保存连接串、账号、密码、SQL 正文或样本数据';
COMMENT ON COLUMN data_sync_template.tenant_id IS '租户 ID，所有同步配置必须具备租户边界';
COMMENT ON COLUMN data_sync_template.project_id IS '项目 ID，用于租户内部二级隔离、项目级权限、配额、SLA 和成本审计';
COMMENT ON COLUMN data_sync_template.workspace_id IS '工作空间 ID，用于多团队协作空间、空间级筛选和后续空间级配额';
COMMENT ON COLUMN data_sync_template.source_datasource_id IS '源端数据源 ID，只引用 datasource-management 的登记事实，不在本表保存凭据';
COMMENT ON COLUMN data_sync_template.target_datasource_id IS '目标端数据源 ID，只引用 datasource-management 的登记事实，不在本表保存凭据';
COMMENT ON COLUMN data_sync_template.source_schema_name IS '源端 schema 或命名空间，属于低敏对象定位元数据，不保存连接地址、账号、密钥或 SQL 条件';
COMMENT ON COLUMN data_sync_template.source_object_name IS '源端对象名称，例如表、视图、topic、文件逻辑对象或 API 资源名';
COMMENT ON COLUMN data_sync_template.target_schema_name IS '目标端 schema 或命名空间，属于低敏对象定位元数据';
COMMENT ON COLUMN data_sync_template.target_object_name IS '目标端对象名称，真实执行器据此确定写入对象';
COMMENT ON COLUMN data_sync_template.source_connector_type IS '源端连接器类型低敏快照，例如 MYSQL、POSTGRESQL、KAFKA、FILE';
COMMENT ON COLUMN data_sync_template.target_connector_type IS '目标端连接器类型低敏快照，用于能力预检、调度和运营筛选';
COMMENT ON COLUMN data_sync_template.sync_mode IS '同步模式，例如 FULL、INCREMENTAL_TIME、INCREMENTAL_ID、CDC_STREAMING、ONE_TIME_MIGRATION、REPLAY、BACKFILL';
COMMENT ON COLUMN data_sync_template.write_strategy IS '目标端写入策略，例如 APPEND、UPSERT、INSERT_IGNORE、REPLACE、OVERWRITE，影响幂等、冲突处理、回放和补数';
COMMENT ON COLUMN data_sync_template.primary_key_field IS '主键或冲突判断字段，只保存字段名，不保存字段值';
COMMENT ON COLUMN data_sync_template.incremental_field IS '增量字段，用于增量同步推进 checkpoint，不保存 checkpoint 原始值';
COMMENT ON COLUMN data_sync_template.field_mapping_config IS '字段映射配置 JSON 文本，当前保持 String 映射，禁止保存敏感样本数据';
COMMENT ON COLUMN data_sync_template.filter_config IS '过滤条件配置 JSON 文本，禁止保存完整 SQL 正文或敏感业务条件';
COMMENT ON COLUMN data_sync_template.partition_config IS '分区与并发配置 JSON 文本，例如按日期分区、ID range 或 hash 分片';
COMMENT ON COLUMN data_sync_template.retry_policy IS '重试策略 JSON 文本，例如最大重试次数、退避间隔和可重试错误类型';
COMMENT ON COLUMN data_sync_template.timeout_policy IS '超时策略 JSON 文本，例如单批读取超时、整体执行超时和目标写入超时';
COMMENT ON COLUMN data_sync_template.enabled IS '模板是否启用；禁用后不应创建新的同步任务，历史任务和执行记录仍保留';

CREATE INDEX IF NOT EXISTS idx_data_sync_template_tenant_mode ON data_sync_template (tenant_id, sync_mode, enabled);
CREATE INDEX IF NOT EXISTS idx_data_sync_template_project_mode ON data_sync_template (tenant_id, project_id, sync_mode, enabled);
CREATE INDEX IF NOT EXISTS idx_data_sync_template_workspace ON data_sync_template (tenant_id, workspace_id, update_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_template_connector_mode ON data_sync_template (tenant_id, source_connector_type, target_connector_type, sync_mode);
CREATE INDEX IF NOT EXISTS idx_data_sync_template_object_pair ON data_sync_template (tenant_id, source_object_name, target_object_name);
CREATE INDEX IF NOT EXISTS idx_data_sync_template_write_strategy ON data_sync_template (tenant_id, write_strategy, sync_mode);
CREATE INDEX IF NOT EXISTS idx_data_sync_template_source ON data_sync_template (source_datasource_id);
CREATE INDEX IF NOT EXISTS idx_data_sync_template_target ON data_sync_template (target_datasource_id);
CREATE INDEX IF NOT EXISTS idx_data_sync_template_update_time ON data_sync_template (update_time);

CREATE TABLE IF NOT EXISTS data_sync_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    template_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    current_state VARCHAR(64) NOT NULL,
    approval_state VARCHAR(64) NOT NULL,
    priority VARCHAR(32) NOT NULL DEFAULT 'MEDIUM',
    schedule_config TEXT,
    run_mode VARCHAR(64) NOT NULL DEFAULT 'TEMPLATE',
    trigger_type VARCHAR(64) NOT NULL DEFAULT 'MANUAL',
    owner_id BIGINT,
    last_execution_id BIGINT,
    attention_required BOOLEAN NOT NULL DEFAULT FALSE,
    attention_reason VARCHAR(1000),
    description VARCHAR(512),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_data_sync_task_tenant_non_negative CHECK (tenant_id >= 0),
    CONSTRAINT ck_data_sync_task_template_positive CHECK (template_id > 0),
    CONSTRAINT ck_data_sync_task_state CHECK (current_state IN (
        'DRAFT', 'CONFIGURED', 'PENDING_APPROVAL', 'SCHEDULED', 'QUEUED', 'RUNNING',
        'PAUSED', 'RETRYING', 'PARTIALLY_SUCCEEDED', 'SUCCEEDED', 'FAILED',
        'VALIDATION_FAILED', 'BLOCKED_BY_DEPENDENCY', 'AWAITING_OPERATOR_ACTION',
        'DEGRADED', 'CANCELLED', 'ARCHIVED'
    )),
    CONSTRAINT ck_data_sync_task_approval_state CHECK (approval_state IN ('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED'))
);

COMMENT ON TABLE data_sync_task IS '数据同步任务表，是运营台、调度、暂停、恢复、重试、取消和人工介入的主对象';
COMMENT ON COLUMN data_sync_task.current_state IS '任务主状态，覆盖草稿、配置完成、审批、排队、运行、暂停、重试、成功、失败、人工介入、取消和归档等生命周期';
COMMENT ON COLUMN data_sync_task.approval_state IS '审批状态，高风险同步或导出类任务可要求审批通过后才能运行';
COMMENT ON COLUMN data_sync_task.priority IS '任务优先级，用于未来调度队列、租户配额和运维干预策略';
COMMENT ON COLUMN data_sync_task.schedule_config IS '调度配置 JSON 文本，例如 cron、固定间隔、维护窗口、时区和错峰策略';
COMMENT ON COLUMN data_sync_task.last_execution_id IS '最近一次同步执行记录 ID，列表页可快速展示最近运行结果，完整历史仍在 data_sync_execution';
COMMENT ON COLUMN data_sync_task.attention_required IS '是否需要人工介入，通常由超过最大退避次数、反复租约过期或执行环境异常触发';
COMMENT ON COLUMN data_sync_task.attention_reason IS '人工介入原因摘要，用于运营台、告警和后续工单流转';

CREATE INDEX IF NOT EXISTS idx_data_sync_task_tenant_state ON data_sync_task (tenant_id, current_state, update_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_project_state ON data_sync_task (tenant_id, project_id, current_state, update_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_workspace_state ON data_sync_task (tenant_id, workspace_id, current_state, update_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_template ON data_sync_task (template_id);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_owner_state ON data_sync_task (tenant_id, owner_id, current_state);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_approval ON data_sync_task (tenant_id, approval_state, update_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_trigger ON data_sync_task (trigger_type, update_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_attention ON data_sync_task (tenant_id, attention_required, update_time);

CREATE TABLE IF NOT EXISTS data_sync_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    sync_task_id BIGINT NOT NULL,
    execution_no BIGINT NOT NULL,
    execution_state VARCHAR(64) NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    queued_at TIMESTAMP WITHOUT TIME ZONE,
    started_at TIMESTAMP WITHOUT TIME ZONE,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    checkpoint_ref VARCHAR(256),
    records_read BIGINT NOT NULL DEFAULT 0,
    records_written BIGINT NOT NULL DEFAULT 0,
    failed_record_count BIGINT NOT NULL DEFAULT 0,
    error_summary VARCHAR(1000),
    triggered_by BIGINT,
    executor_id VARCHAR(128),
    heartbeat_time TIMESTAMP WITHOUT TIME ZONE,
    lease_expire_time TIMESTAMP WITHOUT TIME ZONE,
    defer_count INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_data_sync_execution_task_no UNIQUE (sync_task_id, execution_no),
    CONSTRAINT ck_data_sync_execution_counts_non_negative CHECK (records_read >= 0 AND records_written >= 0 AND failed_record_count >= 0 AND defer_count >= 0),
    CONSTRAINT ck_data_sync_execution_state CHECK (execution_state IN (
        'QUEUED', 'RUNNING', 'PAUSED', 'RETRYING', 'PARTIALLY_SUCCEEDED',
        'SUCCEEDED', 'FAILED', 'CANCELLED'
    ))
);

COMMENT ON TABLE data_sync_execution IS '数据同步执行记录表；一条任务可运行多次，每次运行都由独立 execution 承载状态、计数和租约';
COMMENT ON COLUMN data_sync_execution.execution_no IS '同一任务下第几次执行，用于用户理解第 N 次运行并支撑唯一约束';
COMMENT ON COLUMN data_sync_execution.execution_state IS '执行状态，worker 认领、心跳、退避、成功、失败和取消都围绕该字段流转';
COMMENT ON COLUMN data_sync_execution.queued_at IS '进入执行队列的时间；退避回队列时会被推迟到未来时间';
COMMENT ON COLUMN data_sync_execution.checkpoint_ref IS '最近 checkpoint 引用，可保存 checkpoint 主键或外部状态引用';
COMMENT ON COLUMN data_sync_execution.executor_id IS '执行器实例 ID，worker 认领后写入，用于并发裁决和故障定位';
COMMENT ON COLUMN data_sync_execution.heartbeat_time IS '最近一次执行器心跳时间，用于判断执行器是否仍然存活';
COMMENT ON COLUMN data_sync_execution.lease_expire_time IS '当前执行租约过期时间，超过后可进入自动恢复或人工介入流程';
COMMENT ON COLUMN data_sync_execution.defer_count IS '当前执行记录被延迟回队列次数，用于识别长期被退避的任务';

CREATE INDEX IF NOT EXISTS idx_data_sync_execution_task_state ON data_sync_execution (sync_task_id, execution_state, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_tenant_state ON data_sync_execution (tenant_id, execution_state, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_project_state ON data_sync_execution (tenant_id, project_id, execution_state, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_workspace_state ON data_sync_execution (tenant_id, workspace_id, execution_state, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_trigger ON data_sync_execution (trigger_type, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_executor ON data_sync_execution (executor_id, started_at);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_lease ON data_sync_execution (execution_state, lease_expire_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_execution_queue ON data_sync_execution (execution_state, queued_at, id);

CREATE TABLE IF NOT EXISTS data_sync_callback_idempotency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    sync_task_id BIGINT,
    execution_id BIGINT,
    scope_key VARCHAR(128) NOT NULL,
    action VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    executor_id VARCHAR(128),
    request_digest VARCHAR(1000),
    callback_state VARCHAR(32) NOT NULL,
    response_summary VARCHAR(1000),
    error_message VARCHAR(1000),
    first_seen_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_seen_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_data_sync_callback_idempotency UNIQUE (tenant_id, action, scope_key, idempotency_key),
    CONSTRAINT ck_data_sync_callback_state CHECK (callback_state IN ('PROCESSING', 'SUCCEEDED', 'FAILED'))
);

COMMENT ON TABLE data_sync_callback_idempotency IS 'data-sync 执行器回调与租约动作幂等记录表，用数据库唯一约束保护多实例重复请求';
COMMENT ON COLUMN data_sync_callback_idempotency.scope_key IS '幂等作用域，例如 taskId:executionId 或 RECOVERY:ALL；避免可空字段组合破坏唯一语义';
COMMENT ON COLUMN data_sync_callback_idempotency.idempotency_key IS '调用方生成的幂等键，同一业务动作重试必须复用同一个键';
COMMENT ON COLUMN data_sync_callback_idempotency.request_digest IS '低敏请求摘要，用于排障，不保存完整结果、SQL、密钥或样本';
COMMENT ON COLUMN data_sync_callback_idempotency.callback_state IS '幂等处理状态：PROCESSING、SUCCEEDED、FAILED';
COMMENT ON COLUMN data_sync_callback_idempotency.last_seen_time IS '最近一次看到该幂等键的时间，保留期清理以该字段为主';

CREATE INDEX IF NOT EXISTS idx_data_sync_callback_execution ON data_sync_callback_idempotency (execution_id, action, last_seen_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_callback_task ON data_sync_callback_idempotency (sync_task_id, action, last_seen_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_callback_executor ON data_sync_callback_idempotency (executor_id, last_seen_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_callback_retention ON data_sync_callback_idempotency (last_seen_time, id);
CREATE INDEX IF NOT EXISTS idx_data_sync_callback_state ON data_sync_callback_idempotency (callback_state, last_seen_time);

CREATE TABLE IF NOT EXISTS data_sync_task_management_receipt_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id VARCHAR(180) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    sync_task_id BIGINT NOT NULL,
    sync_execution_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    source_service VARCHAR(128) NOT NULL DEFAULT 'data-sync',
    outbox_state VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempt_count INTEGER NOT NULL DEFAULT 6,
    next_retry_at TIMESTAMP WITHOUT TIME ZONE,
    last_attempt_at TIMESTAMP WITHOUT TIME ZONE,
    delivered_at TIMESTAMP WITHOUT TIME ZONE,
    dead_letter_at TIMESTAMP WITHOUT TIME ZONE,
    last_error_code VARCHAR(128),
    last_error_summary VARCHAR(512),
    actor_id BIGINT,
    actor_role VARCHAR(64),
    trace_id VARCHAR(128),
    payload_json TEXT NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_data_sync_task_receipt_outbox_receipt UNIQUE (receipt_id),
    CONSTRAINT ck_data_sync_task_receipt_attempt CHECK (attempt_count >= 0 AND max_attempt_count > 0),
    CONSTRAINT ck_data_sync_task_receipt_state CHECK (outbox_state IN ('PENDING', 'DELIVERING', 'RETRY_WAIT', 'DELIVERED', 'DEAD_LETTER'))
);

COMMENT ON TABLE data_sync_task_management_receipt_outbox IS 'data-sync 到 task-management execution receipt 的可靠投递 outbox 表';
COMMENT ON COLUMN data_sync_task_management_receipt_outbox.receipt_id IS '稳定幂等 receiptId；同一 execution 的同一事件只能创建一条 outbox';
COMMENT ON COLUMN data_sync_task_management_receipt_outbox.outbox_state IS '投递状态：PENDING、DELIVERING、RETRY_WAIT、DELIVERED、DEAD_LETTER';
COMMENT ON COLUMN data_sync_task_management_receipt_outbox.attempt_count IS '当前已尝试投递次数，进入 DELIVERING 时递增';
COMMENT ON COLUMN data_sync_task_management_receipt_outbox.next_retry_at IS '下一次允许重试时间；为空表示可立即投递或不再重试';
COMMENT ON COLUMN data_sync_task_management_receipt_outbox.payload_json IS '低敏 receipt 请求 JSON 文本，禁止包含 SQL、连接串、凭据、checkpoint 原始值、样本数据、prompt、模型输出或内部 URL';

CREATE INDEX IF NOT EXISTS idx_data_sync_task_receipt_outbox_state_retry ON data_sync_task_management_receipt_outbox (outbox_state, next_retry_at, id);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_receipt_outbox_delivering ON data_sync_task_management_receipt_outbox (outbox_state, last_attempt_at, id);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_receipt_outbox_execution ON data_sync_task_management_receipt_outbox (sync_execution_id, event_type);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_receipt_outbox_task ON data_sync_task_management_receipt_outbox (sync_task_id, event_type, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_receipt_outbox_scope_state ON data_sync_task_management_receipt_outbox (tenant_id, project_id, workspace_id, outbox_state, update_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_task_receipt_outbox_dead_letter ON data_sync_task_management_receipt_outbox (outbox_state, dead_letter_at, id);

CREATE TABLE IF NOT EXISTS data_sync_checkpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    sync_task_id BIGINT NOT NULL,
    execution_id BIGINT NOT NULL,
    checkpoint_type VARCHAR(64) NOT NULL,
    checkpoint_value TEXT NOT NULL,
    shard_or_partition VARCHAR(128),
    records_read BIGINT NOT NULL DEFAULT 0,
    records_written BIGINT NOT NULL DEFAULT 0,
    checkpoint_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_data_sync_checkpoint_counts_non_negative CHECK (records_read >= 0 AND records_written >= 0)
);

COMMENT ON TABLE data_sync_checkpoint IS '数据同步 checkpoint 表，表达同步已经安全推进到哪里，是增量、CDC、回放和补数恢复的关键状态';
COMMENT ON COLUMN data_sync_checkpoint.checkpoint_type IS 'checkpoint 类型，例如 TIME_FIELD、ID_RANGE、KAFKA_OFFSET、FILE_POSITION、PARTITION_WINDOW';
COMMENT ON COLUMN data_sync_checkpoint.checkpoint_value IS 'checkpoint 值，例如时间戳、最大 ID、Kafka offset 或低敏 JSON 结构';
COMMENT ON COLUMN data_sync_checkpoint.shard_or_partition IS '分片或分区标识，支持并行任务保存多条 checkpoint';
COMMENT ON COLUMN data_sync_checkpoint.checkpoint_time IS 'checkpoint 生成时间，保留期清理按该业务时间判断';

CREATE INDEX IF NOT EXISTS idx_data_sync_checkpoint_task ON data_sync_checkpoint (sync_task_id, checkpoint_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_checkpoint_execution ON data_sync_checkpoint (execution_id, checkpoint_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_checkpoint_type ON data_sync_checkpoint (tenant_id, checkpoint_type, checkpoint_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_checkpoint_project ON data_sync_checkpoint (tenant_id, project_id, checkpoint_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_checkpoint_partition ON data_sync_checkpoint (sync_task_id, shard_or_partition);
CREATE INDEX IF NOT EXISTS idx_data_sync_checkpoint_retention ON data_sync_checkpoint (checkpoint_time, id);

CREATE TABLE IF NOT EXISTS data_sync_execution_recovery_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    sync_task_id BIGINT NOT NULL,
    execution_id BIGINT NOT NULL,
    recovery_type VARCHAR(32) NOT NULL,
    source_execution_id BIGINT,
    source_checkpoint_id BIGINT,
    window_start VARCHAR(128),
    window_end VARCHAR(128),
    shard_or_partition VARCHAR(256),
    reason VARCHAR(500),
    plan_state VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_data_sync_recovery_execution UNIQUE (execution_id),
    CONSTRAINT ck_data_sync_recovery_type CHECK (recovery_type IN ('REPLAY', 'BACKFILL')),
    CONSTRAINT ck_data_sync_recovery_state CHECK (plan_state IN ('CREATED', 'CLAIMED', 'CONSUMED', 'CANCELLED'))
);

COMMENT ON TABLE data_sync_execution_recovery_plan IS '数据同步 replay/backfill 恢复计划表，保存低敏恢复窗口和来源 checkpoint 契约';
COMMENT ON COLUMN data_sync_execution_recovery_plan.recovery_type IS '恢复类型：REPLAY 表示从历史执行或 checkpoint 回放，BACKFILL 表示按窗口或分区补数';
COMMENT ON COLUMN data_sync_execution_recovery_plan.execution_id IS '本恢复计划驱动的新 executionId，worker 认领 execution 后按该字段读取计划';
COMMENT ON COLUMN data_sync_execution_recovery_plan.source_checkpoint_id IS 'replay 来源 checkpointId；为空表示从来源 execution 起点回放或由 worker 选择安全起点';
COMMENT ON COLUMN data_sync_execution_recovery_plan.reason IS '低敏操作原因，禁止保存 SQL、连接串、密码、token、prompt、样本数据或完整工具参数';
COMMENT ON COLUMN data_sync_execution_recovery_plan.plan_state IS '计划状态：CREATED、CLAIMED、CONSUMED、CANCELLED';

CREATE INDEX IF NOT EXISTS idx_data_sync_recovery_task ON data_sync_execution_recovery_plan (sync_task_id, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_recovery_source ON data_sync_execution_recovery_plan (source_execution_id, source_checkpoint_id);
CREATE INDEX IF NOT EXISTS idx_data_sync_recovery_project ON data_sync_execution_recovery_plan (tenant_id, project_id, recovery_type, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_recovery_state ON data_sync_execution_recovery_plan (plan_state, create_time);

CREATE TABLE IF NOT EXISTS data_sync_error_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    sync_task_id BIGINT NOT NULL,
    execution_id BIGINT NOT NULL,
    error_type VARCHAR(64) NOT NULL,
    error_code VARCHAR(128),
    error_message VARCHAR(1000),
    source_record_key VARCHAR(256),
    target_record_key VARCHAR(256),
    sample_payload VARCHAR(4000),
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

COMMENT ON TABLE data_sync_error_sample IS '数据同步错误样本表，保存脱敏后的失败定位信息，用于排障、质量复盘和人工修复';
COMMENT ON COLUMN data_sync_error_sample.error_type IS '错误类型，例如 SOURCE_READ_ERROR、TARGET_WRITE_ERROR、TYPE_CONVERSION_ERROR';
COMMENT ON COLUMN data_sync_error_sample.error_message IS '错误摘要，避免把完整堆栈、SQL、连接串或敏感样本写入业务表';
COMMENT ON COLUMN data_sync_error_sample.source_record_key IS '源端记录定位，例如主键、文件行号或 Kafka topic/partition/offset';
COMMENT ON COLUMN data_sync_error_sample.target_record_key IS '目标端记录定位，例如目标主键或写入批次';
COMMENT ON COLUMN data_sync_error_sample.sample_payload IS '脱敏并截断后的样本载荷';
COMMENT ON COLUMN data_sync_error_sample.retryable IS '是否可重试，用于运维判断是自动补偿还是人工修复';

CREATE INDEX IF NOT EXISTS idx_data_sync_error_task ON data_sync_error_sample (sync_task_id, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_error_execution ON data_sync_error_sample (execution_id, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_error_type ON data_sync_error_sample (tenant_id, error_type, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_error_project ON data_sync_error_sample (tenant_id, project_id, error_type, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_error_retryable ON data_sync_error_sample (retryable, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_error_retention ON data_sync_error_sample (create_time, id);

CREATE TABLE IF NOT EXISTS data_sync_incident_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    sync_task_id BIGINT NOT NULL,
    execution_id BIGINT,
    incident_type VARCHAR(64) NOT NULL,
    severity VARCHAR(32) NOT NULL DEFAULT 'P3',
    incident_status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    title VARCHAR(256) NOT NULL,
    description VARCHAR(2000),
    operator_id BIGINT,
    operator_role VARCHAR(64),
    assigned_operator_id BIGINT,
    assigned_operator_role VARCHAR(64),
    resolution_summary VARCHAR(2000),
    acknowledged_at TIMESTAMP WITHOUT TIME ZONE,
    resolved_at TIMESTAMP WITHOUT TIME ZONE,
    closed_at TIMESTAMP WITHOUT TIME ZONE,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_data_sync_incident_status CHECK (incident_status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'CLOSED')),
    CONSTRAINT ck_data_sync_incident_severity CHECK (severity IN ('P1', 'P2', 'P3', 'P4'))
);

COMMENT ON TABLE data_sync_incident_record IS '数据同步事故记录表，用于执行器失联、连接器失败、目标端限流、配置错误和数据契约破坏等运营闭环';
COMMENT ON COLUMN data_sync_incident_record.incident_type IS '事故类型，例如 EXECUTOR_UNSTABLE、CONNECTOR_FAILURE、TARGET_THROTTLED、CONFIGURATION_ERROR、DATA_CONTRACT_BROKEN';
COMMENT ON COLUMN data_sync_incident_record.severity IS '事故严重级别：P1、P2、P3、P4';
COMMENT ON COLUMN data_sync_incident_record.incident_status IS '事故状态：OPEN、ACKNOWLEDGED、RESOLVED、CLOSED';
COMMENT ON COLUMN data_sync_incident_record.assigned_operator_id IS '当前事故负责人 ID，用于运营分派、SLA 跟踪和我的事故列表';
COMMENT ON COLUMN data_sync_incident_record.resolution_summary IS '事故解决摘要，关闭或解决时填写，禁止保存敏感样本、凭据或完整 SQL';

CREATE INDEX IF NOT EXISTS idx_data_sync_incident_task ON data_sync_incident_record (sync_task_id, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_incident_tenant_status ON data_sync_incident_record (tenant_id, incident_status, severity, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_incident_project_status ON data_sync_incident_record (tenant_id, project_id, incident_status, severity, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_incident_workspace_status ON data_sync_incident_record (tenant_id, workspace_id, incident_status, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_incident_execution ON data_sync_incident_record (execution_id);
CREATE INDEX IF NOT EXISTS idx_data_sync_incident_operator ON data_sync_incident_record (operator_id, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_incident_assignee ON data_sync_incident_record (assigned_operator_id, incident_status, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_incident_retention ON data_sync_incident_record (incident_status, closed_at, id);

CREATE TABLE IF NOT EXISTS data_sync_audit_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    template_id BIGINT,
    sync_task_id BIGINT,
    execution_id BIGINT,
    action_type VARCHAR(64) NOT NULL,
    actor_id BIGINT,
    actor_role VARCHAR(64),
    action_payload VARCHAR(2000),
    result VARCHAR(32) NOT NULL,
    trace_id VARCHAR(128),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_data_sync_audit_result CHECK (result IN ('SUCCESS', 'FAILED', 'REJECTED'))
);

COMMENT ON TABLE data_sync_audit_record IS '数据同步审计记录表，用于追踪模板、任务、执行、checkpoint、恢复和人工操作';
COMMENT ON COLUMN data_sync_audit_record.template_id IS '关联同步模板 ID，可为空；模板创建、校验、禁用等动作通常没有 sync_task_id';
COMMENT ON COLUMN data_sync_audit_record.action_type IS '审计动作类型，例如 CREATE_TEMPLATE、CREATE_TASK、RUN_TASK、UPDATE_CHECKPOINT、RECOVER_EXECUTION';
COMMENT ON COLUMN data_sync_audit_record.action_payload IS '动作载荷摘要，应保存脱敏后的轻量信息，禁止保存 SQL、凭据、样本或完整模型输出';
COMMENT ON COLUMN data_sync_audit_record.result IS '动作结果：SUCCESS、FAILED、REJECTED';
COMMENT ON COLUMN data_sync_audit_record.trace_id IS '链路追踪 ID，用于跨 gateway、task-management、datasource-management 和 Python Runtime 排障';

CREATE INDEX IF NOT EXISTS idx_data_sync_audit_task_time ON data_sync_audit_record (sync_task_id, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_audit_template_time ON data_sync_audit_record (template_id, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_audit_execution_time ON data_sync_audit_record (execution_id, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_audit_tenant_action ON data_sync_audit_record (tenant_id, action_type, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_audit_project_action ON data_sync_audit_record (tenant_id, project_id, action_type, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_audit_actor ON data_sync_audit_record (actor_id, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_audit_trace ON data_sync_audit_record (trace_id);
CREATE INDEX IF NOT EXISTS idx_data_sync_audit_retention ON data_sync_audit_record (create_time, id);
