-- DataSmart Govern - data-sync 对象级执行账本
--
-- 设计说明：
-- 1. data_sync_execution 表只描述父级 execution，例如用户点击“运行一次同步任务”形成的整次运行。
-- 2. data_sync_object_execution 表描述父 execution 内部的可恢复工作单元，当前主要是一张源表到目标表的对象映射。
-- 3. 后续如果实现 splitPk、时间窗口、hash 分片或文件分片，可以继续把本表扩展为“对象 + 分片”级账本。
-- 4. 本表允许保存对象名用于内部恢复和排障，但普通 API、日志、指标和跨服务 receipt 仍不得直接暴露对象名、SQL、连接串、凭据或行样本。
CREATE TABLE IF NOT EXISTS data_sync_object_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT,
    workspace_id BIGINT,
    sync_task_id BIGINT NOT NULL,
    execution_id BIGINT NOT NULL,
    template_id BIGINT,
    object_ordinal INTEGER NOT NULL,
    source_schema_name VARCHAR(128),
    source_object_name VARCHAR(256),
    target_schema_name VARCHAR(128),
    target_object_name VARCHAR(256),
    object_state VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempt_count INTEGER NOT NULL DEFAULT 3,
    records_read BIGINT NOT NULL DEFAULT 0,
    records_written BIGINT NOT NULL DEFAULT 0,
    failed_record_count BIGINT NOT NULL DEFAULT 0,
    last_error_type VARCHAR(128),
    last_error_code VARCHAR(128),
    last_error_message VARCHAR(1000),
    started_at TIMESTAMP WITHOUT TIME ZONE,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    payload_policy VARCHAR(256) NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_data_sync_object_execution_ordinal UNIQUE (execution_id, object_ordinal),
    CONSTRAINT ck_data_sync_object_execution_counts CHECK (
        object_ordinal >= 0
        AND attempt_count >= 0
        AND max_attempt_count > 0
        AND records_read >= 0
        AND records_written >= 0
        AND failed_record_count >= 0
    ),
    CONSTRAINT ck_data_sync_object_execution_state CHECK (
        object_state IN ('PENDING', 'RUNNING', 'RETRYING', 'SUCCEEDED', 'FAILED', 'SKIPPED')
    )
);

COMMENT ON TABLE data_sync_object_execution IS 'data-sync OBJECT_LIST 对象级执行账本，用于记录父 execution 下每个对象或未来分片的状态、尝试次数、计数和低敏错误摘要';
COMMENT ON COLUMN data_sync_object_execution.execution_id IS '父级 data_sync_execution ID；同一个父 execution 下每个 object_ordinal 只允许一条记录';
COMMENT ON COLUMN data_sync_object_execution.object_ordinal IS '对象在 objectMappingConfig.mappings 中的顺序号，从 0 开始；用于稳定恢复执行顺序和定位失败对象';
COMMENT ON COLUMN data_sync_object_execution.source_object_name IS '源端对象名，内部恢复和排障使用；普通 API、日志、指标和 receipt 不应直接暴露';
COMMENT ON COLUMN data_sync_object_execution.target_object_name IS '目标端对象名，内部恢复和排障使用；普通 API、日志、指标和 receipt 不应直接暴露';
COMMENT ON COLUMN data_sync_object_execution.object_state IS '对象级状态：PENDING、RUNNING、RETRYING、SUCCEEDED、FAILED、SKIPPED';
COMMENT ON COLUMN data_sync_object_execution.attempt_count IS '当前对象已经尝试执行的次数；成功对象不会因为其他对象失败而重复增加';
COMMENT ON COLUMN data_sync_object_execution.max_attempt_count IS '当前对象允许的最大尝试次数，创建时从模板 retryPolicy 解析并落表，避免模板后续修改影响历史 execution';
COMMENT ON COLUMN data_sync_object_execution.last_error_message IS '最近一次低敏错误摘要；禁止保存连接串、凭据、SQL、字段值、样本行或完整异常堆栈';
COMMENT ON COLUMN data_sync_object_execution.payload_policy IS '载荷安全策略说明，明确本表可内部使用但不应直接投影到公开事件';

CREATE INDEX IF NOT EXISTS idx_data_sync_object_execution_parent_state
    ON data_sync_object_execution (execution_id, object_state, object_ordinal);
CREATE INDEX IF NOT EXISTS idx_data_sync_object_execution_task_state
    ON data_sync_object_execution (sync_task_id, object_state, create_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_object_execution_scope_state
    ON data_sync_object_execution (tenant_id, project_id, workspace_id, object_state, update_time);
CREATE INDEX IF NOT EXISTS idx_data_sync_object_execution_retry
    ON data_sync_object_execution (object_state, attempt_count, max_attempt_count, update_time);
