-- data-quality PostgreSQL schema 基线。
--
-- 迁移原则：
-- 1. 四张表保持现有 Java 实体、API 和业务生命周期语义，不借数据库切换擅自重写领域模型；
-- 2. 主键使用 GENERATED BY DEFAULT AS IDENTITY，既支持 MyBatis-Plus 自动回填，也允许受控数据迁移显式写入旧 ID；
-- 3. LocalDateTime 对应 TIMESTAMP WITHOUT TIME ZONE，避免迁移时发生隐式时区换算；平台运行时仍应统一使用 UTC；
-- 4. 高频运营查询继续使用 tenant/project/workspace 冗余列和组合索引，避免报告与异常列表反复 join；
-- 5. 暂不增加外键。现有归档、逻辑删除和历史证据保留流程尚未统一，过早添加级联约束会改变线上行为；
-- 6. PostgreSQL DDL 只负责目标空 schema 基线；MySQL 历史数据迁移由后续双写/校验/切流脚本独立负责。

SET search_path TO data_quality, public;

CREATE TABLE quality_rule (
    tenant_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL DEFAULT 1,
    workspace_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    rule_type VARCHAR(32) NOT NULL,
    target_object VARCHAR(256) NOT NULL,
    target_type VARCHAR(64) NOT NULL DEFAULT 'GENERIC',
    data_source_id BIGINT,
    database_name VARCHAR(128),
    schema_name VARCHAR(128),
    table_name VARCHAR(128),
    field_name VARCHAR(128),
    scan_strategy VARCHAR(64),
    target_validation_status VARCHAR(32) NOT NULL DEFAULT 'UNVALIDATED',
    target_validation_message VARCHAR(1000),
    target_validated_time TIMESTAMP WITHOUT TIME ZONE,
    comparison_operator VARCHAR(16) NOT NULL,
    expected_value NUMERIC(20, 4) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    description VARCHAR(512),
    status VARCHAR(32) NOT NULL,
    rule_version INTEGER NOT NULL DEFAULT 1,
    last_check_time TIMESTAMP WITHOUT TIME ZONE,
    last_check_status VARCHAR(16),
    last_report_id BIGINT,
    archived_time TIMESTAMP WITHOUT TIME ZONE,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_quality_rule_tenant_project_name UNIQUE (tenant_id, project_id, name),
    CONSTRAINT ck_quality_rule_scope_positive CHECK (tenant_id > 0 AND project_id > 0),
    CONSTRAINT ck_quality_rule_version_positive CHECK (rule_version > 0)
);

COMMENT ON TABLE quality_rule IS '质量规则定义表，保存判断标准、目标定位、生命周期及最近执行摘要';
COMMENT ON COLUMN quality_rule.tenant_id IS '租户隔离边界，用于配额、审计和规则模板共享';
COMMENT ON COLUMN quality_rule.project_id IS '项目隔离边界，用于 PROJECT 数据范围';
COMMENT ON COLUMN quality_rule.workspace_id IS '可选工作空间边界，用于研发、测试、生产空间隔离';
COMMENT ON COLUMN quality_rule.id IS '规则主键，PostgreSQL identity 自动生成';
COMMENT ON COLUMN quality_rule.name IS '租户和项目内唯一的规则名称';
COMMENT ON COLUMN quality_rule.rule_type IS '质量维度或规则分类';
COMMENT ON COLUMN quality_rule.target_object IS '被检测对象的人类可读快照';
COMMENT ON COLUMN quality_rule.target_type IS '目标类型，决定扫描策略';
COMMENT ON COLUMN quality_rule.data_source_id IS 'datasource-management 数据源引用，不保存连接凭据';
COMMENT ON COLUMN quality_rule.target_validation_status IS '最近一次目标校验状态';
COMMENT ON COLUMN quality_rule.expected_value IS '期望值或判断阈值';
COMMENT ON COLUMN quality_rule.status IS 'DRAFT、ACTIVE、INACTIVE、ARCHIVED、DELETED 等生命周期状态';
COMMENT ON COLUMN quality_rule.rule_version IS '规则定义版本，修改业务定义时递增';
COMMENT ON COLUMN quality_rule.create_time IS '创建时间，应用统一按 UTC 解释';
COMMENT ON COLUMN quality_rule.update_time IS '最后更新时间，应用统一按 UTC 解释';

CREATE INDEX idx_quality_rule_tenant_project_status
    ON quality_rule (tenant_id, project_id, status);
CREATE INDEX idx_quality_rule_workspace_status
    ON quality_rule (tenant_id, workspace_id, status);
CREATE INDEX idx_quality_rule_type ON quality_rule (rule_type);
CREATE INDEX idx_quality_rule_target_type ON quality_rule (target_type);
CREATE INDEX idx_quality_rule_datasource ON quality_rule (data_source_id);
CREATE INDEX idx_quality_rule_table_field ON quality_rule (table_name, field_name);
CREATE INDEX idx_quality_rule_validation_status ON quality_rule (target_validation_status);
CREATE INDEX idx_quality_rule_status ON quality_rule (status);
CREATE INDEX idx_quality_rule_last_check ON quality_rule (last_check_time);

CREATE TABLE quality_check_execution (
    tenant_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL DEFAULT 1,
    workspace_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    execution_no BIGINT NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    execution_state VARCHAR(32) NOT NULL,
    operator VARCHAR(128),
    task_id BIGINT,
    task_run_id BIGINT,
    executor_id VARCHAR(128),
    started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    duration_ms BIGINT,
    report_id BIGINT,
    scan_plan_snapshot TEXT,
    message VARCHAR(1000),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_quality_execution_rule_no UNIQUE (rule_id, execution_no),
    CONSTRAINT ck_quality_execution_scope_positive CHECK (tenant_id > 0 AND project_id > 0),
    CONSTRAINT ck_quality_execution_no_positive CHECK (execution_no > 0),
    CONSTRAINT ck_quality_execution_duration_non_negative CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

COMMENT ON TABLE quality_check_execution IS '质量检测运行事实，区分执行是否成功与报告业务结果是否通过';
COMMENT ON COLUMN quality_check_execution.tenant_id IS '冗余租户边界，支撑租户级失败率和资源统计';
COMMENT ON COLUMN quality_check_execution.project_id IS '冗余项目边界，支撑项目执行历史和 SLA';
COMMENT ON COLUMN quality_check_execution.workspace_id IS '冗余工作空间边界';
COMMENT ON COLUMN quality_check_execution.execution_no IS '同一规则内单调递增的业务执行序号';
COMMENT ON COLUMN quality_check_execution.task_id IS 'task-management 任务主键';
COMMENT ON COLUMN quality_check_execution.task_run_id IS 'task-management 单次运行主键';
COMMENT ON COLUMN quality_check_execution.scan_plan_snapshot IS '低敏扫描计划 JSON 快照，不应包含凭据或原始样本';

CREATE INDEX idx_quality_execution_rule_state
    ON quality_check_execution (rule_id, execution_state, started_at);
CREATE INDEX idx_quality_execution_state_time
    ON quality_check_execution (execution_state, started_at);
CREATE INDEX idx_quality_execution_task_id ON quality_check_execution (task_id);
CREATE INDEX idx_quality_execution_task_run_id ON quality_check_execution (task_run_id);
CREATE INDEX idx_quality_execution_project_state
    ON quality_check_execution (tenant_id, project_id, execution_state, started_at);
CREATE INDEX idx_quality_execution_workspace_state
    ON quality_check_execution (tenant_id, workspace_id, execution_state, started_at);
CREATE INDEX idx_quality_execution_executor
    ON quality_check_execution (executor_id, started_at);

CREATE TABLE quality_check_report (
    tenant_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL DEFAULT 1,
    workspace_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    execution_id BIGINT,
    rule_version INTEGER,
    rule_name VARCHAR(128) NOT NULL,
    rule_type VARCHAR(32),
    target_object VARCHAR(256) NOT NULL,
    severity VARCHAR(16),
    measured_value NUMERIC(20, 4) NOT NULL,
    expected_value NUMERIC(20, 4) NOT NULL,
    comparison_operator VARCHAR(16) NOT NULL,
    check_status VARCHAR(16) NOT NULL,
    sample_size INTEGER NOT NULL,
    exception_count INTEGER NOT NULL,
    pass_rate NUMERIC(10, 4),
    trigger_type VARCHAR(64),
    summary VARCHAR(1024) NOT NULL,
    notes VARCHAR(1024),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_quality_report_scope_positive CHECK (tenant_id > 0 AND project_id > 0),
    CONSTRAINT ck_quality_report_counts_non_negative
        CHECK (sample_size >= 0 AND exception_count >= 0),
    CONSTRAINT ck_quality_report_pass_rate
        CHECK (pass_rate IS NULL OR (pass_rate >= 0 AND pass_rate <= 1))
);

COMMENT ON TABLE quality_check_report IS '质量检测结果快照，保留当时的规则版本、阈值和目标语义';
COMMENT ON COLUMN quality_check_report.tenant_id IS '冗余租户边界，用于报告审计与保留策略';
COMMENT ON COLUMN quality_check_report.project_id IS '冗余项目边界，用于质量大盘和权限过滤';
COMMENT ON COLUMN quality_check_report.execution_id IS '对应的质量检测执行记录';
COMMENT ON COLUMN quality_check_report.measured_value IS '本次实际观测值';
COMMENT ON COLUMN quality_check_report.expected_value IS '执行时的规则阈值快照';
COMMENT ON COLUMN quality_check_report.pass_rate IS '通过率比例值，范围 0 至 1';

CREATE INDEX idx_quality_report_rule_id ON quality_check_report (rule_id);
CREATE INDEX idx_quality_report_project_status_time
    ON quality_check_report (tenant_id, project_id, check_status, create_time);
CREATE INDEX idx_quality_report_workspace_time
    ON quality_check_report (tenant_id, workspace_id, create_time);
CREATE INDEX idx_quality_report_rule_type ON quality_check_report (rule_type);
CREATE INDEX idx_quality_report_execution_id ON quality_check_report (execution_id);
CREATE INDEX idx_quality_report_status ON quality_check_report (check_status);
CREATE INDEX idx_quality_report_severity ON quality_check_report (severity);
CREATE INDEX idx_quality_report_target_object ON quality_check_report (target_object);
CREATE INDEX idx_quality_report_trigger_type ON quality_check_report (trigger_type);
CREATE INDEX idx_quality_report_create_time ON quality_check_report (create_time);

CREATE TABLE quality_anomaly_detail (
    tenant_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL DEFAULT 1,
    workspace_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    rule_id BIGINT NOT NULL,
    target_object VARCHAR(256) NOT NULL,
    anomaly_type VARCHAR(64),
    field_name VARCHAR(128),
    record_identifier VARCHAR(256),
    observed_value VARCHAR(1024),
    expected_value VARCHAR(1024),
    severity VARCHAR(16),
    recommendation VARCHAR(1024),
    sample_payload VARCHAR(4000),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_quality_anomaly_scope_positive CHECK (tenant_id > 0 AND project_id > 0)
);

COMMENT ON TABLE quality_anomaly_detail IS '样本级异常证据，用于下钻、根因分析和治理任务创建';
COMMENT ON COLUMN quality_anomaly_detail.tenant_id IS '异常样本的租户隔离边界';
COMMENT ON COLUMN quality_anomaly_detail.project_id IS '异常工作台和治理任务的项目隔离边界';
COMMENT ON COLUMN quality_anomaly_detail.record_identifier IS '低敏记录定位摘要，不应保存凭据';
COMMENT ON COLUMN quality_anomaly_detail.observed_value IS '异常观测值，展示与导出时必须执行脱敏策略';
COMMENT ON COLUMN quality_anomaly_detail.sample_payload IS '脱敏且截断后的样本上下文，禁止保存完整原始记录';

CREATE INDEX idx_quality_anomaly_report_id ON quality_anomaly_detail (report_id);
CREATE INDEX idx_quality_anomaly_rule_id ON quality_anomaly_detail (rule_id);
CREATE INDEX idx_quality_anomaly_project_type_time
    ON quality_anomaly_detail (tenant_id, project_id, anomaly_type, create_time);
CREATE INDEX idx_quality_anomaly_workspace_time
    ON quality_anomaly_detail (tenant_id, workspace_id, create_time);
CREATE INDEX idx_quality_anomaly_type ON quality_anomaly_detail (anomaly_type);
CREATE INDEX idx_quality_anomaly_field_name ON quality_anomaly_detail (field_name);
CREATE INDEX idx_quality_anomaly_severity ON quality_anomaly_detail (severity);
CREATE INDEX idx_quality_anomaly_target_object ON quality_anomaly_detail (target_object);
CREATE INDEX idx_quality_anomaly_rule_field_time
    ON quality_anomaly_detail (rule_id, field_name, create_time);
CREATE INDEX idx_quality_anomaly_report_type_time
    ON quality_anomaly_detail (report_id, anomaly_type, create_time);
CREATE INDEX idx_quality_anomaly_create_time ON quality_anomaly_detail (create_time);
