-- DataSmart Govern - task-management PostgreSQL 基线。
--
-- 迁移原则：
-- 1. 本脚本只创建 task-management 当前 Java 实体、Mapper 和服务逻辑真实使用的 8 张任务域表。
--    旧 MySQL 初始化脚本里混放的 agent_async_task_command_outbox、agent_run_tool_dag_confirmation、
--    agent_memory_* 等表不属于本模块，后续应分别进入 agent-runtime / ai_memory 迁移批次。
-- 2. task_data_sync_worker_command_outbox 与 task_data_sync_worker_execution_receipt 虽然名字包含 data_sync，
--    但它们表达的是 task-management 对下游 data-sync worker 的命令账本和执行投影，归属 task_management schema。
-- 3. 主键统一使用 GENERATED BY DEFAULT AS IDENTITY，既支持 MyBatis-Plus 自动回填，也支持后续存量迁移保留旧 MySQL ID。
-- 4. Java LocalDateTime 对应 TIMESTAMP WITHOUT TIME ZONE，避免迁移期被数据库 session 时区隐式改写审计事实。
-- 5. MySQL TINYINT(1) 转 PostgreSQL BOOLEAN，让 attentionRequired、payloadTruncated、sideEffectStarted 等开关字段语义清晰。
-- 6. JSON 字段当前保持 TEXT，因为 Java 实体均为 String；未来升级 JSONB 时必须同步 TypeHandler、查询 SQL 和迁移脚本 checksum。
-- 7. 本脚本暂不创建外键和级联删除。任务、执行、日志、幂等、outbox 和 receipt 都是生产证据，删除/归档应由保留期任务显式治理。
-- 8. DDL 只负责新安装空库基线；已有 MySQL 历史数据需要后续独立脚手架执行导出、导入、对账和 sequence 校正。

SET search_path TO task_management, public;

CREATE TABLE IF NOT EXISTS task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(50) NOT NULL,
    creation_idempotency_key VARCHAR(180),
    tenant_id BIGINT,
    owner_id BIGINT,
    project_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    params TEXT,
    progress INTEGER DEFAULT 0,
    checkpoint TEXT,
    priority VARCHAR(10) DEFAULT 'MEDIUM',
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retry_count INTEGER NOT NULL DEFAULT 3,
    defer_count INTEGER NOT NULL DEFAULT 0,
    max_defer_count INTEGER NOT NULL DEFAULT 20,
    current_execution_run_id BIGINT,
    current_executor_id VARCHAR(128),
    queued_time TIMESTAMP WITHOUT TIME ZONE,
    heartbeat_time TIMESTAMP WITHOUT TIME ZONE,
    lease_expire_time TIMESTAMP WITHOUT TIME ZONE,
    attention_required BOOLEAN NOT NULL DEFAULT FALSE,
    timeout_seconds INTEGER NOT NULL DEFAULT 3600,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    end_time TIMESTAMP WITHOUT TIME ZONE,
    result TEXT,
    CONSTRAINT uk_task_creation_idempotency_key UNIQUE (creation_idempotency_key),
    CONSTRAINT ck_task_progress_range CHECK (progress IS NULL OR (progress >= 0 AND progress <= 100)),
    CONSTRAINT ck_task_retry_non_negative CHECK (
        retry_count >= 0 AND max_retry_count >= 0 AND defer_count >= 0 AND max_defer_count >= 0 AND timeout_seconds >= 0
    ),
    CONSTRAINT ck_task_priority CHECK (priority IS NULL OR priority IN ('HIGH', 'MEDIUM', 'LOW')),
    CONSTRAINT ck_task_status CHECK (status IN (
        'PENDING', 'RUNNING', 'PAUSED', 'SUCCESS', 'FAILED', 'CANCELLED',
        'RETRYING', 'DEFERRED', 'DEAD_LETTER'
    ))
);

COMMENT ON TABLE task IS '任务聚合主表，保存任务当前快照、队列状态、执行租约、重试退避、进度和最近结果';
COMMENT ON COLUMN task.creation_idempotency_key IS '任务创建幂等键；跨服务重试时复用同一任务，禁止保存业务正文、SQL、prompt、样本、凭据或内部 URL';
COMMENT ON COLUMN task.tenant_id IS '任务所属租户 ID，用于多租户数据隔离、租户级队列公平性、SLA 和审计查询；允许为空兼容早期历史任务';
COMMENT ON COLUMN task.owner_id IS '任务负责人 ID，用于我的任务、失败通知、责任归属、人工待办和运营排障';
COMMENT ON COLUMN task.project_id IS '任务所属项目 ID，用于项目级配额、项目级看板、项目负责人审批和成本审计';
COMMENT ON COLUMN task.status IS '任务主状态；Service 层负责维护合法流转，数据库 CHECK 只防止明显非法值进入';
COMMENT ON COLUMN task.params IS '任务输入参数 JSON 文本；当前保持 String 映射，禁止直接暴露敏感参数或大样本';
COMMENT ON COLUMN task.checkpoint IS '断点续跑或失败恢复所需的低敏检查点摘要';
COMMENT ON COLUMN task.defer_count IS '当前连续延迟回队列次数，用于识别容量背压是否形成无限循环';
COMMENT ON COLUMN task.current_execution_run_id IS '当前执行记录 ID，用于任务详情快速定位正在运行的执行尝试';
COMMENT ON COLUMN task.current_executor_id IS '当前认领任务的执行器实例 ID，心跳和完成回调必须与该值一致';
COMMENT ON COLUMN task.queued_time IS '最近一次进入可调度队列的时间，DEFERRED 任务会被推迟到未来时间';
COMMENT ON COLUMN task.lease_expire_time IS '当前执行租约过期时间，超过后可被恢复扫描识别为执行器失联';
COMMENT ON COLUMN task.attention_required IS '是否需要运营人员关注，例如租约超时、重试耗尽或长时间排队';
COMMENT ON COLUMN task.result IS '最近一次结果或失败摘要；完整过程仍应查看 task_execution_log 和 task_execution_run';

CREATE INDEX IF NOT EXISTS idx_task_status ON task (status);
CREATE INDEX IF NOT EXISTS idx_task_type ON task (type);
CREATE INDEX IF NOT EXISTS idx_task_tenant_status_time ON task (tenant_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_task_owner_status_time ON task (owner_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_task_project_status_time ON task (project_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_task_create_time ON task (create_time);
CREATE INDEX IF NOT EXISTS idx_task_queue_claim ON task (status, queued_time, priority, create_time);
CREATE INDEX IF NOT EXISTS idx_task_tenant_queue_claim ON task (tenant_id, status, queued_time, priority, create_time);
CREATE INDEX IF NOT EXISTS idx_task_executor_lease ON task (current_executor_id, lease_expire_time);
CREATE INDEX IF NOT EXISTS idx_task_attention ON task (attention_required, update_time);

CREATE TABLE IF NOT EXISTS task_draft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(50) NOT NULL,
    tenant_id BIGINT,
    owner_id BIGINT,
    project_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    params TEXT,
    priority VARCHAR(10) DEFAULT 'MEDIUM',
    max_retry_count INTEGER NOT NULL DEFAULT 3,
    max_defer_count INTEGER NOT NULL DEFAULT 20,
    source_type VARCHAR(32) DEFAULT 'MANUAL',
    source_ref VARCHAR(255),
    created_by BIGINT,
    submitted_by BIGINT,
    approved_by BIGINT,
    approval_comment TEXT,
    converted_task_id BIGINT,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    submit_time TIMESTAMP WITHOUT TIME ZONE,
    approval_time TIMESTAMP WITHOUT TIME ZONE,
    convert_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ck_task_draft_status CHECK (status IN (
        'DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'CONVERTING', 'REJECTED', 'CONVERTED'
    )),
    CONSTRAINT ck_task_draft_priority CHECK (priority IS NULL OR priority IN ('HIGH', 'MEDIUM', 'LOW')),
    CONSTRAINT ck_task_draft_retry_non_negative CHECK (max_retry_count >= 0 AND max_defer_count >= 0)
);

COMMENT ON TABLE task_draft IS '任务草稿表，用于 Agent、模板和人工配置生成待审批任务，草稿不会被执行器认领';
COMMENT ON COLUMN task_draft.status IS '草稿状态；CONVERTING 是并发转换门闩，避免多请求重复创建真实任务';
COMMENT ON COLUMN task_draft.params IS '草稿参数 JSON 文本；转换真实任务前仍需按任务类型执行 schema 校验';
COMMENT ON COLUMN task_draft.source_type IS '草稿来源类型，例如 AGENT、TEMPLATE、MANUAL、API';
COMMENT ON COLUMN task_draft.source_ref IS '来源引用，例如 Agent auditId、任务模板 ID 或外部工单号';
COMMENT ON COLUMN task_draft.converted_task_id IS '转换得到的真实任务 ID；重复转换可直接返回该任务，避免二次创建';

CREATE INDEX IF NOT EXISTS idx_task_draft_status_time ON task_draft (status, create_time);
CREATE INDEX IF NOT EXISTS idx_task_draft_tenant_status_time ON task_draft (tenant_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_task_draft_project_status_time ON task_draft (project_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_task_draft_owner_status_time ON task_draft (owner_id, status, create_time);
CREATE INDEX IF NOT EXISTS idx_task_draft_source ON task_draft (source_type, source_ref);
CREATE INDEX IF NOT EXISTS idx_task_draft_converted_task ON task_draft (converted_task_id);

CREATE TABLE IF NOT EXISTS task_execution_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    action VARCHAR(32) NOT NULL,
    from_status VARCHAR(20),
    to_status VARCHAR(20),
    message VARCHAR(255) NOT NULL,
    operator VARCHAR(64) DEFAULT 'system',
    details TEXT,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

COMMENT ON TABLE task_execution_log IS '任务执行日志表，记录任务为什么走到当前状态，是追踪、审计、回放和故障复盘的基础';
COMMENT ON COLUMN task_execution_log.action IS '执行动作，例如 CREATE、START、PROGRESS、DEFER、RETRY、COMPLETE、FAIL、CANCEL';
COMMENT ON COLUMN task_execution_log.from_status IS '变更前状态；创建或纯过程日志可能为空';
COMMENT ON COLUMN task_execution_log.to_status IS '变更后状态；PROGRESS 类日志前后状态可能相同';
COMMENT ON COLUMN task_execution_log.details IS '低敏详细上下文，可包含 checkpoint、失败摘要、重试次数等，禁止保存凭据、SQL、样本或 prompt';

CREATE INDEX IF NOT EXISTS idx_task_execution_log_task_time ON task_execution_log (task_id, create_time);

CREATE TABLE IF NOT EXISTS task_execution_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    run_no BIGINT NOT NULL,
    executor_id VARCHAR(128) NOT NULL,
    state VARCHAR(32) NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    triggered_by BIGINT,
    started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    heartbeat_at TIMESTAMP WITHOUT TIME ZONE,
    lease_expire_time TIMESTAMP WITHOUT TIME ZONE,
    progress INTEGER DEFAULT 0,
    checkpoint TEXT,
    error_message TEXT,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_task_execution_run_no UNIQUE (task_id, run_no),
    CONSTRAINT ck_task_execution_run_progress_range CHECK (progress IS NULL OR (progress >= 0 AND progress <= 100)),
    CONSTRAINT ck_task_execution_run_state CHECK (state IN (
        'RUNNING', 'SUCCESS', 'FAILED', 'DEFERRED', 'TIMEOUT', 'CANCELLED'
    ))
);

COMMENT ON TABLE task_execution_run IS '任务执行尝试记录表；同一任务可多次执行，每一次 run 都保存独立租约、进度、结果和错误摘要';
COMMENT ON COLUMN task_execution_run.run_no IS '同一任务下第几次执行，失败重试后递增';
COMMENT ON COLUMN task_execution_run.executor_id IS '执行器实例 ID，例如 worker、Pod、机器或 Agent Runtime 实例';
COMMENT ON COLUMN task_execution_run.trigger_type IS '触发类型，例如 EXECUTOR_CLAIM、MANUAL_RETRY、SCHEDULED 或 AGENT_COMMAND';
COMMENT ON COLUMN task_execution_run.heartbeat_at IS '最近一次心跳时间，用于判断执行器是否仍然存活';
COMMENT ON COLUMN task_execution_run.lease_expire_time IS '执行租约过期时间，恢复扫描会按该字段识别失联 run';
COMMENT ON COLUMN task_execution_run.checkpoint IS '本次执行最近检查点，用于断点续跑或人工复盘';

CREATE INDEX IF NOT EXISTS idx_task_execution_run_state_lease ON task_execution_run (state, lease_expire_time);
CREATE INDEX IF NOT EXISTS idx_task_execution_run_executor ON task_execution_run (executor_id, state, lease_expire_time);
CREATE INDEX IF NOT EXISTS idx_task_execution_run_task_time ON task_execution_run (task_id, started_at);

CREATE TABLE IF NOT EXISTS task_callback_idempotency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    action VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    run_id BIGINT NOT NULL,
    executor_id VARCHAR(128) NOT NULL,
    request_digest VARCHAR(1000),
    callback_state VARCHAR(32) NOT NULL,
    response_summary VARCHAR(1000),
    error_message VARCHAR(1000),
    first_seen_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_seen_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_task_callback_idempotency UNIQUE (task_id, action, idempotency_key),
    CONSTRAINT ck_task_callback_state CHECK (callback_state IN ('PROCESSING', 'SUCCEEDED', 'FAILED'))
);

COMMENT ON TABLE task_callback_idempotency IS '任务执行器回调幂等记录表，用数据库唯一约束保护 progress、complete、fail、defer 等回调不被重复推进';
COMMENT ON COLUMN task_callback_idempotency.idempotency_key IS '调用方生成的幂等键；同一次业务动作重试必须复用同一个键';
COMMENT ON COLUMN task_callback_idempotency.run_id IS '回调所属执行 run ID；用于阻止旧 run 的迟到回调污染新 run';
COMMENT ON COLUMN task_callback_idempotency.request_digest IS '请求摘要，只保存排障所需短文本，不保存完整请求体、敏感参数或大结果';
COMMENT ON COLUMN task_callback_idempotency.callback_state IS 'PROCESSING 表示正在处理，SUCCEEDED 表示已成功落地，FAILED 为后续失败审计预留';
COMMENT ON COLUMN task_callback_idempotency.last_seen_time IS '最近一次看到该幂等键的时间；重复回调只刷新该字段，不再推进任务状态';

CREATE INDEX IF NOT EXISTS idx_task_callback_run_action ON task_callback_idempotency (run_id, action);
CREATE INDEX IF NOT EXISTS idx_task_callback_executor_time ON task_callback_idempotency (executor_id, last_seen_time);
CREATE INDEX IF NOT EXISTS idx_task_callback_state_time ON task_callback_idempotency (callback_state, last_seen_time);

CREATE TABLE IF NOT EXISTS agent_async_task_command_inbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    schema_version VARCHAR(80) NOT NULL,
    command_type VARCHAR(80) NOT NULL,
    audit_id VARCHAR(128) NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    tool_code VARCHAR(128) NOT NULL,
    target_service VARCHAR(128) NOT NULL,
    target_endpoint VARCHAR(300),
    tenant_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    workspace_id BIGINT,
    actor_id VARCHAR(128) NOT NULL,
    trace_id VARCHAR(128) NOT NULL,
    payload_reference VARCHAR(512) NOT NULL,
    argument_names TEXT NOT NULL,
    sensitive_argument_names TEXT NOT NULL,
    consume_state VARCHAR(32) NOT NULL,
    task_id BIGINT,
    first_seen_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_seen_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_agent_async_task_command_id UNIQUE (command_id),
    CONSTRAINT uk_agent_async_task_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_agent_async_task_scope_positive CHECK (tenant_id > 0 AND project_id > 0),
    CONSTRAINT ck_agent_async_task_consume_state CHECK (consume_state IN ('PROCESSING', 'TASK_CREATED'))
);

COMMENT ON TABLE agent_async_task_command_inbox IS 'Agent 异步工具命令 Inbox 表，用本地唯一约束保护 Kafka 重放、消费者重启和人工重放不重复创建任务';
COMMENT ON COLUMN agent_async_task_command_inbox.command_id IS 'Agent Runtime 生成的稳定命令 ID，同一命令只能转换成一条任务';
COMMENT ON COLUMN agent_async_task_command_inbox.idempotency_key IS '跨服务幂等键，Kafka 重投、消费者重启和人工重放必须复用相同值';
COMMENT ON COLUMN agent_async_task_command_inbox.target_endpoint IS '工具目录声明的目标端点模板；新受控工具动作可为空，由执行器重新解析白名单目标';
COMMENT ON COLUMN agent_async_task_command_inbox.tenant_id IS '租户隔离边界；异步自动化动作禁止缺失';
COMMENT ON COLUMN agent_async_task_command_inbox.workspace_id IS 'Agent 工作空间隔离边界；部分新受控命令可在后续 payload store 或执行器阶段补强';
COMMENT ON COLUMN agent_async_task_command_inbox.payload_reference IS '受控载荷引用，只保存安全引用，不保存原始工具参数值';
COMMENT ON COLUMN agent_async_task_command_inbox.argument_names IS '参数名 JSON 文本，只保存字段名，不保存参数值';
COMMENT ON COLUMN agent_async_task_command_inbox.sensitive_argument_names IS '敏感参数名 JSON 文本，用于执行前脱敏、审批和审计复核';
COMMENT ON COLUMN agent_async_task_command_inbox.consume_state IS 'Inbox 消费状态，例如 PROCESSING、TASK_CREATED';

CREATE INDEX IF NOT EXISTS idx_agent_async_task_audit ON agent_async_task_command_inbox (audit_id);
CREATE INDEX IF NOT EXISTS idx_agent_async_task_run ON agent_async_task_command_inbox (session_id, run_id, consume_state);
CREATE INDEX IF NOT EXISTS idx_agent_async_task_scope_state ON agent_async_task_command_inbox (tenant_id, project_id, workspace_id, consume_state, update_time);
CREATE INDEX IF NOT EXISTS idx_agent_async_task_task ON agent_async_task_command_inbox (task_id);
CREATE INDEX IF NOT EXISTS idx_agent_async_task_state_time ON agent_async_task_command_inbox (consume_state, update_time);

CREATE TABLE IF NOT EXISTS task_data_sync_worker_command_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id VARCHAR(300) NOT NULL,
    command_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    task_id BIGINT NOT NULL,
    agent_run_id VARCHAR(128) NOT NULL,
    agent_session_id VARCHAR(128),
    audit_id VARCHAR(128),
    tool_code VARCHAR(128) NOT NULL,
    target_service VARCHAR(128) NOT NULL,
    operation VARCHAR(80) NOT NULL,
    tenant_id BIGINT,
    project_id BIGINT,
    workspace_id BIGINT,
    actor_id VARCHAR(128),
    trace_id VARCHAR(128),
    template_id BIGINT,
    sync_template_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    payload_json TEXT NOT NULL,
    payload_size_bytes INTEGER NOT NULL DEFAULT 0,
    payload_truncated BOOLEAN NOT NULL DEFAULT FALSE,
    next_retry_at TIMESTAMP WITHOUT TIME ZONE,
    dispatched_at TIMESTAMP WITHOUT TIME ZONE,
    receipt_id VARCHAR(180),
    sync_task_id BIGINT,
    sync_execution_id BIGINT,
    side_effect_started BOOLEAN NOT NULL DEFAULT FALSE,
    side_effect_executed BOOLEAN NOT NULL DEFAULT FALSE,
    last_error VARCHAR(1024),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_task_datasync_worker_outbox_id UNIQUE (outbox_id),
    CONSTRAINT uk_task_datasync_worker_command_id UNIQUE (command_id),
    CONSTRAINT uk_task_datasync_worker_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uk_task_datasync_worker_receipt_id UNIQUE (receipt_id),
    CONSTRAINT ck_task_datasync_worker_attempt_non_negative CHECK (attempt_count >= 0 AND payload_size_bytes >= 0),
    CONSTRAINT ck_task_datasync_worker_status CHECK (status IN (
        'PENDING', 'DISPATCHING', 'DEFERRED', 'SUCCEEDED', 'FAILED', 'DEAD_LETTER', 'CLOSED'
    ))
);

COMMENT ON TABLE task_data_sync_worker_command_outbox IS 'task-management 到 data-sync worker 的命令 outbox 表，保存低敏跨服务命令事实和投递状态';
COMMENT ON COLUMN task_data_sync_worker_command_outbox.outbox_id IS 'task-management 本地 outbox 记录唯一 ID，建议由 command_id 派生';
COMMENT ON COLUMN task_data_sync_worker_command_outbox.command_id IS 'Agent Runtime 稳定命令 ID，同一 command 只能对应一条 data-sync worker outbox';
COMMENT ON COLUMN task_data_sync_worker_command_outbox.idempotency_key IS '跨服务幂等键，也会传给 data-sync 内部入口';
COMMENT ON COLUMN task_data_sync_worker_command_outbox.agent_run_id IS 'Agent Runtime run ID，与 task_execution_run 不是同一 ID 空间';
COMMENT ON COLUMN task_data_sync_worker_command_outbox.operation IS '命令操作类型，例如 DATA_SYNC_EXECUTE，未来可扩展 CANCEL、BACKFILL、RUN_BATCH_ONCE';
COMMENT ON COLUMN task_data_sync_worker_command_outbox.payload_json IS '低敏命令 payload JSON 文本，禁止包含工具实参正文、SQL、凭据、样本数据、prompt 或模型输出';
COMMENT ON COLUMN task_data_sync_worker_command_outbox.payload_truncated IS 'payload 是否被截断或阻断；正常实现不应截断，超限应阻断命令而不是悄悄执行';
COMMENT ON COLUMN task_data_sync_worker_command_outbox.side_effect_started IS '是否已经越过调用下游的副作用边界，用于失败恢复判断';
COMMENT ON COLUMN task_data_sync_worker_command_outbox.side_effect_executed IS '下游是否确认副作用已被接受或执行，用于防止重复提交';
COMMENT ON COLUMN task_data_sync_worker_command_outbox.last_error IS '最近一次低敏错误摘要，禁止保存连接串、凭据、内部 URL、样本或完整异常堆栈';

CREATE INDEX IF NOT EXISTS idx_task_datasync_worker_status_retry ON task_data_sync_worker_command_outbox (status, next_retry_at, id);
CREATE INDEX IF NOT EXISTS idx_task_datasync_worker_task_status ON task_data_sync_worker_command_outbox (task_id, status, id);
CREATE INDEX IF NOT EXISTS idx_task_datasync_worker_scope_time ON task_data_sync_worker_command_outbox (tenant_id, project_id, workspace_id, update_time);
CREATE INDEX IF NOT EXISTS idx_task_datasync_worker_sync_ref ON task_data_sync_worker_command_outbox (sync_task_id, sync_execution_id);
CREATE INDEX IF NOT EXISTS idx_task_datasync_worker_agent_run ON task_data_sync_worker_command_outbox (agent_run_id, agent_session_id, status);

CREATE TABLE IF NOT EXISTS task_data_sync_worker_execution_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id VARCHAR(220) NOT NULL,
    command_id VARCHAR(128) NOT NULL,
    outbox_id VARCHAR(300) NOT NULL,
    task_id BIGINT NOT NULL,
    agent_run_id VARCHAR(128),
    agent_session_id VARCHAR(128),
    audit_id VARCHAR(128),
    tenant_id BIGINT,
    project_id BIGINT,
    workspace_id BIGINT,
    sync_task_id BIGINT NOT NULL,
    sync_execution_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    event_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    executor_id VARCHAR(128),
    source_service VARCHAR(128) NOT NULL DEFAULT 'datasource-management',
    batch_records_read BIGINT NOT NULL DEFAULT 0,
    batch_records_written BIGINT NOT NULL DEFAULT 0,
    batch_failed_record_count BIGINT NOT NULL DEFAULT 0,
    total_records_read BIGINT NOT NULL DEFAULT 0,
    total_records_written BIGINT NOT NULL DEFAULT 0,
    total_failed_record_count BIGINT NOT NULL DEFAULT 0,
    progress_percent INTEGER,
    end_of_source BOOLEAN NOT NULL DEFAULT FALSE,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    failed BOOLEAN NOT NULL DEFAULT FALSE,
    progress_reported BOOLEAN NOT NULL DEFAULT FALSE,
    checkpoint_persisted BOOLEAN NOT NULL DEFAULT FALSE,
    checkpoint_type VARCHAR(80),
    checkpoint_value_visibility VARCHAR(160),
    error_summary VARCHAR(500),
    warning_count INTEGER NOT NULL DEFAULT 0,
    warning_summary VARCHAR(1000),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_task_datasync_exec_receipt_id UNIQUE (receipt_id),
    CONSTRAINT ck_task_datasync_exec_counts_non_negative CHECK (
        batch_records_read >= 0
        AND batch_records_written >= 0
        AND batch_failed_record_count >= 0
        AND total_records_read >= 0
        AND total_records_written >= 0
        AND total_failed_record_count >= 0
        AND warning_count >= 0
    ),
    CONSTRAINT ck_task_datasync_exec_progress CHECK (progress_percent IS NULL OR (progress_percent >= 0 AND progress_percent <= 100)),
    CONSTRAINT ck_task_datasync_exec_event_type CHECK (event_type IN ('PROGRESS', 'CHECKPOINT', 'COMPLETE', 'PARTIALLY_SUCCEEDED', 'FAILED'))
);

COMMENT ON TABLE task_data_sync_worker_execution_receipt IS 'task-management 保存 data-sync/datasource-management Runner 低敏执行回执投影，用于任务中心和 Agent timeline 还原端到端历史';
COMMENT ON COLUMN task_data_sync_worker_execution_receipt.receipt_id IS '执行回执幂等 ID；同一个下游事件重试回写必须复用该值';
COMMENT ON COLUMN task_data_sync_worker_execution_receipt.command_id IS 'Agent Runtime command ID，用于从工具命令维度串联端到端历史';
COMMENT ON COLUMN task_data_sync_worker_execution_receipt.outbox_id IS 'task-management 本地 DataSync worker outbox ID';
COMMENT ON COLUMN task_data_sync_worker_execution_receipt.event_type IS '执行事件类型：PROGRESS、CHECKPOINT、COMPLETE、PARTIALLY_SUCCEEDED、FAILED；部分成功表示已有对象完成但仍有失败对象需要选择性重试';
COMMENT ON COLUMN task_data_sync_worker_execution_receipt.event_time IS '下游事件发生时间；缺省时由服务层使用 task-management 接收时间';
COMMENT ON COLUMN task_data_sync_worker_execution_receipt.executor_id IS '下游 Runner/worker 执行器 ID，用于排障定位，不作为权限判断依据';
COMMENT ON COLUMN task_data_sync_worker_execution_receipt.progress_percent IS '进度百分比；流式、CDC 或未知总量任务允许为空';
COMMENT ON COLUMN task_data_sync_worker_execution_receipt.checkpoint_value_visibility IS '检查点值可见性策略，例如 HASHED、HIDDEN、WINDOW_ONLY，禁止保存 checkpoint 原始值';
COMMENT ON COLUMN task_data_sync_worker_execution_receipt.error_summary IS '服务端脱敏后的低敏错误摘要；普通 API 视图默认不返回正文';
COMMENT ON COLUMN task_data_sync_worker_execution_receipt.warning_summary IS '服务端脱敏后的 warning 摘要；普通 API 视图默认不返回正文';

CREATE INDEX IF NOT EXISTS idx_task_datasync_exec_command_time ON task_data_sync_worker_execution_receipt (command_id, event_time, id);
CREATE INDEX IF NOT EXISTS idx_task_datasync_exec_sync_ref ON task_data_sync_worker_execution_receipt (sync_task_id, sync_execution_id, event_time);
CREATE INDEX IF NOT EXISTS idx_task_datasync_exec_task_time ON task_data_sync_worker_execution_receipt (task_id, event_time);
CREATE INDEX IF NOT EXISTS idx_task_datasync_exec_scope_time ON task_data_sync_worker_execution_receipt (tenant_id, project_id, workspace_id, event_time);
CREATE INDEX IF NOT EXISTS idx_task_datasync_exec_event_time ON task_data_sync_worker_execution_receipt (event_type, event_time);
