-- DataSmart Govern Backend - ai_memory PostgreSQL / pgvector V1 基线。
--
-- 本脚本服务于 Python AI Runtime、LangGraph 多智能体执行、长期记忆和用户画像能力。
-- 它刻意放在 PostgreSQL 初始化目录中，而不是继续放在 docker/mysql/migrations：
-- 1. PostgreSQL/pgvector 已经被确定为项目目标存储，MySQL 只保留迁移期兼容；
-- 2. ai_memory 与 agent_runtime 分 schema 隔离，避免把“Agent 控制面事实”和“模型可召回记忆正文/向量”混在一起；
-- 3. Python Runtime 当前没有 Spring/Flyway 运行时，因此新环境先通过 Compose init 脚本获得可运行基线；
-- 4. 已有 PostgreSQL 数据卷不会自动重跑 init 脚本，存量环境应由运维手工执行本文件或后续专用迁移工具。
--
-- 重要边界：
-- - 本脚本只保存低敏摘要、治理元数据、向量索引和 LangGraph durable state；
-- - 禁止把 prompt、原始 SQL、样本数据、完整工具输出、完整异常堆栈或密钥写入这些表；
-- - 真实客户环境应为 ai_memory 分配独立数据库角色、备份策略、保留期策略和审计权限。

CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS ai_memory AUTHORIZATION datasmart;

SET search_path TO ai_memory, public;

COMMENT ON SCHEMA ai_memory IS
    '用户画像、长期记忆、全文索引、pgvector 语义索引和 LangGraph durable state。该 schema 是 AI Memory 的事实源，不属于 agent_runtime 控制面。';

CREATE TABLE IF NOT EXISTS agent_memory_write_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    project_id VARCHAR(64) NOT NULL,
    actor_id VARCHAR(64) NOT NULL,
    memory_type VARCHAR(32) NOT NULL,
    scope VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content_summary TEXT NOT NULL,
    source VARCHAR(64) NOT NULL,
    workspace_key VARCHAR(255),
    memory_namespace VARCHAR(255),
    source_tool_name VARCHAR(128),
    source_status VARCHAR(64),
    source_audit_id VARCHAR(128),
    source_run_id VARCHAR(128),
    output_ref VARCHAR(512),
    approval_required BOOLEAN NOT NULL DEFAULT FALSE,
    retention_days INTEGER NOT NULL DEFAULT 30,
    sensitivity_level VARCHAR(32) NOT NULL DEFAULT 'internal',
    privacy_notes_json JSONB,
    candidate_version INTEGER NOT NULL DEFAULT 1,
    idempotency_key VARCHAR(512),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at TIMESTAMPTZ,
    decided_by VARCHAR(64),
    decision_reason VARCHAR(1024),
    attributes_json JSONB,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_memory_write_candidate_id UNIQUE (candidate_id),
    CONSTRAINT uk_agent_memory_write_candidate_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT ck_agent_memory_write_candidate_memory_type CHECK (
        memory_type IN ('semantic', 'episodic', 'procedural', 'resource', 'short_term')
    ),
    CONSTRAINT ck_agent_memory_write_candidate_scope CHECK (
        scope IN ('session', 'project', 'tenant', 'global')
    ),
    CONSTRAINT ck_agent_memory_write_candidate_status CHECK (
        status IN ('draft', 'pending_approval', 'approved', 'rejected', 'ignored')
    ),
    CONSTRAINT ck_agent_memory_write_candidate_retention CHECK (retention_days > 0),
    CONSTRAINT ck_agent_memory_write_candidate_version CHECK (candidate_version > 0)
);

COMMENT ON TABLE agent_memory_write_candidate IS
    '长期记忆写入候选表。它表示某次 Agent 工具结果是否允许沉淀为长期记忆，是审批、拒绝、审计和后续物化 worker 的入口。';
COMMENT ON COLUMN agent_memory_write_candidate.candidate_id IS
    '候选业务 ID。审批台、物化 worker、审计表和迁移脚手架都应使用该字段关联，而不是依赖自增主键。';
COMMENT ON COLUMN agent_memory_write_candidate.memory_type IS
    '记忆类型：semantic 表示事实/知识，episodic 表示历史经验，procedural 表示操作流程，resource 表示资源引用，short_term 表示可短期保留的会话经验。';
COMMENT ON COLUMN agent_memory_write_candidate.scope IS
    '未来可见范围。scope 越大，审批、脱敏、保留期和召回过滤越严格；global 不应在普通用户流程中自动产生。';
COMMENT ON COLUMN agent_memory_write_candidate.status IS
    '候选生命周期状态。approved 只表示允许物化，不表示正式记忆已经写入成功；正式落成证据在 receipt 表中。';
COMMENT ON COLUMN agent_memory_write_candidate.workspace_key IS
    'Agent 工作空间隔离键。即使 tenant/project 相同，不同 workspace 的经验也不应默认互相召回。';
COMMENT ON COLUMN agent_memory_write_candidate.memory_namespace IS
    '长期记忆命名空间。SQL 过滤、pgvector metadata filter 和 LangGraph store namespace 必须使用同一边界。';
COMMENT ON COLUMN agent_memory_write_candidate.content_summary IS
    '低敏候选摘要。只允许保存脱敏后的经验描述和引用说明，禁止保存完整工具输出、原始 SQL 或样本数据。';
COMMENT ON COLUMN agent_memory_write_candidate.output_ref IS
    '完整工具结果的外部受控引用，例如 MinIO 对象或 Java 审计引用；读取时仍必须经过权限校验。';
COMMENT ON COLUMN agent_memory_write_candidate.privacy_notes_json IS
    '隐私、脱敏、数据范围和写入前注意事项，供审批人、物化 worker 和审计导出使用。';
COMMENT ON COLUMN agent_memory_write_candidate.idempotency_key IS
    '候选生成幂等键，用于处理 HTTP 重试、Kafka 重放或 Agent loop 恢复后的重复提交。';
COMMENT ON COLUMN agent_memory_write_candidate.created_at IS
    '候选业务创建时间。Python Runtime 现有 SQL store 使用该字段排序，因此 PostgreSQL 基线必须保留。';
COMMENT ON COLUMN agent_memory_write_candidate.create_time IS
    '数据库记录创建时间。保留该字段是为了兼容旧 MySQL 初始化脚本和后续存量迁移对账。';

CREATE INDEX IF NOT EXISTS idx_agent_memory_write_candidate_scope_status
    ON agent_memory_write_candidate (tenant_id, project_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_write_candidate_workspace
    ON agent_memory_write_candidate (tenant_id, project_id, workspace_key, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_write_candidate_type_scope
    ON agent_memory_write_candidate (tenant_id, memory_type, scope, status);
CREATE INDEX IF NOT EXISTS idx_agent_memory_write_candidate_source
    ON agent_memory_write_candidate (source_audit_id, source_run_id);
CREATE INDEX IF NOT EXISTS idx_agent_memory_write_candidate_attributes_gin
    ON agent_memory_write_candidate USING GIN (attributes_json jsonb_path_ops);

CREATE TABLE IF NOT EXISTS agent_memory_write_candidate_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    project_id VARCHAR(64) NOT NULL,
    operator_id VARCHAR(64) NOT NULL,
    action VARCHAR(32) NOT NULL,
    previous_status VARCHAR(32) NOT NULL,
    next_status VARCHAR(32) NOT NULL,
    reason VARCHAR(1024) NOT NULL,
    candidate_version INTEGER NOT NULL,
    decided_at TIMESTAMPTZ,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_agent_memory_write_candidate_audit_action CHECK (
        action IN ('approve', 'reject', 'archive', 'forget', 'reopen')
    ),
    CONSTRAINT ck_agent_memory_write_candidate_audit_version CHECK (candidate_version > 0)
);

COMMENT ON TABLE agent_memory_write_candidate_audit IS
    '长期记忆候选决策审计表。它记录谁在什么时候因为什么原因改变了候选状态，不能只依赖候选主表最后状态。';
COMMENT ON COLUMN agent_memory_write_candidate_audit.reason IS
    '审批或拒绝原因。原因不能为空，但仍必须低敏，不能写入 prompt、SQL、样本数据或完整工具输出。';

CREATE INDEX IF NOT EXISTS idx_agent_memory_write_candidate_audit_candidate
    ON agent_memory_write_candidate_audit (candidate_id, id);
CREATE INDEX IF NOT EXISTS idx_agent_memory_write_candidate_audit_operator
    ON agent_memory_write_candidate_audit (tenant_id, operator_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_write_candidate_audit_project
    ON agent_memory_write_candidate_audit (tenant_id, project_id, create_time DESC);

CREATE TABLE IF NOT EXISTS agent_memory_store_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64),
    project_id VARCHAR(64),
    session_id VARCHAR(128),
    memory_type VARCHAR(32) NOT NULL,
    scope VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    source VARCHAR(128),
    importance_score NUMERIC(10,4) NOT NULL DEFAULT 0.5000,
    sensitivity_level VARCHAR(32) NOT NULL DEFAULT 'internal',
    tags_json JSONB,
    created_at TIMESTAMPTZ,
    attributes_json JSONB,
    workspace_key VARCHAR(255) NOT NULL,
    memory_namespace VARCHAR(255) NOT NULL,
    namespace_json JSONB,
    idempotency_key VARCHAR(512) NOT NULL,
    source_candidate_id VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    materialized_at TIMESTAMPTZ NOT NULL,
    content_search_vector TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('simple', COALESCE(title, '') || ' ' || COALESCE(content, ''))
    ) STORED,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_memory_store_memory_id UNIQUE (memory_id),
    CONSTRAINT uk_agent_memory_store_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uk_agent_memory_store_candidate UNIQUE (source_candidate_id),
    CONSTRAINT ck_agent_memory_store_memory_type CHECK (
        memory_type IN ('semantic', 'episodic', 'procedural', 'resource', 'short_term')
    ),
    CONSTRAINT ck_agent_memory_store_scope CHECK (
        scope IN ('session', 'project', 'tenant', 'global')
    ),
    CONSTRAINT ck_agent_memory_store_importance CHECK (
        importance_score >= 0 AND importance_score <= 1
    )
);

COMMENT ON TABLE agent_memory_store_entry IS
    '正式长期记忆低敏摘要表。它是模型可召回记忆的结构化事实源，pgvector、全文索引、图谱或对象存储都围绕 memory_id 扩展。';
COMMENT ON COLUMN agent_memory_store_entry.content IS
    '正式记忆低敏摘要。该字段可进入模型上下文，因此必须经过脱敏、保留期和 namespace 过滤。';
COMMENT ON COLUMN agent_memory_store_entry.content_search_vector IS
    'PostgreSQL 全文检索向量，用于没有向量或向量降级时的关键词召回。中文分词后续可替换为更专业扩展。';
COMMENT ON COLUMN agent_memory_store_entry.expires_at IS
    '记忆过期时间。所有检索查询必须排除过期记录，遗忘任务也应以该字段为清理依据。';

CREATE INDEX IF NOT EXISTS idx_agent_memory_store_project_lookup
    ON agent_memory_store_entry (tenant_id, project_id, memory_namespace, memory_type, scope, expires_at, materialized_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_store_tenant_lookup
    ON agent_memory_store_entry (tenant_id, memory_namespace, memory_type, scope, expires_at, materialized_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_store_session_lookup
    ON agent_memory_store_entry (tenant_id, project_id, session_id, memory_namespace, memory_type, expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_memory_store_expiry
    ON agent_memory_store_entry (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_memory_store_fts
    ON agent_memory_store_entry USING GIN (content_search_vector);
CREATE INDEX IF NOT EXISTS idx_agent_memory_store_tags_gin
    ON agent_memory_store_entry USING GIN (tags_json jsonb_path_ops);

CREATE TABLE IF NOT EXISTS agent_memory_embedding_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    embedding_id VARCHAR(160) NOT NULL,
    memory_id VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64),
    project_id VARCHAR(64),
    session_id VARCHAR(128),
    workspace_key VARCHAR(255) NOT NULL,
    memory_namespace VARCHAR(255) NOT NULL,
    memory_type VARCHAR(32) NOT NULL,
    scope VARCHAR(32) NOT NULL,
    embedding_model VARCHAR(128) NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    embedding VECTOR,
    content_fingerprint VARCHAR(128) NOT NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    index_status VARCHAR(32) NOT NULL DEFAULT 'ready',
    indexed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_memory_embedding_id UNIQUE (embedding_id),
    CONSTRAINT uk_agent_memory_embedding_memory_model UNIQUE (memory_id, embedding_model, content_fingerprint),
    CONSTRAINT ck_agent_memory_embedding_dimension CHECK (embedding_dimension > 0),
    CONSTRAINT ck_agent_memory_embedding_status CHECK (
        index_status IN ('pending', 'ready', 'stale', 'failed', 'deleted')
    )
);

COMMENT ON TABLE agent_memory_embedding_index IS
    'pgvector 语义索引表。它保存长期记忆的向量表示和 metadata filter 字段，用于逐步替代 Chroma 作为目标向量底座。';
COMMENT ON COLUMN agent_memory_embedding_index.embedding IS
    'pgvector 向量。这里不固定维度，避免把项目锁死到某一代 embedding 模型；生产可按当前模型维度建立专用 HNSW/IVFFLAT 索引或分区。';
COMMENT ON COLUMN agent_memory_embedding_index.embedding_model IS
    '生成该向量的 embedding 模型或 provider 标识。模型升级时允许同一 memory_id 并存不同模型版本的索引。';
COMMENT ON COLUMN agent_memory_embedding_index.content_fingerprint IS
    '记忆正文低敏摘要的指纹。正文变更后新指纹会触发重建向量，旧索引可标记 stale。';

CREATE INDEX IF NOT EXISTS idx_agent_memory_embedding_filter
    ON agent_memory_embedding_index (tenant_id, project_id, memory_namespace, memory_type, scope, index_status);
CREATE INDEX IF NOT EXISTS idx_agent_memory_embedding_model
    ON agent_memory_embedding_index (embedding_model, embedding_dimension, index_status);
CREATE INDEX IF NOT EXISTS idx_agent_memory_embedding_metadata_gin
    ON agent_memory_embedding_index USING GIN (metadata_json jsonb_path_ops);

CREATE TABLE IF NOT EXISTS agent_memory_materialization_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id VARCHAR(128) NOT NULL,
    candidate_id VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    project_id VARCHAR(64) NOT NULL,
    workspace_key VARCHAR(255) NOT NULL,
    memory_namespace VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 1,
    worker_id VARCHAR(128),
    memory_id VARCHAR(128),
    namespace_json JSONB,
    outcome VARCHAR(64),
    message VARCHAR(1024),
    error_message VARCHAR(1024),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_memory_materialization_receipt_id UNIQUE (receipt_id),
    CONSTRAINT uk_agent_memory_materialization_candidate UNIQUE (candidate_id),
    CONSTRAINT ck_agent_memory_materialization_receipt_status CHECK (
        status IN ('started', 'succeeded', 'failed')
    ),
    CONSTRAINT ck_agent_memory_materialization_receipt_attempt CHECK (attempt_count > 0)
);

COMMENT ON TABLE agent_memory_materialization_receipt IS
    '长期记忆物化 receipt 表。它证明 approved 候选是否已经被 worker 尝试落成正式记忆，避免候选状态同时承担审批语义和执行语义。';
COMMENT ON COLUMN agent_memory_materialization_receipt.error_message IS
    '低敏失败摘要，只允许记录异常类型和短错误说明，禁止保存 prompt、SQL、样本数据或完整异常堆栈。';

CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_scope_status
    ON agent_memory_materialization_receipt (tenant_id, project_id, status, update_time DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_workspace
    ON agent_memory_materialization_receipt (tenant_id, project_id, workspace_key, status, update_time DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_memory
    ON agent_memory_materialization_receipt (memory_id);

CREATE TABLE IF NOT EXISTS agent_memory_materialization_lease (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_id VARCHAR(160) NOT NULL,
    candidate_id VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    project_id VARCHAR(64) NOT NULL,
    workspace_key VARCHAR(255) NOT NULL,
    memory_namespace VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 1,
    worker_id VARCHAR(128) NOT NULL,
    lease_token VARCHAR(128) NOT NULL,
    leased_until TIMESTAMPTZ NOT NULL,
    next_retry_at TIMESTAMPTZ,
    memory_id VARCHAR(128),
    outcome VARCHAR(64),
    message VARCHAR(1024),
    error_message VARCHAR(1024),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_memory_materialization_lease_id UNIQUE (lease_id),
    CONSTRAINT uk_agent_memory_materialization_lease_candidate UNIQUE (candidate_id),
    CONSTRAINT ck_agent_memory_materialization_lease_status CHECK (
        status IN ('leased', 'succeeded', 'failed', 'dead_letter')
    ),
    CONSTRAINT ck_agent_memory_materialization_lease_attempt CHECK (attempt_count > 0)
);

COMMENT ON TABLE agent_memory_materialization_lease IS
    '长期记忆物化 worker 租约表。多实例 worker 通过租约和 fencing token 避免重复处理同一候选。';
COMMENT ON COLUMN agent_memory_materialization_lease.lease_token IS
    '内部 fencing token。只用于条件更新，禁止输出到诊断接口、日志、前端或审计 payload。';
COMMENT ON COLUMN agent_memory_materialization_lease.next_retry_at IS
    '失败退避结束时间。未到时间前 runner 不应重新领取，dead_letter 状态下通常为空并等待人工补偿。';

CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_lease_claim
    ON agent_memory_materialization_lease (status, leased_until, update_time);
CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_lease_retry
    ON agent_memory_materialization_lease (status, next_retry_at, leased_until, update_time);
CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_lease_scope
    ON agent_memory_materialization_lease (tenant_id, project_id, status, update_time DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_lease_workspace
    ON agent_memory_materialization_lease (tenant_id, project_id, workspace_key, status, update_time DESC);

CREATE TABLE IF NOT EXISTS agent_memory_materialization_audit_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(96) NOT NULL,
    event_purpose VARCHAR(128) NOT NULL,
    aggregate_id VARCHAR(160) NOT NULL,
    tenant_id VARCHAR(64),
    project_id VARCHAR(64),
    actor_id VARCHAR(64),
    request_id VARCHAR(128),
    run_id VARCHAR(128),
    session_id VARCHAR(128),
    severity VARCHAR(32) NOT NULL,
    action VARCHAR(64),
    dry_run BOOLEAN NOT NULL DEFAULT FALSE,
    payload_json JSONB NOT NULL,
    delivery_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_delivery_attempt_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_memory_materialization_audit_outbox_id UNIQUE (outbox_id),
    CONSTRAINT ck_agent_memory_materialization_audit_delivery CHECK (
        delivery_status IN ('pending', 'dispatched', 'failed', 'blocked')
    ),
    CONSTRAINT ck_agent_memory_materialization_audit_attempt CHECK (attempt_count >= 0)
);

COMMENT ON TABLE agent_memory_materialization_audit_outbox IS
    '长期记忆物化审计 outbox。它记录 worker 批次或管理员补偿动作，后续可投递到 Java 审计中心、Kafka、对象归档或 SIEM。';
COMMENT ON COLUMN agent_memory_materialization_audit_outbox.payload_json IS
    '低敏审计 payload。只允许保存计数、状态、candidateId、namespace、attemptCount 等控制面事实，禁止保存正文、SQL、样本、原始输出或 lease token。';

CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_audit_dispatch
    ON agent_memory_materialization_audit_outbox (delivery_status, next_delivery_attempt_at, update_time);
CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_audit_scope
    ON agent_memory_materialization_audit_outbox (tenant_id, project_id, event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_audit_actor
    ON agent_memory_materialization_audit_outbox (tenant_id, actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_materialization_audit_aggregate
    ON agent_memory_materialization_audit_outbox (aggregate_id, created_at DESC);

CREATE TABLE IF NOT EXISTS user_profile_fact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_fact_id VARCHAR(160) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    actor_id VARCHAR(64) NOT NULL,
    project_id VARCHAR(64),
    workspace_key VARCHAR(255),
    fact_type VARCHAR(64) NOT NULL,
    fact_key VARCHAR(128) NOT NULL,
    fact_value_summary TEXT NOT NULL,
    confidence_score NUMERIC(10,4) NOT NULL DEFAULT 0.5000,
    source VARCHAR(128) NOT NULL,
    source_run_id VARCHAR(128),
    source_memory_id VARCHAR(128),
    sensitivity_level VARCHAR(32) NOT NULL DEFAULT 'internal',
    retention_days INTEGER NOT NULL DEFAULT 180,
    expires_at TIMESTAMPTZ NOT NULL,
    attributes_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_profile_fact_id UNIQUE (profile_fact_id),
    CONSTRAINT uk_user_profile_fact_key UNIQUE (tenant_id, actor_id, project_id, workspace_key, fact_type, fact_key),
    CONSTRAINT ck_user_profile_fact_confidence CHECK (
        confidence_score >= 0 AND confidence_score <= 1
    ),
    CONSTRAINT ck_user_profile_fact_retention CHECK (retention_days > 0)
);

COMMENT ON TABLE user_profile_fact IS
    '用户画像事实表。它保存可解释、可过期、可审计的低敏用户偏好和工作方式事实，为 Codex/Claude Code 类 Agent 的个性化行为提供长期状态。';
COMMENT ON COLUMN user_profile_fact.fact_value_summary IS
    '低敏画像摘要，例如偏好的输出格式、常用工作区或审批习惯。禁止保存密码、密钥、完整 prompt 或敏感业务样本。';
COMMENT ON COLUMN user_profile_fact.confidence_score IS
    '画像置信度。来自单次对话的事实应较低，多次稳定观察或人工确认后可提高。';

CREATE INDEX IF NOT EXISTS idx_user_profile_fact_actor_lookup
    ON user_profile_fact (tenant_id, actor_id, project_id, workspace_key, fact_type, expires_at);
CREATE INDEX IF NOT EXISTS idx_user_profile_fact_source
    ON user_profile_fact (source_memory_id, source_run_id);
CREATE INDEX IF NOT EXISTS idx_user_profile_fact_attributes_gin
    ON user_profile_fact USING GIN (attributes_json jsonb_path_ops);

CREATE TABLE IF NOT EXISTS langgraph_thread_checkpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkpoint_id VARCHAR(160) NOT NULL,
    thread_id VARCHAR(160) NOT NULL,
    parent_checkpoint_id VARCHAR(160),
    tenant_id VARCHAR(64),
    project_id VARCHAR(64),
    actor_id VARCHAR(64),
    workspace_key VARCHAR(255),
    run_id VARCHAR(128),
    session_id VARCHAR(128),
    graph_name VARCHAR(128) NOT NULL,
    graph_version VARCHAR(64) NOT NULL,
    node_name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    checkpoint_version INTEGER NOT NULL DEFAULT 1,
    state_json JSONB NOT NULL,
    next_nodes_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    resume_requirements_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    low_sensitive_summary VARCHAR(1024),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_langgraph_thread_checkpoint_id UNIQUE (checkpoint_id),
    CONSTRAINT ck_langgraph_thread_checkpoint_status CHECK (
        status IN ('running', 'waiting_human', 'waiting_tool', 'paused', 'completed', 'failed', 'cancelled')
    ),
    CONSTRAINT ck_langgraph_thread_checkpoint_version CHECK (checkpoint_version > 0)
);

COMMENT ON TABLE langgraph_thread_checkpoint IS
    'LangGraph durable checkpoint 表。它让 Agent 图执行具备可恢复、可观测、可暂停和可分支的状态机能力，而不是只在进程内保存固定流水线状态。';
COMMENT ON COLUMN langgraph_thread_checkpoint.state_json IS
    '低敏图状态快照。只能保存恢复执行所需的状态、指针和摘要，禁止保存完整 prompt、工具原始输出、密钥或大样本数据。';
COMMENT ON COLUMN langgraph_thread_checkpoint.next_nodes_json IS
    '下一批候选节点。边逻辑可根据该字段恢复分支、循环、人工介入或工具等待状态。';
COMMENT ON COLUMN langgraph_thread_checkpoint.resume_requirements_json IS
    '恢复执行前必须满足的事实条件，例如审批、澄清、预算、outbox ack 或 worker receipt。';

CREATE INDEX IF NOT EXISTS idx_langgraph_thread_checkpoint_thread
    ON langgraph_thread_checkpoint (thread_id, checkpoint_version DESC);
CREATE INDEX IF NOT EXISTS idx_langgraph_thread_checkpoint_run
    ON langgraph_thread_checkpoint (tenant_id, project_id, run_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_langgraph_thread_checkpoint_status
    ON langgraph_thread_checkpoint (status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_langgraph_thread_checkpoint_state_gin
    ON langgraph_thread_checkpoint USING GIN (state_json jsonb_path_ops);

CREATE TABLE IF NOT EXISTS langgraph_checkpoint_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(160) NOT NULL,
    checkpoint_id VARCHAR(160) NOT NULL,
    thread_id VARCHAR(160) NOT NULL,
    tenant_id VARCHAR(64),
    project_id VARCHAR(64),
    run_id VARCHAR(128),
    event_type VARCHAR(96) NOT NULL,
    node_name VARCHAR(128),
    edge_name VARCHAR(128),
    sequence_number BIGINT NOT NULL,
    attributes_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_langgraph_checkpoint_event_id UNIQUE (event_id),
    CONSTRAINT uk_langgraph_checkpoint_event_sequence UNIQUE (thread_id, sequence_number),
    CONSTRAINT ck_langgraph_checkpoint_event_sequence CHECK (sequence_number > 0)
);

COMMENT ON TABLE langgraph_checkpoint_event IS
    'LangGraph checkpoint 事件表。它记录节点进入、边选择、暂停、恢复和失败等低敏事件，支撑审计回放和可观测图执行。';
COMMENT ON COLUMN langgraph_checkpoint_event.edge_name IS
    '被选择的边名称。边把 Agent 从固定流水线升级为可分支、可循环、可控制的状态机，因此必须可观测。';

CREATE INDEX IF NOT EXISTS idx_langgraph_checkpoint_event_checkpoint
    ON langgraph_checkpoint_event (checkpoint_id, sequence_number);
CREATE INDEX IF NOT EXISTS idx_langgraph_checkpoint_event_run
    ON langgraph_checkpoint_event (tenant_id, project_id, run_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_langgraph_checkpoint_event_type
    ON langgraph_checkpoint_event (event_type, created_at DESC);
