-- datasource-management PostgreSQL schema 基线。
--
-- 迁移原则：
-- 1. 本脚本只建立 datasource-management 当前 Java 实体、Mapper 和服务逻辑真实使用的控制面表。
--    data_sync_* 表属于独立 data-sync 微服务，不能因为历史 MySQL 初始化脚本混放而继续塞入本 schema。
-- 2. 平台自身业务事实库切换到 PostgreSQL；外部 MySQL/PostgreSQL/SQL Server 等连接器驱动仍由应用层保留，
--    因为 datasource-management 的产品职责正是管理和探测客户侧异构数据源。
-- 3. 主键使用 GENERATED BY DEFAULT AS IDENTITY，既支持 MyBatis-Plus 自动回填，也允许后续存量迁移显式保留旧 ID。
-- 4. MySQL TINYINT(1) 转换为 PostgreSQL BOOLEAN，避免把开关语义继续伪装成 0/1 整数。
-- 5. LocalDateTime 对应 TIMESTAMP WITHOUT TIME ZONE。应用层仍应统一按 UTC 或平台约定时区解释，避免迁移期隐式换算。
-- 6. JSON 配置、审计 payload、错误摘要等字段本批仍保持 TEXT，因为 Java 实体当前是 String；未来升级 JSONB 必须同步 TypeHandler。
-- 7. 本脚本不添加外键级联。同步任务、执行、告警、审批、审计都有历史证据保留需求，过早级联删除会改变线上行为。
-- 8. DDL 只负责新安装空库基线；已有 MySQL 存量数据仍需要独立导出、导入、对账、sequence 校正和只读观察流程。

SET search_path TO datasource_management, public;

CREATE TABLE datasource_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL DEFAULT 1,
    workspace_id BIGINT,
    name VARCHAR(128) NOT NULL,
    type VARCHAR(32) NOT NULL,
    jdbc_url VARCHAR(512) NOT NULL,
    username VARCHAR(128) NOT NULL,
    password VARCHAR(256) NOT NULL,
    driver_class_name VARCHAR(256) NOT NULL,
    description VARCHAR(512),
    status VARCHAR(32) NOT NULL,
    last_test_status VARCHAR(32) DEFAULT 'UNKNOWN',
    last_test_message VARCHAR(512),
    last_test_time TIMESTAMP WITHOUT TIME ZONE,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_datasource_tenant_project_name UNIQUE (tenant_id, project_id, name),
    CONSTRAINT ck_datasource_scope_positive CHECK (tenant_id > 0 AND project_id > 0)
);

COMMENT ON TABLE datasource_config IS '数据源配置主表，保存平台登记的外部数据源连接、生命周期、最近一次连通性探测结果和项目/租户边界';
COMMENT ON COLUMN datasource_config.id IS '数据源主键，PostgreSQL identity 自动生成；存量迁移时允许显式写入旧 MySQL ID';
COMMENT ON COLUMN datasource_config.tenant_id IS '租户隔离边界，用于多租户权限、配额、审计和成本统计';
COMMENT ON COLUMN datasource_config.project_id IS '项目隔离边界，用于项目级数据源列表、项目权限和治理看板';
COMMENT ON COLUMN datasource_config.workspace_id IS '可选工作空间边界，用于区分研发、测试、生产或临时分析空间';
COMMENT ON COLUMN datasource_config.name IS '租户和项目内唯一的数据源名称，面向用户展示和任务配置引用';
COMMENT ON COLUMN datasource_config.type IS '外部数据源类型，例如 MYSQL、POSTGRESQL、SQLSERVER；它描述客户源端，不描述平台自身数据库';
COMMENT ON COLUMN datasource_config.jdbc_url IS '外部数据源 JDBC 地址。该字段包含敏感连接位置信息，日志和迁移脚本必须脱敏处理';
COMMENT ON COLUMN datasource_config.username IS '外部数据源连接用户名；生产环境后续应升级为密钥引用或加密存储';
COMMENT ON COLUMN datasource_config.password IS '外部数据源连接凭据；当前沿用历史模型，后续应迁入密钥中心或字段级加密';
COMMENT ON COLUMN datasource_config.driver_class_name IS 'JDBC 驱动类名，用于连接测试、元数据发现和同步执行器按需装载驱动';
COMMENT ON COLUMN datasource_config.status IS '数据源生命周期状态，例如 ACTIVE、INACTIVE、DELETED';
COMMENT ON COLUMN datasource_config.last_test_status IS '最近一次连接测试状态，例如 SUCCESS、FAILED、UNKNOWN';
COMMENT ON COLUMN datasource_config.last_test_message IS '最近一次连接测试摘要，禁止写入完整连接串、密码或驱动堆栈中的敏感片段';
COMMENT ON COLUMN datasource_config.last_test_time IS '最近一次连接测试时间';
COMMENT ON COLUMN datasource_config.create_time IS '记录创建时间，由 MyBatis-Plus MetaObjectHandler 自动填充';
COMMENT ON COLUMN datasource_config.update_time IS '记录最后更新时间，由 MyBatis-Plus MetaObjectHandler 自动填充';
CREATE INDEX idx_datasource_tenant_project ON datasource_config (tenant_id, project_id, status);
CREATE INDEX idx_datasource_workspace ON datasource_config (tenant_id, workspace_id, status);
CREATE INDEX idx_datasource_type ON datasource_config (type);
CREATE INDEX idx_datasource_status ON datasource_config (status);

CREATE TABLE datasource_readonly_sql_execution_audit (
    datasource_tenant_id BIGINT,
    datasource_project_id BIGINT,
    datasource_workspace_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datasource_id BIGINT NOT NULL,
    datasource_name VARCHAR(128) NOT NULL,
    datasource_type VARCHAR(32) NOT NULL,
    purpose VARCHAR(128),
    actor_tenant_id BIGINT,
    actor_id BIGINT,
    actor_role VARCHAR(64) NOT NULL,
    actor_type VARCHAR(64),
    source_service VARCHAR(128),
    trace_id VARCHAR(128),
    sql_fingerprint VARCHAR(64),
    sql_preview VARCHAR(1000),
    requested_max_rows INTEGER,
    applied_max_rows INTEGER,
    requested_query_timeout_seconds INTEGER,
    applied_query_timeout_seconds INTEGER,
    returned_row_count INTEGER,
    column_count INTEGER,
    duration_ms BIGINT,
    execution_status VARCHAR(32) NOT NULL,
    failure_message VARCHAR(1000),
    executed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_datasource_readonly_limits_non_negative CHECK (
        (requested_max_rows IS NULL OR requested_max_rows >= 0)
        AND (applied_max_rows IS NULL OR applied_max_rows >= 0)
        AND (requested_query_timeout_seconds IS NULL OR requested_query_timeout_seconds >= 0)
        AND (applied_query_timeout_seconds IS NULL OR applied_query_timeout_seconds >= 0)
        AND (returned_row_count IS NULL OR returned_row_count >= 0)
        AND (column_count IS NULL OR column_count >= 0)
        AND (duration_ms IS NULL OR duration_ms >= 0)
    )
);

COMMENT ON TABLE datasource_readonly_sql_execution_audit IS '受控只读 SQL 执行审计表，记录谁在什么目的下读取了哪个数据源以及平台施加的行数、超时和脱敏约束';
COMMENT ON COLUMN datasource_readonly_sql_execution_audit.datasource_tenant_id IS '被访问数据源所属租户快照，与 actor_tenant_id 分开保存以支持代操作和服务账号审计';
COMMENT ON COLUMN datasource_readonly_sql_execution_audit.datasource_project_id IS '被访问数据源所属项目快照，用于项目级 SQL 访问审计报表';
COMMENT ON COLUMN datasource_readonly_sql_execution_audit.datasource_workspace_id IS '被访问数据源所属工作空间快照，用于研发、测试、生产空间维度的审计过滤';
COMMENT ON COLUMN datasource_readonly_sql_execution_audit.sql_fingerprint IS 'SQL SHA-256 指纹，用于聚合同类访问，避免保存完整 SQL';
COMMENT ON COLUMN datasource_readonly_sql_execution_audit.sql_preview IS '脱敏和截断后的 SQL 预览，只用于排障，禁止存入完整敏感字面量';
COMMENT ON COLUMN datasource_readonly_sql_execution_audit.execution_status IS '执行状态，例如 SUCCESS、FAILED';
COMMENT ON COLUMN datasource_readonly_sql_execution_audit.failure_message IS '失败摘要，禁止写入完整堆栈、连接串、凭据或原始业务样本';
CREATE INDEX idx_datasource_readonly_audit_datasource_time ON datasource_readonly_sql_execution_audit (datasource_id, executed_at);
CREATE INDEX idx_datasource_readonly_audit_purpose_time ON datasource_readonly_sql_execution_audit (purpose, executed_at);
CREATE INDEX idx_datasource_readonly_audit_tenant_time ON datasource_readonly_sql_execution_audit (actor_tenant_id, executed_at);
CREATE INDEX idx_datasource_readonly_audit_actor_time ON datasource_readonly_sql_execution_audit (actor_role, executed_at);
CREATE INDEX idx_datasource_readonly_audit_project_time ON datasource_readonly_sql_execution_audit (datasource_tenant_id, datasource_project_id, executed_at);
CREATE INDEX idx_datasource_readonly_audit_workspace_time ON datasource_readonly_sql_execution_audit (datasource_tenant_id, datasource_workspace_id, executed_at);
CREATE INDEX idx_datasource_readonly_audit_trace_id ON datasource_readonly_sql_execution_audit (trace_id);
CREATE INDEX idx_datasource_readonly_audit_status_time ON datasource_readonly_sql_execution_audit (execution_status, executed_at);
CREATE INDEX idx_datasource_readonly_audit_sql_fingerprint ON datasource_readonly_sql_execution_audit (sql_fingerprint);

CREATE TABLE sync_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL DEFAULT 1,
    workspace_id BIGINT,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    source_datasource_id BIGINT NOT NULL,
    source_schema_name VARCHAR(128),
    source_object_name VARCHAR(128) NOT NULL,
    target_datasource_id BIGINT NOT NULL,
    target_schema_name VARCHAR(128),
    target_object_name VARCHAR(128) NOT NULL,
    sync_mode VARCHAR(64) NOT NULL,
    write_strategy VARCHAR(64) NOT NULL DEFAULT 'APPEND',
    primary_key_field VARCHAR(128),
    incremental_field VARCHAR(128),
    field_mapping_config TEXT,
    filter_config TEXT,
    partition_config TEXT,
    retry_policy TEXT,
    timeout_policy TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NOT NULL,
    updated_by BIGINT,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_sync_template_tenant_project_name UNIQUE (tenant_id, project_id, name),
    CONSTRAINT ck_sync_template_scope_positive CHECK (tenant_id > 0 AND project_id > 0)
);

COMMENT ON TABLE sync_template IS '数据同步模板表，保存可复用的源端、目标端、同步模式、写入策略、字段映射、过滤、分片、重试和超时定义';
COMMENT ON COLUMN sync_template.source_datasource_id IS '源端数据源 ID，引用 datasource_config 中登记的外部数据源';
COMMENT ON COLUMN sync_template.target_datasource_id IS '目标端数据源 ID，引用 datasource_config 中登记的外部数据源';
COMMENT ON COLUMN sync_template.sync_mode IS '同步模式，例如 FULL、INCREMENTAL_TIME、INCREMENTAL_ID、CDC、BACKFILL';
COMMENT ON COLUMN sync_template.write_strategy IS '目标端写入策略，例如 APPEND、UPSERT、INSERT_IGNORE、REPLACE、OVERWRITE';
COMMENT ON COLUMN sync_template.primary_key_field IS '主键或幂等字段，用于去重、冲突判断、重试和回放';
COMMENT ON COLUMN sync_template.incremental_field IS '增量字段，用于时间水位或 ID 水位推进';
COMMENT ON COLUMN sync_template.field_mapping_config IS '字段映射 JSON 文本，当前按 String 保存，未来可迁移为 JSONB';
COMMENT ON COLUMN sync_template.filter_config IS '过滤条件 JSON 文本，禁止保存凭据或完整敏感样本';
COMMENT ON COLUMN sync_template.partition_config IS '分片或分区配置 JSON 文本，用于未来并行读取、分区回放和补数';
COMMENT ON COLUMN sync_template.retry_policy IS '重试策略 JSON 文本，例如最大次数、退避、可重试异常类别';
COMMENT ON COLUMN sync_template.timeout_policy IS '超时策略 JSON 文本，例如单次执行、批次、连接探测超时';
COMMENT ON COLUMN sync_template.enabled IS '模板是否启用；禁用后不删除历史任务，只阻止新任务继续复用';
CREATE INDEX idx_sync_template_project_mode ON sync_template (tenant_id, project_id, sync_mode, enabled);
CREATE INDEX idx_sync_template_workspace ON sync_template (tenant_id, workspace_id, update_time);
CREATE INDEX idx_sync_template_source ON sync_template (tenant_id, source_datasource_id);
CREATE INDEX idx_sync_template_target ON sync_template (tenant_id, target_datasource_id);
CREATE INDEX idx_sync_template_enabled ON sync_template (tenant_id, enabled);

CREATE TABLE sync_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL DEFAULT 1,
    workspace_id BIGINT,
    template_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    current_state VARCHAR(64) NOT NULL,
    approval_state VARCHAR(64) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    run_mode VARCHAR(64) NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    schedule_config TEXT,
    owner_id BIGINT NOT NULL,
    last_execution_id BIGINT,
    next_run_at TIMESTAMP WITHOUT TIME ZONE,
    queued_at TIMESTAMP WITHOUT TIME ZONE,
    current_executor_id VARCHAR(128),
    dispatch_lease_expire_at TIMESTAMP WITHOUT TIME ZONE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    operator_attention_required BOOLEAN NOT NULL DEFAULT FALSE,
    timeout_seconds INTEGER NOT NULL,
    max_retry_count INTEGER NOT NULL DEFAULT 3,
    retry_count INTEGER NOT NULL DEFAULT 0,
    queue_attempt_count INTEGER NOT NULL DEFAULT 0,
    latest_error_summary VARCHAR(1024),
    incident_note VARCHAR(1024),
    created_by BIGINT NOT NULL,
    updated_by BIGINT,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_sync_task_tenant_project_name UNIQUE (tenant_id, project_id, name),
    CONSTRAINT ck_sync_task_scope_positive CHECK (tenant_id > 0 AND project_id > 0),
    CONSTRAINT ck_sync_task_retry_non_negative CHECK (
        timeout_seconds >= 0 AND max_retry_count >= 0 AND retry_count >= 0 AND queue_attempt_count >= 0
    )
);

COMMENT ON TABLE sync_task IS '数据同步任务表，承载模板实例化后的执行治理对象，包括审批、优先级、队列、租约、重试、人工关注和事故备注';
COMMENT ON COLUMN sync_task.current_state IS '任务主状态，例如 DRAFT、QUEUED、RUNNING、PAUSED、SUCCEEDED、FAILED、CANCELLED';
COMMENT ON COLUMN sync_task.approval_state IS '治理审批状态，不等同于执行状态，用于控制任务是否可进入运行链路';
COMMENT ON COLUMN sync_task.queued_at IS '最近一次入队时间，用于识别队列积压和调度器停滞';
COMMENT ON COLUMN sync_task.dispatch_lease_expire_at IS '任务调度租约过期时间，用于失联恢复和重复认领保护';
COMMENT ON COLUMN sync_task.operator_attention_required IS '是否需要人工关注，面向运维看板和告警系统';
COMMENT ON COLUMN sync_task.queue_attempt_count IS '累计入队次数，不等同于业务重试次数';
CREATE INDEX idx_sync_task_project_state ON sync_task (tenant_id, project_id, current_state);
CREATE INDEX idx_sync_task_workspace_state ON sync_task (tenant_id, workspace_id, current_state);
CREATE INDEX idx_sync_task_state ON sync_task (tenant_id, current_state);
CREATE INDEX idx_sync_task_owner ON sync_task (tenant_id, owner_id);
CREATE INDEX idx_sync_task_approval ON sync_task (tenant_id, approval_state);
CREATE INDEX idx_sync_task_next_run ON sync_task (tenant_id, next_run_at);
CREATE INDEX idx_sync_task_queue ON sync_task (tenant_id, current_state, queued_at);
CREATE INDEX idx_sync_task_executor ON sync_task (current_executor_id, dispatch_lease_expire_at);

CREATE TABLE sync_agent_command_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id VARCHAR(180) NOT NULL,
    command_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    agent_session_id VARCHAR(128),
    agent_run_id VARCHAR(128),
    audit_id VARCHAR(128),
    tool_code VARCHAR(128) NOT NULL,
    tenant_id BIGINT NOT NULL,
    project_id BIGINT,
    workspace_id BIGINT,
    actor_id VARCHAR(128),
    trace_id VARCHAR(128),
    template_id BIGINT,
    sync_template_id BIGINT,
    resolved_template_id BIGINT NOT NULL,
    sync_task_id BIGINT,
    sync_execution_id BIGINT,
    status VARCHAR(32) NOT NULL,
    downstream_state VARCHAR(64) NOT NULL,
    side_effect_started BOOLEAN NOT NULL DEFAULT FALSE,
    side_effect_executed BOOLEAN NOT NULL DEFAULT FALSE,
    duplicate BOOLEAN NOT NULL DEFAULT FALSE,
    message VARCHAR(512),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_sync_agent_command_receipt_id UNIQUE (receipt_id),
    CONSTRAINT uk_sync_agent_command_id UNIQUE (command_id),
    CONSTRAINT uk_sync_agent_command_idempotency UNIQUE (idempotency_key),
    CONSTRAINT ck_sync_agent_command_tenant_positive CHECK (tenant_id > 0)
);

COMMENT ON TABLE sync_agent_command_receipt IS 'datasource-management 侧 Agent 命令接收 receipt 表，用于证明 Agent 命令已被转换为本模块同步任务副作用';
COMMENT ON COLUMN sync_agent_command_receipt.idempotency_key IS '跨服务幂等键，HTTP 超时、Kafka 重放或 dispatcher 重试时必须复用';
COMMENT ON COLUMN sync_agent_command_receipt.resolved_template_id IS 'datasource-management 实际采用的同步模板 ID';
COMMENT ON COLUMN sync_agent_command_receipt.message IS '低敏结果说明，禁止保存 SQL、连接串、凭据、样本数据、prompt、模型输出或工具实参正文';
CREATE INDEX idx_sync_agent_command_scope_time ON sync_agent_command_receipt (tenant_id, project_id, workspace_id, update_time);
CREATE INDEX idx_sync_agent_command_task ON sync_agent_command_receipt (sync_task_id, sync_execution_id);
CREATE INDEX idx_sync_agent_command_run ON sync_agent_command_receipt (agent_run_id, agent_session_id, status);

CREATE TABLE sync_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_task_id BIGINT NOT NULL,
    execution_no BIGINT NOT NULL,
    state VARCHAR(64) NOT NULL,
    started_at TIMESTAMP WITHOUT TIME ZONE,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    checkpoint_ref VARCHAR(256),
    records_read BIGINT DEFAULT 0,
    records_written BIGINT DEFAULT 0,
    failed_record_count BIGINT DEFAULT 0,
    error_summary TEXT,
    triggered_by BIGINT,
    executor_id VARCHAR(128),
    heartbeat_at TIMESTAMP WITHOUT TIME ZONE,
    lease_expire_at TIMESTAMP WITHOUT TIME ZONE,
    trigger_reason VARCHAR(512),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_sync_execution_no_positive CHECK (execution_no > 0),
    CONSTRAINT ck_sync_execution_counts_non_negative CHECK (
        (records_read IS NULL OR records_read >= 0)
        AND (records_written IS NULL OR records_written >= 0)
        AND (failed_record_count IS NULL OR failed_record_count >= 0)
    )
);

COMMENT ON TABLE sync_execution IS '数据同步执行记录表，一次任务运行对应一条独立执行事实，用于历史轨迹、重试分析、SLA 和故障恢复';
COMMENT ON COLUMN sync_execution.checkpoint_ref IS '当前检查点摘要或引用，明细保存在 sync_checkpoint';
COMMENT ON COLUMN sync_execution.error_summary IS '错误摘要，禁止保存完整敏感样本或凭据';
COMMENT ON COLUMN sync_execution.lease_expire_at IS '执行租约到期时间，用于失联恢复';
CREATE INDEX idx_sync_execution_task_no ON sync_execution (sync_task_id, execution_no);
CREATE INDEX idx_sync_execution_state ON sync_execution (sync_task_id, state);
CREATE INDEX idx_sync_execution_started_at ON sync_execution (started_at);
CREATE INDEX idx_sync_execution_executor ON sync_execution (executor_id, lease_expire_at);

CREATE TABLE sync_checkpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL,
    checkpoint_type VARCHAR(64) NOT NULL,
    checkpoint_value TEXT NOT NULL,
    shard_or_partition VARCHAR(128),
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

COMMENT ON TABLE sync_checkpoint IS '数据同步检查点表，用于断点续跑、分片恢复、补数和回放';
COMMENT ON COLUMN sync_checkpoint.checkpoint_value IS '检查点值，使用文本兼容不同模式下的水位表达';
CREATE INDEX idx_sync_checkpoint_execution_partition ON sync_checkpoint (execution_id, shard_or_partition);

CREATE TABLE sync_audit_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    sync_task_id BIGINT,
    execution_id BIGINT,
    action_type VARCHAR(64) NOT NULL,
    actor_id BIGINT NOT NULL,
    actor_role VARCHAR(64) NOT NULL,
    action_payload TEXT,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_sync_audit_tenant_positive CHECK (tenant_id > 0)
);

COMMENT ON TABLE sync_audit_record IS '数据同步审计记录表，保存模板变更、任务操作、审批、执行回调和运维动作证据';
COMMENT ON COLUMN sync_audit_record.action_payload IS '动作载荷摘要或 JSON 文本，禁止保存凭据、完整 SQL、原始样本和模型输出正文';
CREATE INDEX idx_sync_audit_tenant_action ON sync_audit_record (tenant_id, action_type);
CREATE INDEX idx_sync_audit_task_time ON sync_audit_record (sync_task_id, create_time);
CREATE INDEX idx_sync_audit_execution_time ON sync_audit_record (execution_id, create_time);

CREATE TABLE sync_permission_policy_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    actor_role VARCHAR(64) NOT NULL,
    binding_type VARCHAR(64) NOT NULL,
    binding_value VARCHAR(128) NOT NULL,
    binding_source VARCHAR(64) NOT NULL DEFAULT 'MANUAL',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL DEFAULT 100,
    note VARCHAR(512),
    created_by BIGINT NOT NULL,
    updated_by BIGINT,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_sync_permission_binding_scope_role_type_value UNIQUE (tenant_id, actor_role, binding_type, binding_value),
    CONSTRAINT ck_sync_permission_binding_tenant_non_negative CHECK (tenant_id >= 0),
    CONSTRAINT ck_sync_permission_binding_priority_non_negative CHECK (priority >= 0)
);

COMMENT ON TABLE sync_permission_policy_binding IS '同步权限策略绑定表，表达不同角色在同步控制面可见菜单、可访问路由和默认数据范围';
CREATE INDEX idx_sync_permission_binding_scope_role_type ON sync_permission_policy_binding (tenant_id, actor_role, binding_type, enabled);
CREATE INDEX idx_sync_permission_binding_priority ON sync_permission_policy_binding (binding_type, priority, update_time);

CREATE TABLE sync_permission_policy_change_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_tenant_id BIGINT NOT NULL DEFAULT 0,
    requester_id BIGINT NOT NULL,
    requester_role VARCHAR(64) NOT NULL,
    requester_tenant_id BIGINT,
    target_role VARCHAR(64) NOT NULL,
    binding_type VARCHAR(64) NOT NULL,
    binding_values_json TEXT NOT NULL,
    requested_priority INTEGER NOT NULL DEFAULT 100,
    requested_binding_source VARCHAR(64) NOT NULL DEFAULT 'MANUAL',
    request_reason VARCHAR(1000) NOT NULL,
    required_approver_roles_json TEXT,
    request_status VARCHAR(64) NOT NULL,
    approver_id BIGINT,
    approver_role VARCHAR(64),
    approval_mode VARCHAR(64),
    delegated_from_approver_id BIGINT,
    delegated_from_approver_role VARCHAR(64),
    approval_comment VARCHAR(1000),
    approved_at TIMESTAMP WITHOUT TIME ZONE,
    executed_at TIMESTAMP WITHOUT TIME ZONE,
    execution_summary VARCHAR(1000),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_sync_permission_change_tenant_non_negative CHECK (target_tenant_id >= 0),
    CONSTRAINT ck_sync_permission_change_priority_non_negative CHECK (requested_priority >= 0)
);

COMMENT ON TABLE sync_permission_policy_change_request IS '同步权限策略变更申请表，用于把菜单、路由、数据范围变更纳入审批、委托、执行和审计闭环';
COMMENT ON COLUMN sync_permission_policy_change_request.binding_values_json IS '申请写入的绑定值列表 JSON 文本';
COMMENT ON COLUMN sync_permission_policy_change_request.required_approver_roles_json IS '提交时固化的审批角色快照 JSON 文本';
CREATE INDEX idx_sync_permission_change_scope_status ON sync_permission_policy_change_request (target_tenant_id, request_status, create_time);
CREATE INDEX idx_sync_permission_change_role_type ON sync_permission_policy_change_request (target_role, binding_type, create_time);

CREATE TABLE sync_permission_approval_delegate_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_tenant_id BIGINT NOT NULL DEFAULT 0,
    delegator_id BIGINT NOT NULL,
    delegator_role VARCHAR(64) NOT NULL,
    delegate_id BIGINT NOT NULL,
    delegate_role VARCHAR(64) NOT NULL,
    effective_from TIMESTAMP WITHOUT TIME ZONE,
    effective_to TIMESTAMP WITHOUT TIME ZONE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    delegate_reason VARCHAR(1000) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_by BIGINT,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_sync_permission_delegate_tenant_non_negative CHECK (target_tenant_id >= 0)
);

COMMENT ON TABLE sync_permission_approval_delegate_rule IS '同步权限审批委托规则表，用于请假、值班轮转和组织调整时的代审批治理';
CREATE INDEX idx_sync_permission_delegate_scope_delegate ON sync_permission_approval_delegate_rule (target_tenant_id, delegate_id, delegate_role, enabled);
CREATE INDEX idx_sync_permission_delegate_scope_delegator ON sync_permission_approval_delegate_rule (target_tenant_id, delegator_id, delegator_role, enabled);
CREATE INDEX idx_sync_permission_delegate_effective_window ON sync_permission_approval_delegate_rule (effective_from, effective_to, update_time);

CREATE TABLE sync_governance_alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    sync_task_id BIGINT,
    alert_type VARCHAR(64) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    alert_status VARCHAR(32) NOT NULL,
    delivery_status VARCHAR(32) NOT NULL,
    delivery_channel VARCHAR(32) NOT NULL,
    alert_key VARCHAR(128) NOT NULL,
    summary VARCHAR(512) NOT NULL,
    detail TEXT,
    source_resource VARCHAR(64),
    triggered_by_action VARCHAR(64),
    first_occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    occurrence_count INTEGER NOT NULL DEFAULT 1,
    acknowledged_by BIGINT,
    acknowledged_at TIMESTAMP WITHOUT TIME ZONE,
    resolved_by BIGINT,
    resolved_at TIMESTAMP WITHOUT TIME ZONE,
    last_delivery_at TIMESTAMP WITHOUT TIME ZONE,
    next_delivery_attempt_at TIMESTAMP WITHOUT TIME ZONE,
    delivery_attempt_count INTEGER NOT NULL DEFAULT 0,
    last_delivery_error VARCHAR(1000),
    dead_lettered_at TIMESTAMP WITHOUT TIME ZONE,
    dead_letter_reason VARCHAR(1000),
    dispatch_lease_owner VARCHAR(128),
    dispatch_lease_expire_at TIMESTAMP WITHOUT TIME ZONE,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_sync_governance_alert_key_open UNIQUE (alert_key, alert_status),
    CONSTRAINT ck_sync_alert_counts_non_negative CHECK (occurrence_count > 0 AND delivery_attempt_count >= 0)
);

COMMENT ON TABLE sync_governance_alert IS '同步治理告警表，保存队列积压、租约失联、投递失败、人工介入和死信等可运营风险';
COMMENT ON COLUMN sync_governance_alert.alert_key IS '告警去重键，用于短时间窗口内折叠同类风险';
COMMENT ON COLUMN sync_governance_alert.dispatch_lease_expire_at IS '当前 outbox 投递租约过期时间';
CREATE INDEX idx_sync_alert_tenant_status_time ON sync_governance_alert (tenant_id, alert_status, last_occurred_at);
CREATE INDEX idx_sync_alert_task_status_time ON sync_governance_alert (sync_task_id, alert_status, last_occurred_at);
CREATE INDEX idx_sync_alert_delivery_status ON sync_governance_alert (delivery_status, last_occurred_at);
CREATE INDEX idx_sync_alert_retry_time ON sync_governance_alert (delivery_status, next_delivery_attempt_at);
CREATE INDEX idx_sync_alert_dispatch_lease ON sync_governance_alert (dispatch_lease_expire_at, delivery_status, next_delivery_attempt_at);

CREATE TABLE sync_alert_delivery_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    alert_id BIGINT NOT NULL,
    sync_task_id BIGINT,
    attempt_no INTEGER NOT NULL,
    channel VARCHAR(32) NOT NULL,
    delivery_status VARCHAR(32) NOT NULL,
    target_endpoint VARCHAR(256),
    manual_dispatch BOOLEAN NOT NULL DEFAULT FALSE,
    operator_id BIGINT,
    operator_role VARCHAR(64),
    response_summary VARCHAR(1000),
    error_summary VARCHAR(1000),
    started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_sync_alert_delivery_attempt_positive CHECK (attempt_no > 0)
);

COMMENT ON TABLE sync_alert_delivery_record IS '同步治理告警投递记录表，保存每次 webhook、飞书、企业微信或内部日志投递尝试的低敏结果';
COMMENT ON COLUMN sync_alert_delivery_record.target_endpoint IS '目标地址摘要或内部通道标识，生产环境不得保存完整带 token 的 webhook URL';
COMMENT ON COLUMN sync_alert_delivery_record.response_summary IS '通道返回摘要，禁止保存敏感响应正文';
CREATE INDEX idx_sync_alert_delivery_alert_attempt ON sync_alert_delivery_record (alert_id, attempt_no);
CREATE INDEX idx_sync_alert_delivery_tenant_time ON sync_alert_delivery_record (tenant_id, create_time);
CREATE INDEX idx_sync_alert_delivery_channel_status ON sync_alert_delivery_record (channel, delivery_status, create_time);

CREATE TABLE sync_permission_governance_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    change_request_id BIGINT NOT NULL,
    notification_type VARCHAR(64) NOT NULL,
    recipient_actor_id BIGINT,
    recipient_actor_role VARCHAR(64),
    notification_channel VARCHAR(32) NOT NULL,
    notification_status VARCHAR(32) NOT NULL,
    summary VARCHAR(512) NOT NULL,
    detail VARCHAR(2000),
    next_dispatch_at TIMESTAMP WITHOUT TIME ZONE,
    dispatch_attempt_count INTEGER NOT NULL DEFAULT 0,
    dispatched_at TIMESTAMP WITHOUT TIME ZONE,
    last_dispatch_error VARCHAR(1000),
    read_by BIGINT,
    read_at TIMESTAMP WITHOUT TIME ZONE,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_sync_permission_notification_tenant_non_negative CHECK (tenant_id >= 0),
    CONSTRAINT ck_sync_permission_notification_attempt_non_negative CHECK (dispatch_attempt_count >= 0)
);

COMMENT ON TABLE sync_permission_governance_notification IS '同步权限治理通知表，保存审批待办、提醒、升级、审批通过或驳回等通知事实';
COMMENT ON COLUMN sync_permission_governance_notification.detail IS '通知详情，禁止保存凭据、完整 SQL、原始样本或模型输出正文';
CREATE INDEX idx_sync_permission_notification_scope_role ON sync_permission_governance_notification (tenant_id, recipient_actor_role, notification_status, create_time);
CREATE INDEX idx_sync_permission_notification_scope_actor ON sync_permission_governance_notification (tenant_id, recipient_actor_id, notification_status, create_time);
CREATE INDEX idx_sync_permission_notification_change_request ON sync_permission_governance_notification (change_request_id, notification_type, create_time);
