-- datasource-management 数据源实例级授权账本。
--
-- 设计目的：
-- 1. datasource_config 只描述“某条外部数据源连接是什么、属于哪个租户/项目、当前是否可用”；
--    它不应该混入“这条连接授权给谁”的多值关系，否则一条数据源被授权给多个用户时会把主表撑成不可维护的宽表。
-- 2. permission-admin 的路由策略负责判断“某个角色能不能访问某个 API”，但数据源授权还需要判断
--    “某个具体数据源实例能不能被某个用户/角色/服务账号使用”。因此这里建立资源实例级 ACL 账本。
-- 3. 授权不做物理删除，而是通过 ACTIVE/REVOKED 保留生命周期事实，方便审计、误授权追责和后续授权恢复。
-- 4. 当前表不添加外键级联删除，因为数据源、同步任务、质量扫描和审计记录都需要保留历史证据；
--    数据源逻辑删除后，服务层会阻止继续新增授权。

SET search_path TO datasource_management, public;

CREATE TABLE datasource_authorization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datasource_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    workspace_id BIGINT,
    subject_type VARCHAR(32) NOT NULL,
    subject_id VARCHAR(128) NOT NULL,
    subject_name VARCHAR(128),
    subject_role VARCHAR(64),
    authorized_actions VARCHAR(128) NOT NULL,
    grant_source VARCHAR(64) NOT NULL DEFAULT 'UI_MANUAL',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    grant_reason VARCHAR(512),
    expire_time TIMESTAMP WITHOUT TIME ZONE,
    granted_by_actor_id VARCHAR(128),
    granted_by_actor_role VARCHAR(64),
    granted_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked_by_actor_id VARCHAR(128),
    revoked_by_actor_role VARCHAR(64),
    revoke_reason VARCHAR(512),
    revoked_time TIMESTAMP WITHOUT TIME ZONE,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_datasource_authorization_subject_type
        CHECK (subject_type IN ('USER', 'ROLE', 'SERVICE_ACCOUNT')),
    CONSTRAINT ck_datasource_authorization_status
        CHECK (status IN ('ACTIVE', 'REVOKED')),
    CONSTRAINT ck_datasource_authorization_actions
        CHECK (authorized_actions <> ''),
    CONSTRAINT ck_datasource_authorization_scope_positive
        CHECK (tenant_id > 0 AND project_id > 0)
);

COMMENT ON TABLE datasource_authorization IS
    '数据源实例级授权账本，保存某条 datasource_config 授权给某个用户、角色或服务账号的事实。';
COMMENT ON COLUMN datasource_authorization.datasource_id IS
    '被授权的数据源 ID；不使用级联外键，避免数据源逻辑删除影响历史授权审计。';
COMMENT ON COLUMN datasource_authorization.tenant_id IS
    '数据源所属租户快照，用于租户级隔离、授权检索和审计过滤。';
COMMENT ON COLUMN datasource_authorization.project_id IS
    '数据源所属项目快照，用于项目级授权清单和被授权资源可见性判断。';
COMMENT ON COLUMN datasource_authorization.workspace_id IS
    '历史兼容字段；当前用户可见层级已收敛为项目，但保留旧数据和内部沙箱扩展位。';
COMMENT ON COLUMN datasource_authorization.subject_type IS
    '授权主体类型：USER 表示单个用户，ROLE 表示项目/租户角色，SERVICE_ACCOUNT 表示机器身份。';
COMMENT ON COLUMN datasource_authorization.subject_id IS
    '授权主体 ID。USER 通常为 actorId，ROLE 可为角色编码，SERVICE_ACCOUNT 为服务账号 ID。';
COMMENT ON COLUMN datasource_authorization.subject_name IS
    '授权主体展示名称，用于前端弹窗和审计阅读。';
COMMENT ON COLUMN datasource_authorization.subject_role IS
    '授权主体角色快照；按角色授权时可等于角色编码，按用户授权时记录该用户当时角色。';
COMMENT ON COLUMN datasource_authorization.authorized_actions IS
    '逗号分隔的授权动作集合，当前支持 VIEW、USE、MANAGE。MANAGE 在服务层解释为包含 VIEW/USE。';
COMMENT ON COLUMN datasource_authorization.grant_source IS
    '授权来源，例如 UI_MANUAL、IMPORT、SYSTEM_BOOTSTRAP、AGENT_RECOMMENDATION。';
COMMENT ON COLUMN datasource_authorization.status IS
    '授权生命周期状态：ACTIVE 生效，REVOKED 已撤销。';
COMMENT ON COLUMN datasource_authorization.grant_reason IS
    '授权原因，用于解释为什么该主体需要访问这条数据源。';
COMMENT ON COLUMN datasource_authorization.expire_time IS
    '授权过期时间；为空表示长期有效。临时排障授权建议设置过期时间。';
COMMENT ON COLUMN datasource_authorization.granted_by_actor_id IS
    '授权操作人 actorId 快照。';
COMMENT ON COLUMN datasource_authorization.granted_by_actor_role IS
    '授权操作人角色快照。';
COMMENT ON COLUMN datasource_authorization.granted_time IS
    '授权生效时间。';
COMMENT ON COLUMN datasource_authorization.revoked_by_actor_id IS
    '撤销授权操作人 actorId 快照。';
COMMENT ON COLUMN datasource_authorization.revoked_by_actor_role IS
    '撤销授权操作人角色快照。';
COMMENT ON COLUMN datasource_authorization.revoke_reason IS
    '撤销原因，用于审计误授权、人员离岗、临时授权到期等场景。';
COMMENT ON COLUMN datasource_authorization.revoked_time IS
    '撤销时间。';
COMMENT ON COLUMN datasource_authorization.create_time IS
    '记录创建时间，由服务层写入。';
COMMENT ON COLUMN datasource_authorization.update_time IS
    '记录最后更新时间，由服务层写入。';

CREATE INDEX idx_datasource_authorization_datasource
    ON datasource_authorization (datasource_id, status, update_time);
CREATE INDEX idx_datasource_authorization_subject
    ON datasource_authorization (tenant_id, project_id, subject_type, subject_id, status);
CREATE INDEX idx_datasource_authorization_role
    ON datasource_authorization (tenant_id, project_id, subject_role, status);
CREATE INDEX idx_datasource_authorization_expire
    ON datasource_authorization (status, expire_time);

-- 同一数据源、同一主体在 ACTIVE 状态下只允许一条有效授权。
-- 被撤销的历史记录可以保留多条，从而表达“撤销后重新授权”的完整审计链。
CREATE UNIQUE INDEX uk_datasource_authorization_active_subject
    ON datasource_authorization (datasource_id, subject_type, subject_id)
    WHERE status = 'ACTIVE';
