-- permission-admin: project join request approval workflow.
--
-- A join request is not a membership. It is a pending workflow fact. Only approval writes
-- permission_project_membership, which is the durable project data-scope fact consumed by gateway.
SET search_path TO permission_admin, public;

CREATE TABLE IF NOT EXISTS permission_project_join_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    applicant_actor_id BIGINT NOT NULL,
    applicant_name VARCHAR(128),
    requested_project_role VARCHAR(64) NOT NULL DEFAULT 'READER',
    request_reason VARCHAR(500),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    reviewer_actor_id BIGINT,
    reviewer_actor_role VARCHAR(64),
    review_comment VARCHAR(500),
    review_time TIMESTAMP,
    membership_id BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_permission_project_join_request_role
        CHECK (requested_project_role IN ('OWNER', 'MANAGER', 'READER')),
    CONSTRAINT ck_permission_project_join_request_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT fk_permission_project_join_request_project
        FOREIGN KEY (project_id) REFERENCES permission_project (project_id)
);

COMMENT ON TABLE permission_project_join_request IS
    '项目加入申请审批表。PENDING 不会产生数据范围授权；只有 APPROVED 后才会写 permission_project_membership。';
COMMENT ON COLUMN permission_project_join_request.tenant_id IS
    '目标项目所属租户 ID，用于跨公司隔离申请与审批视图。';
COMMENT ON COLUMN permission_project_join_request.project_id IS
    '申请加入的目标项目 ID。';
COMMENT ON COLUMN permission_project_join_request.applicant_actor_id IS
    '申请人 actor ID，对应 gateway/IdP 注入的用户身份。';
COMMENT ON COLUMN permission_project_join_request.requested_project_role IS
    '申请的项目内角色。普通申请默认 READER，MANAGER 需管理员或项目 OWNER 审批；OWNER 通常由管理员直接授权。';
COMMENT ON COLUMN permission_project_join_request.status IS
    '审批状态：PENDING、APPROVED、REJECTED、CANCELLED。';
COMMENT ON COLUMN permission_project_join_request.membership_id IS
    '审批通过后创建或更新的 permission_project_membership 主键。';

CREATE INDEX IF NOT EXISTS idx_permission_project_join_request_project_status
    ON permission_project_join_request (tenant_id, project_id, status, update_time DESC);

CREATE INDEX IF NOT EXISTS idx_permission_project_join_request_applicant
    ON permission_project_join_request (tenant_id, applicant_actor_id, status, update_time DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uk_permission_project_join_request_pending
    ON permission_project_join_request (tenant_id, project_id, applicant_actor_id)
    WHERE status = 'PENDING';

INSERT INTO permission_route_policy
(tenant_id, policy_name, role_code, http_method, path_pattern, resource_type, action, effect, priority, enabled, description, create_time, update_time)
VALUES
(0, '普通用户提交项目加入申请', 'ORDINARY_USER', 'POST', '/api/permission/project-join-requests', 'PROJECT_JOIN_REQUEST', 'APPLY', 'ALLOW', 760, TRUE,
 '普通用户可以申请加入本租户项目。申请本身不产生项目数据范围，必须等待审批通过。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '普通用户查看自己的项目加入申请', 'ORDINARY_USER', 'GET', '/api/permission/project-join-requests/my', 'PROJECT_JOIN_REQUEST', 'VIEW_OWN', 'ALLOW', 760, TRUE,
 '普通用户只能查看自己的项目加入申请记录。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '普通用户撤销自己的项目加入申请', 'ORDINARY_USER', 'POST', '/api/permission/project-join-requests/*/cancel', 'PROJECT_JOIN_REQUEST', 'CANCEL_OWN', 'ALLOW', 760, TRUE,
 '普通用户可以撤销自己仍处于 PENDING 的项目加入申请。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '项目负责人审批项目加入申请', 'PROJECT_OWNER', 'ANY', '/api/permission/project-join-requests/**', 'PROJECT_JOIN_REQUEST', 'REVIEW', 'ALLOW', 780, TRUE,
 '项目负责人可以审批自己拥有 OWNER 成员关系的项目加入申请；Service 层继续校验项目边界。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '租户管理员审批项目加入申请', 'TENANT_ADMINISTRATOR', 'ANY', '/api/permission/project-join-requests/**', 'PROJECT_JOIN_REQUEST', 'REVIEW', 'ALLOW', 800, TRUE,
 '租户管理员可以审批本租户项目加入申请。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '平台管理员审批项目加入申请', 'PLATFORM_ADMINISTRATOR', 'ANY', '/api/permission/project-join-requests/**', 'PROJECT_JOIN_REQUEST', 'REVIEW', 'ALLOW', 900, TRUE,
 '平台管理员可以跨租户排障和审批项目加入申请。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
