-- permission-admin: project creation request approval workflow.
--
-- A creation request is intentionally not a project. It only becomes a project when a tenant or platform
-- administrator approves it and the service writes permission_project plus OWNER membership.
SET search_path TO permission_admin, public;

CREATE TABLE IF NOT EXISTS permission_project_creation_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    application_id BIGINT,
    project_code VARCHAR(64),
    project_name VARCHAR(128) NOT NULL,
    project_type VARCHAR(64) NOT NULL DEFAULT 'DATA_GOVERNANCE',
    applicant_actor_id BIGINT NOT NULL,
    applicant_name VARCHAR(128),
    owner_actor_id BIGINT NOT NULL,
    description VARCHAR(1000),
    request_reason VARCHAR(500),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    reviewer_actor_id BIGINT,
    reviewer_actor_role VARCHAR(64),
    review_comment VARCHAR(500),
    review_time TIMESTAMP,
    created_project_id BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_permission_project_creation_request_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT fk_permission_project_creation_request_application
        FOREIGN KEY (application_id) REFERENCES permission_application (application_id)
);

COMMENT ON TABLE permission_project_creation_request IS
    'Project creation approval workflow facts. PENDING rows do not grant project data scope.';
COMMENT ON COLUMN permission_project_creation_request.tenant_id IS
    'Tenant where the requested project should be created.';
COMMENT ON COLUMN permission_project_creation_request.application_id IS
    'Target application. Null means the service should use the tenant default application at approval time.';
COMMENT ON COLUMN permission_project_creation_request.project_code IS
    'Requested stable project code. It is rechecked when the approval creates the real project.';
COMMENT ON COLUMN permission_project_creation_request.owner_actor_id IS
    'Actor who receives OWNER project membership after approval.';
COMMENT ON COLUMN permission_project_creation_request.created_project_id IS
    'Real project ID created by the approval path.';

CREATE INDEX IF NOT EXISTS idx_permission_project_creation_request_reviewer
    ON permission_project_creation_request (tenant_id, status, update_time DESC);

CREATE INDEX IF NOT EXISTS idx_permission_project_creation_request_applicant
    ON permission_project_creation_request (tenant_id, applicant_actor_id, status, update_time DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uk_permission_project_creation_request_pending_code
    ON permission_project_creation_request (tenant_id, project_code)
    WHERE status = 'PENDING' AND project_code IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_permission_project_creation_request_pending_applicant_name
    ON permission_project_creation_request (tenant_id, applicant_actor_id, project_name)
    WHERE status = 'PENDING';

INSERT INTO permission_route_policy
(tenant_id, policy_name, role_code, http_method, path_pattern, resource_type, action, effect, priority, enabled, description, create_time, update_time)
VALUES
(0, 'Ordinary user applies to create project', 'ORDINARY_USER', 'POST', '/api/permission/project-creation-requests', 'PROJECT_CREATION_REQUEST', 'APPLY', 'ALLOW', 760, TRUE,
 'Ordinary users can request project creation. Approval is required before project data scope exists.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'Project owner applies to create project', 'PROJECT_OWNER', 'POST', '/api/permission/project-creation-requests', 'PROJECT_CREATION_REQUEST', 'APPLY', 'ALLOW', 760, TRUE,
 'Project owners can request additional projects, but tenant or platform administrators still approve creation.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'Operator applies to create project', 'OPERATOR', 'POST', '/api/permission/project-creation-requests', 'PROJECT_CREATION_REQUEST', 'APPLY', 'ALLOW', 760, TRUE,
 'Operators can request operational projects when tenant administrators approve them.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'User views own project creation requests', 'ORDINARY_USER', 'GET', '/api/permission/project-creation-requests/my', 'PROJECT_CREATION_REQUEST', 'VIEW_OWN', 'ALLOW', 760, TRUE,
 'Users can query only their own project creation requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'Project owner views own project creation requests', 'PROJECT_OWNER', 'GET', '/api/permission/project-creation-requests/my', 'PROJECT_CREATION_REQUEST', 'VIEW_OWN', 'ALLOW', 760, TRUE,
 'Project owners can query their own project creation requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'Operator views own project creation requests', 'OPERATOR', 'GET', '/api/permission/project-creation-requests/my', 'PROJECT_CREATION_REQUEST', 'VIEW_OWN', 'ALLOW', 760, TRUE,
 'Operators can query their own project creation requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'User cancels own project creation request', 'ORDINARY_USER', 'POST', '/api/permission/project-creation-requests/*/cancel', 'PROJECT_CREATION_REQUEST', 'CANCEL_OWN', 'ALLOW', 760, TRUE,
 'Users can cancel their own still-pending project creation requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'Project owner cancels own project creation request', 'PROJECT_OWNER', 'POST', '/api/permission/project-creation-requests/*/cancel', 'PROJECT_CREATION_REQUEST', 'CANCEL_OWN', 'ALLOW', 760, TRUE,
 'Project owners can cancel their own still-pending project creation requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'Operator cancels own project creation request', 'OPERATOR', 'POST', '/api/permission/project-creation-requests/*/cancel', 'PROJECT_CREATION_REQUEST', 'CANCEL_OWN', 'ALLOW', 760, TRUE,
 'Operators can cancel their own still-pending project creation requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'Tenant administrator reviews project creation requests', 'TENANT_ADMINISTRATOR', 'ANY', '/api/permission/project-creation-requests/**', 'PROJECT_CREATION_REQUEST', 'REVIEW', 'ALLOW', 820, TRUE,
 'Tenant administrators can approve or reject project creation requests in their tenant.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'Platform administrator reviews project creation requests', 'PLATFORM_ADMINISTRATOR', 'ANY', '/api/permission/project-creation-requests/**', 'PROJECT_CREATION_REQUEST', 'REVIEW', 'ALLOW', 900, TRUE,
 'Platform administrators can approve or reject project creation requests across tenants.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
