-- identity provisioning shadow schema.
--
-- 设计目标：
-- 1. Keycloak/企业 IdP 继续持有密码、登录态、MFA、账号锁定、Token 签发等高敏能力；
-- 2. permission-admin 只保存低敏影子身份，用于 DataSmart 内部 actorId、tenantId、role、workspace 和审计；
-- 3. 账号生命周期不物理删除，禁用后保留历史，便于审计员复盘账号来源与停用原因；
-- 4. 新增默认路由策略，确保 /api/identity/** 不会因为平台管理员 /api/** 之外的宽泛规则而裸奔。

SET search_path TO permission_admin, public;

CREATE SEQUENCE IF NOT EXISTS permission_identity_actor_id_seq
    START WITH 100000
    INCREMENT BY 1;
COMMENT ON SEQUENCE permission_identity_actor_id_seq IS
    'DataSmart 内部 actorId 分配序列；独立于影子表主键，确保多实例账号供应时主体 ID 不重复。';

CREATE TABLE IF NOT EXISTS permission_identity_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    actor_id BIGINT NOT NULL,
    provider_mode VARCHAR(64) NOT NULL,
    provider_user_id VARCHAR(128) NOT NULL,
    username VARCHAR(128) NOT NULL,
    email VARCHAR(255),
    actor_role VARCHAR(64) NOT NULL,
    actor_type VARCHAR(64) NOT NULL DEFAULT 'USER',
    workspace_id VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    disabled_reason VARCHAR(500),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_permission_identity_tenant_non_negative CHECK (tenant_id >= 0),
    CONSTRAINT ck_permission_identity_actor_positive CHECK (actor_id > 0),
    CONSTRAINT ck_permission_identity_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT uk_permission_identity_tenant_actor UNIQUE (tenant_id, actor_id),
    CONSTRAINT uk_permission_identity_provider_user UNIQUE (provider_mode, provider_user_id),
    CONSTRAINT uk_permission_identity_provider_username UNIQUE (provider_mode, username)
);

COMMENT ON TABLE permission_identity_user IS
    'DataSmart 身份影子表；不保存密码、Token、client secret 或 IdP admin 凭据，只保存外部身份到内部 actor 的低敏映射。';
COMMENT ON COLUMN permission_identity_user.tenant_id IS
    '租户 ID；租户管理员只能管理本租户，平台管理员可以跨租户。';
COMMENT ON COLUMN permission_identity_user.actor_id IS
    'DataSmart 内部主体 ID；进入 gateway Header、审计、Agent 记忆责任链和业务授权。';
COMMENT ON COLUMN permission_identity_user.provider_mode IS
    '身份供应模式，例如 KEYCLOAK_ADMIN_API、ENTERPRISE_IDP、SCIM。';
COMMENT ON COLUMN permission_identity_user.provider_user_id IS
    '外部 IdP 用户 ID，例如 Keycloak UUID；禁用、重置密码和审计定位都使用该字段。';
COMMENT ON COLUMN permission_identity_user.username IS
    '登录用户名；用于 IdP 登录和后台检索，但不作为唯一授权主体。';
COMMENT ON COLUMN permission_identity_user.email IS
    '邮箱；属于个人信息，API 响应应按场景脱敏。';
COMMENT ON COLUMN permission_identity_user.actor_role IS
    'DataSmart 角色编码，例如 ORDINARY_USER、TENANT_ADMINISTRATOR。';
COMMENT ON COLUMN permission_identity_user.actor_type IS
    '主体类型，常见值 USER 或 SERVICE_ACCOUNT；人类用户和机器账号必须分开审计。';
COMMENT ON COLUMN permission_identity_user.workspace_id IS
    '默认 workspace，用于 Agent、工具、RAG、记忆和项目范围隔离。';
COMMENT ON COLUMN permission_identity_user.status IS
    '本地影子状态；ACTIVE 表示可参与业务授权，DISABLED 表示账号已禁用或不应再参与授权。';
COMMENT ON COLUMN permission_identity_user.disabled_reason IS
    '禁用原因，便于审计员复盘离职、冻结、租户退订等账号生命周期事件。';

CREATE INDEX IF NOT EXISTS idx_permission_identity_tenant_status
    ON permission_identity_user (tenant_id, status, update_time DESC);
CREATE INDEX IF NOT EXISTS idx_permission_identity_actor
    ON permission_identity_user (actor_id);
CREATE INDEX IF NOT EXISTS idx_permission_identity_username
    ON permission_identity_user (username);

INSERT INTO permission_menu
(menu_code, parent_code, menu_name, path, icon, sort_order, enabled, description, create_time, update_time)
VALUES
('identity', NULL, '身份账号', '/identity', 'UserSwitchOutlined', 55, TRUE,
 'Keycloak/企业 IdP 账号供应、禁用、密码重置和本地影子身份审计入口。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (menu_code) DO NOTHING;

INSERT INTO permission_role_menu_binding
(tenant_id, role_code, menu_code, enabled, binding_source, note, create_time, update_time)
VALUES
(0, 'TENANT_ADMINISTRATOR', 'identity', TRUE, 'BOOTSTRAP', '租户管理员可管理本租户身份账号供应。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'PLATFORM_ADMINISTRATOR', 'identity', TRUE, 'BOOTSTRAP', '平台管理员可跨租户管理身份账号供应。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'AUDITOR', 'identity', TRUE, 'BOOTSTRAP', '审计员可只读查看身份供应能力与审计线索。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (tenant_id, role_code, menu_code) DO NOTHING;

INSERT INTO permission_route_policy
(tenant_id, policy_name, role_code, http_method, path_pattern, resource_type, action, effect, priority, enabled, description, create_time, update_time)
VALUES
(0, '普通用户禁止身份账号管理', 'ORDINARY_USER', 'ANY', '/api/identity/**', 'IDENTITY_USER', NULL, 'DENY', 760, TRUE,
 '身份账号管理会影响登录主体和权限边界，普通用户不得访问。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '项目负责人禁止身份账号管理', 'PROJECT_OWNER', 'ANY', '/api/identity/**', 'IDENTITY_USER', NULL, 'DENY', 760, TRUE,
 '项目负责人可以管理项目成员授权，但不应创建或重置平台登录账号。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '运营人员禁止身份账号管理', 'OPERATOR', 'ANY', '/api/identity/**', 'IDENTITY_USER', NULL, 'DENY', 760, TRUE,
 '运营人员可排障任务和告警，但不应改变登录凭据或账号状态。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '审计员只读查看身份供应', 'AUDITOR', 'GET', '/api/identity/**', 'IDENTITY_USER', 'VIEW', 'ALLOW', 130, TRUE,
 '审计员可以查看低敏身份供应能力说明和审计线索，但不能执行写动作。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '审计员禁止身份写操作', 'AUDITOR', 'POST', '/api/identity/**', 'IDENTITY_USER', NULL, 'DENY', 930, TRUE,
 '审计员是只读角色，不能创建账号、禁用账号或重置密码。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '租户管理员管理本租户身份账号', 'TENANT_ADMINISTRATOR', 'ANY', '/api/identity/**', 'IDENTITY_USER', NULL, 'ALLOW', 170, TRUE,
 '租户管理员可管理本租户账号供应；跨租户边界由 service 层继续校验。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '平台管理员管理全平台身份账号', 'PLATFORM_ADMINISTRATOR', 'ANY', '/api/identity/**', 'IDENTITY_USER', NULL, 'ALLOW', 1000, TRUE,
 '平台管理员可跨租户管理身份账号供应，高风险动作仍会进入审计。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

INSERT INTO permission_data_scope_policy
(tenant_id, role_code, resource_type, scope_level, scope_expression, approval_required, enabled, description, create_time, update_time)
VALUES
(0, 'AUDITOR', 'IDENTITY_USER', 'TENANT', 'tenant_id = ${tenantId}', FALSE, TRUE,
 '审计员默认只能查看本租户身份账号审计线索。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'TENANT_ADMINISTRATOR', 'IDENTITY_USER', 'TENANT', 'tenant_id = ${tenantId}', FALSE, TRUE,
 '租户管理员只能管理本租户身份账号。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'PLATFORM_ADMINISTRATOR', 'IDENTITY_USER', 'PLATFORM', '1 = 1', TRUE, TRUE,
 '平台管理员可跨租户管理身份账号，但建议对批量导入、批量禁用等动作继续接审批。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (tenant_id, role_code, resource_type) DO NOTHING;
