-- Close the authenticated Agent Console permission contract for governed RAG and runtime-event delivery.
--
-- Route policies only decide whether a role may enter an endpoint. Gateway still rebuilds tenant/application/project
-- identity, Python verifies the HMAC or Agent Runtime service token, RAG filters evidence by that scope, and the
-- Java/Python event stores continue to apply object-level event visibility. No policy below grants tool execution,
-- Specialist fact registration, approval creation, outbox recovery, memory mutation, or business-data writes.
SET search_path TO permission_admin, public;

INSERT INTO permission_route_policy
(tenant_id, policy_name, role_code, http_method, path_pattern, resource_type, action, effect, priority, enabled,
 description, create_time, update_time)
VALUES
-- Interactive users: personal/project-scoped knowledge query and event delivery.
(0, '普通用户执行受治理 RAG 查询', 'ORDINARY_USER', 'POST', '/api/agent/rag/query',
 'AI_RUNTIME', 'EXECUTE', 'ALLOW', 972, TRUE,
 '正文只能提供问题和检索参数；租户、应用、项目、用户与隔离范围由 Gateway 签名上下文重建。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '普通用户读取 RAG 低敏诊断', 'ORDINARY_USER', 'GET', '/api/agent/rag/diagnostics',
 'AI_RUNTIME', 'DIAGNOSE', 'ALLOW', 971, TRUE,
 '只返回检索阶段、证据门禁、持久化与 checkpoint 状态，不返回问题、文档正文或模型输出。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '普通用户补偿回放本人 Agent 事件', 'ORDINARY_USER', 'POST', '/api/agent/events/replay',
 'AI_RUNTIME', 'VIEW_EVENTS', 'ALLOW', 972, TRUE,
 '只回放当前用户在当前授权项目中的低敏 Agent 事件；request/session/run 标识不是授权凭据。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '普通用户控制本人 Agent 事件订阅', 'ORDINARY_USER', 'POST', '/api/agent/events/control',
 'AI_RUNTIME', 'SUBSCRIBE', 'ALLOW', 972, TRUE,
 '只管理当前用户事件订阅的 subscribe、ack、heartbeat、reconnect 和 unsubscribe 状态。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '普通用户查看本人 Agent 运行事件投影', 'ORDINARY_USER', 'GET', '/api/agent/runtime-events/**',
 'AI_RUNTIME', 'VIEW_EVENTS', 'ALLOW', 972, TRUE,
 '只读取当前用户当前授权项目中的低敏运行事件；Java 控制面继续执行对象归属校验。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '普通用户查看 Agent 模型路由摘要', 'ORDINARY_USER', 'GET', '/api/agent/models/routes',
 'AI_RUNTIME', 'VIEW', 'ALLOW', 970, TRUE,
 '只返回模型路由低敏摘要，不返回 Provider 凭据或内部请求正文。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '普通用户查看 Agent 工具目录', 'ORDINARY_USER', 'GET', '/api/agent/tools/**',
 'AI_RUNTIME', 'VIEW', 'ALLOW', 970, TRUE,
 '只读取可见工具描述、风险和输入 schema；不授予工具执行权限。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '普通用户查看 Agent 闭口能力摘要', 'ORDINARY_USER', 'GET', '/api/agent/capabilities/**',
 'AI_RUNTIME', 'DIAGNOSE', 'ALLOW', 970, TRUE,
 '只读取低敏能力闭口摘要，不能据此跳过计划、审批或执行门禁。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(0, '项目负责人执行受治理 RAG 查询', 'PROJECT_OWNER', 'POST', '/api/agent/rag/query',
 'AI_RUNTIME', 'EXECUTE', 'ALLOW', 982, TRUE,
 '项目负责人只能查询当前已授权项目证据，项目角色不会把正文 projectId 变成可信范围。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '项目负责人读取 RAG 低敏诊断', 'PROJECT_OWNER', 'GET', '/api/agent/rag/diagnostics',
 'AI_RUNTIME', 'DIAGNOSE', 'ALLOW', 981, TRUE,
 '只返回 RAG 控制面状态，不返回知识正文、问题、压缩上下文或模型输出。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '项目负责人补偿回放本人 Agent 事件', 'PROJECT_OWNER', 'POST', '/api/agent/events/replay',
 'AI_RUNTIME', 'VIEW_EVENTS', 'ALLOW', 982, TRUE,
 '项目负责人仍按本人会话和当前授权项目回放事件，不能借角色接管成员会话。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '项目负责人控制本人 Agent 事件订阅', 'PROJECT_OWNER', 'POST', '/api/agent/events/control',
 'AI_RUNTIME', 'SUBSCRIBE', 'ALLOW', 982, TRUE,
 '只管理当前项目负责人本人会话的实时事件订阅状态。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '项目负责人查看本人 Agent 运行事件投影', 'PROJECT_OWNER', 'GET', '/api/agent/runtime-events/**',
 'AI_RUNTIME', 'VIEW_EVENTS', 'ALLOW', 982, TRUE,
 '项目负责人仍只能读取本人会话和当前授权项目中的运行事件。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '项目负责人查看 Agent 模型路由摘要', 'PROJECT_OWNER', 'GET', '/api/agent/models/routes',
 'AI_RUNTIME', 'VIEW', 'ALLOW', 980, TRUE,
 '只返回模型选择与健康关联所需低敏字段，不返回密钥。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '项目负责人查看 Agent 工具目录', 'PROJECT_OWNER', 'GET', '/api/agent/tools/**',
 'AI_RUNTIME', 'VIEW', 'ALLOW', 980, TRUE,
 '只读取工具目录，实际执行继续经过会话绑定、权限、审批和下游二次校验。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '项目负责人查看 Agent 闭口能力摘要', 'PROJECT_OWNER', 'GET', '/api/agent/capabilities/**',
 'AI_RUNTIME', 'DIAGNOSE', 'ALLOW', 980, TRUE,
 '只读取低敏能力闭口摘要，不扩大项目数据范围。',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Operations and audit roles: read-only diagnostics plus governed event subscription/replay.
(0, '运营人员诊断 RAG 管线', 'OPERATOR', 'GET', '/api/agent/rag/diagnostics',
 'AI_RUNTIME', 'DIAGNOSE', 'ALLOW', 990, TRUE,
 '读取 RAG 检索、证据、持久化和 checkpoint 低敏运行状态。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '审计员诊断 RAG 管线', 'AUDITOR', 'GET', '/api/agent/rag/diagnostics',
 'AI_RUNTIME', 'DIAGNOSE', 'ALLOW', 990, TRUE,
 '读取 RAG 控制面状态用于审计，不返回问题或证据正文。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '运营人员回放 Agent 事件', 'OPERATOR', 'POST', '/api/agent/events/replay',
 'AI_RUNTIME', 'VIEW_EVENTS', 'ALLOW', 992, TRUE,
 '在明确租户和项目范围内回放低敏运行事件用于排障。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '审计员回放 Agent 事件', 'AUDITOR', 'POST', '/api/agent/events/replay',
 'AI_RUNTIME', 'VIEW_EVENTS', 'ALLOW', 992, TRUE,
 '在明确租户和项目范围内回放只读审计事件。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '运营人员控制 Agent 事件订阅', 'OPERATOR', 'POST', '/api/agent/events/control',
 'AI_RUNTIME', 'SUBSCRIBE', 'ALLOW', 992, TRUE,
 '管理低敏运行事件订阅状态，不执行工具或修改业务对象。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '审计员控制 Agent 事件订阅', 'AUDITOR', 'POST', '/api/agent/events/control',
 'AI_RUNTIME', 'SUBSCRIBE', 'ALLOW', 992, TRUE,
 '管理只读审计事件订阅状态，不授予执行动作。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '运营人员查看 Agent 运行事件投影', 'OPERATOR', 'GET', '/api/agent/runtime-events/**',
 'AI_RUNTIME', 'VIEW_EVENTS', 'ALLOW', 992, TRUE,
 '在当前可信租户范围内读取低敏运行事件用于排障。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '审计员查看 Agent 运行事件投影', 'AUDITOR', 'GET', '/api/agent/runtime-events/**',
 'AI_RUNTIME', 'VIEW_EVENTS', 'ALLOW', 992, TRUE,
 '在当前可信租户范围内读取低敏运行事件用于只读审计。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '运营人员查看 Agent 模型路由', 'OPERATOR', 'GET', '/api/agent/models/routes',
 'AI_RUNTIME', 'VIEW', 'ALLOW', 990, TRUE,
 '查看模型路由低敏摘要用于排障。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '审计员查看 Agent 模型路由', 'AUDITOR', 'GET', '/api/agent/models/routes',
 'AI_RUNTIME', 'VIEW', 'ALLOW', 990, TRUE,
 '查看模型路由低敏摘要用于配置审计。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '运营人员查看 Agent 工具目录', 'OPERATOR', 'GET', '/api/agent/tools/**',
 'AI_RUNTIME', 'VIEW', 'ALLOW', 990, TRUE,
 '查看工具风险与服务映射，不授予执行权限。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, '审计员查看 Agent 工具目录', 'AUDITOR', 'GET', '/api/agent/tools/**',
 'AI_RUNTIME', 'VIEW', 'ALLOW', 990, TRUE,
 '查看工具治理元数据，不授予执行权限。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

-- Keep diagnostic endpoints as a narrow exact allow-list for project owners and operational roles.
INSERT INTO permission_route_policy
(tenant_id, policy_name, role_code, http_method, path_pattern, resource_type, action, effect, priority, enabled,
 description, create_time, update_time)
SELECT 0,
       role_code || ' 读取 Agent Console 低敏诊断 ' || path_pattern,
       role_code,
       'GET',
       path_pattern,
       'AI_RUNTIME',
       'DIAGNOSE',
       'ALLOW',
       CASE role_code WHEN 'PROJECT_OWNER' THEN 985 ELSE 995 END,
       TRUE,
       '只返回状态、计数、版本和错误分类，不返回 prompt、SQL、工具参数、凭据、样本或模型输出正文。',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM (VALUES
    ('PROJECT_OWNER', '/api/agent/runtime-events/diagnostics'),
    ('PROJECT_OWNER', '/api/agent/runtime-events/skill-visibility-snapshots/diagnostics'),
    ('PROJECT_OWNER', '/api/agent/models/provider-health/diagnostics'),
    ('PROJECT_OWNER', '/api/agent/platform/convergence/diagnostics'),
    ('PROJECT_OWNER', '/api/agent/async-task-commands/outbox/diagnostics'),
    ('PROJECT_OWNER', '/api/agent/tool-execution-events/outbox/diagnostics'),
    ('OPERATOR', '/api/agent/runtime-events/diagnostics'),
    ('OPERATOR', '/api/agent/runtime-events/skill-visibility-snapshots/diagnostics'),
    ('OPERATOR', '/api/agent/models/provider-health/diagnostics'),
    ('OPERATOR', '/api/agent/capabilities/closure-readiness'),
    ('OPERATOR', '/api/agent/platform/convergence/diagnostics'),
    ('OPERATOR', '/api/agent/async-task-commands/outbox/diagnostics'),
    ('OPERATOR', '/api/agent/tool-execution-events/outbox/diagnostics'),
    ('AUDITOR', '/api/agent/runtime-events/diagnostics'),
    ('AUDITOR', '/api/agent/runtime-events/skill-visibility-snapshots/diagnostics'),
    ('AUDITOR', '/api/agent/models/provider-health/diagnostics'),
    ('AUDITOR', '/api/agent/capabilities/closure-readiness'),
    ('AUDITOR', '/api/agent/platform/convergence/diagnostics'),
    ('AUDITOR', '/api/agent/async-task-commands/outbox/diagnostics'),
    ('AUDITOR', '/api/agent/tool-execution-events/outbox/diagnostics')
) AS diagnostic_routes(role_code, path_pattern)
ON CONFLICT DO NOTHING;

-- Operational event reads are tenant-bounded. Interactive users retain V35 SELF scope.
INSERT INTO permission_data_scope_policy
(tenant_id, role_code, resource_type, scope_level, scope_expression, approval_required, enabled, description,
 create_time, update_time)
VALUES
(0, 'OPERATOR', 'AI_RUNTIME', 'TENANT', 'tenant_id = ${tenantId}', FALSE, TRUE,
 '运营人员只能在当前可信租户范围内读取 Agent 诊断和运行事件。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0, 'AUDITOR', 'AI_RUNTIME', 'TENANT', 'tenant_id = ${tenantId}', FALSE, TRUE,
 '审计员只能在当前可信租户范围内读取 Agent 诊断和运行事件。', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (tenant_id, role_code, resource_type) DO UPDATE
SET scope_level = EXCLUDED.scope_level,
    scope_expression = EXCLUDED.scope_expression,
    approval_required = EXCLUDED.approval_required,
    enabled = EXCLUDED.enabled,
    description = EXCLUDED.description,
    update_time = CURRENT_TIMESTAMP;
