-- DataSmart Govern - agent-runtime PostgreSQL 控制面基线。
--
-- 迁移边界：
-- 1. 本脚本只创建 Java agent-runtime 当前 JDBC store 真实使用的 11 张控制面事实表。
-- 2. 本批不迁移 agent_memory_*。长期记忆、用户画像、pgvector 语义索引和 LangGraph durable state
--    后续应进入独立 `ai_memory` schema，避免把“Agent 控制面事实”和“AI 长期记忆正文/向量”混在同一生命周期里。
-- 3. JSON-like 字段当前保持 TEXT，因为 Java JDBC mapper 均按 String 绑定；未来若升级 JSONB，必须同步
--    TypeHandler、查询 SQL、迁移脚本 checksum、存量迁移脚手架和对账摘要。
-- 4. Java Instant/LocalDateTime 对应 TIMESTAMP WITHOUT TIME ZONE，避免迁移期被数据库 session 时区隐式改写审计事实。
-- 5. MySQL TINYINT(1) 转 PostgreSQL BOOLEAN，让 requiresApproval、readOnly、sideEffectExecuted 等开关语义清晰。
-- 6. 本脚本不创建跨微服务外键。agent-runtime 保存的是可审计事实和低敏引用，删除、归档和保留期应由运维策略显式治理。
-- 7. 旧 store mode 字符串 `mysql` 仍作为兼容别名存在，但本脚本是目标态 PostgreSQL 基线，不再新增 MySQL 专属语法。

SET search_path TO agent_runtime, public;

CREATE TABLE IF NOT EXISTS agent_tool_execution_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id VARCHAR(128) NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    binding_id VARCHAR(160) NOT NULL,
    tool_code VARCHAR(128) NOT NULL,
    tool_type VARCHAR(80) NOT NULL,
    target_service VARCHAR(128),
    target_endpoint VARCHAR(300),
    target_resource_id BIGINT,
    tenant_id BIGINT,
    project_id BIGINT,
    workspace_id BIGINT,
    actor_id VARCHAR(128),
    risk_level VARCHAR(64) NOT NULL,
    execution_mode VARCHAR(80) NOT NULL,
    requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    read_only BOOLEAN NOT NULL DEFAULT TRUE,
    idempotent BOOLEAN NOT NULL DEFAULT FALSE,
    allowed_actions TEXT NOT NULL,
    plan_reason TEXT,
    plan_arguments TEXT,
    governance_hints TEXT,
    parameter_validation TEXT,
    state VARCHAR(64) NOT NULL,
    trace_id VARCHAR(128),
    message VARCHAR(1024),
    approval_operator_id VARCHAR(128),
    approval_comment VARCHAR(1024),
    approval_time TIMESTAMP WITHOUT TIME ZONE,
    execution_start_time TIMESTAMP WITHOUT TIME ZONE,
    execution_finish_time TIMESTAMP WITHOUT TIME ZONE,
    output_summary VARCHAR(2048),
    error_code VARCHAR(128),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_agent_tool_execution_audit_audit_id UNIQUE (audit_id),
    CONSTRAINT ck_agent_tool_execution_audit_state CHECK (state IN (
        'PLANNED', 'WAITING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTING',
        'SUCCEEDED', 'FAILED', 'SKIPPED', 'CANCELLED'
    ))
);

COMMENT ON TABLE agent_tool_execution_audit IS 'Agent 工具执行审计表，保存一次工具计划、审批、执行和终态的低敏控制面事实';
COMMENT ON COLUMN agent_tool_execution_audit.audit_id IS '工具执行审计业务主键，对应一次 Agent 工具计划/审批/执行链路';
COMMENT ON COLUMN agent_tool_execution_audit.session_id IS 'Agent 会话 ID，用于会话级运行详情、WebSocket replay 和用户侧排障';
COMMENT ON COLUMN agent_tool_execution_audit.run_id IS 'Agent Run ID，用于把多次工具调用归属于同一次模型规划或 LangGraph 运行';
COMMENT ON COLUMN agent_tool_execution_audit.binding_id IS '工具绑定或 Python ToolPlan 派生 ID，用于关联工具目录和模型计划快照';
COMMENT ON COLUMN agent_tool_execution_audit.tool_code IS '工具编码，例如 datasource.metadata.read、quality.rule.suggest、task.draft.persist';
COMMENT ON COLUMN agent_tool_execution_audit.target_service IS '目标微服务逻辑名，只保存白名单服务编码，不保存内部 URL 或动态地址';
COMMENT ON COLUMN agent_tool_execution_audit.target_endpoint IS '目标端点模板，用于审计工具计划会触达哪个业务能力，禁止保存外部输入拼出的任意 URL';
COMMENT ON COLUMN agent_tool_execution_audit.tenant_id IS '租户边界快照，用于后续多租户隔离、SLA、配额和审计过滤';
COMMENT ON COLUMN agent_tool_execution_audit.project_id IS '项目边界快照，用于项目级权限、成本归集和运行详情过滤';
COMMENT ON COLUMN agent_tool_execution_audit.workspace_id IS 'Agent 工作空间 ID，用于类 OpenClaw 工作区隔离和产物追踪';
COMMENT ON COLUMN agent_tool_execution_audit.risk_level IS '工具风险等级，影响审批、权限、审计和运行时保护策略';
COMMENT ON COLUMN agent_tool_execution_audit.execution_mode IS '工具执行模式，例如 SYNC、DRAFT_ONLY、APPROVAL_REQUIRED';
COMMENT ON COLUMN agent_tool_execution_audit.requires_approval IS '是否要求人工审批；高风险工具通常必须进入审批闸门';
COMMENT ON COLUMN agent_tool_execution_audit.read_only IS '是否只读工具；非只读工具需要更严格的权限、幂等和副作用保护';
COMMENT ON COLUMN agent_tool_execution_audit.idempotent IS '工具是否幂等；影响失败重试、重复提交保护和补偿策略';
COMMENT ON COLUMN agent_tool_execution_audit.allowed_actions IS '允许动作 JSON 文本，只保存动作名集合，不保存工具参数值';
COMMENT ON COLUMN agent_tool_execution_audit.plan_arguments IS '模型计划工具参数 JSON 文本；生产环境应脱敏或改为 payloadReference，避免保存敏感正文';
COMMENT ON COLUMN agent_tool_execution_audit.parameter_validation IS '参数校验摘要 JSON 文本，例如缺失字段、系统补全字段和必须澄清字段';
COMMENT ON COLUMN agent_tool_execution_audit.state IS '工具执行状态，由服务层状态机维护合法流转，数据库 CHECK 只阻止明显非法值';
COMMENT ON COLUMN agent_tool_execution_audit.output_summary IS '工具输出低敏摘要，禁止保存完整结果、样本数据、stdout/stderr、prompt 或模型输出正文';
COMMENT ON COLUMN agent_tool_execution_audit.error_code IS '失败机器错误码，用于告警聚合、失败分类和运营统计';

CREATE INDEX IF NOT EXISTS idx_agent_tool_execution_audit_run_state ON agent_tool_execution_audit (session_id, run_id, state, id);
CREATE INDEX IF NOT EXISTS idx_agent_tool_execution_audit_scope_state ON agent_tool_execution_audit (tenant_id, project_id, state, update_time);
CREATE INDEX IF NOT EXISTS idx_agent_tool_execution_audit_tool_state ON agent_tool_execution_audit (tool_code, state, update_time);
CREATE INDEX IF NOT EXISTS idx_agent_tool_execution_audit_trace ON agent_tool_execution_audit (trace_id);
CREATE INDEX IF NOT EXISTS idx_agent_tool_execution_audit_approval ON agent_tool_execution_audit (requires_approval, state, approval_time);

CREATE TABLE IF NOT EXISTS agent_tool_execution_event_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id VARCHAR(300) NOT NULL,
    event_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    schema_version VARCHAR(80) NOT NULL,
    source VARCHAR(80) NOT NULL,
    partition_key VARCHAR(160),
    tenant_id BIGINT,
    project_id BIGINT,
    workspace_id BIGINT,
    actor_id VARCHAR(128),
    session_id VARCHAR(128),
    run_id VARCHAR(128),
    audit_id VARCHAR(128) NOT NULL,
    tool_code VARCHAR(128),
    current_state VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    payload_json TEXT NOT NULL,
    payload_size_bytes INTEGER NOT NULL DEFAULT 0,
    payload_truncated BOOLEAN NOT NULL DEFAULT FALSE,
    occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    next_retry_at TIMESTAMP WITHOUT TIME ZONE,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    last_error VARCHAR(1024),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_tool_event_outbox_outbox_id UNIQUE (outbox_id),
    CONSTRAINT uk_agent_tool_event_outbox_event_id UNIQUE (event_id),
    CONSTRAINT ck_agent_tool_event_outbox_attempt CHECK (attempt_count >= 0 AND payload_size_bytes >= 0),
    CONSTRAINT ck_agent_tool_event_outbox_status CHECK (status IN (
        'PENDING', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'BLOCKED', 'IGNORED'
    ))
);

COMMENT ON TABLE agent_tool_execution_event_outbox IS 'Agent 工具状态事件 outbox 表，用本地事实表解决状态提交与事件投递之间的双写可靠性问题';
COMMENT ON COLUMN agent_tool_execution_event_outbox.outbox_id IS 'outbox 记录唯一 ID，建议由 event_id 派生，用于幂等写入和运维定位';
COMMENT ON COLUMN agent_tool_execution_event_outbox.event_id IS '工具状态事件 ID，对应 AgentToolExecutionStateChangedEvent.eventId';
COMMENT ON COLUMN agent_tool_execution_event_outbox.partition_key IS '建议投递到 Kafka 时使用的分区键，通常为 runId、sessionId 或 auditId';
COMMENT ON COLUMN agent_tool_execution_event_outbox.audit_id IS '关联工具执行审计 ID，用于从事件投递状态回到工具状态事实';
COMMENT ON COLUMN agent_tool_execution_event_outbox.status IS 'outbox 投递状态，dispatcher 按该字段认领、重试、标记成功或失败';
COMMENT ON COLUMN agent_tool_execution_event_outbox.payload_json IS '待投递事件 JSON 文本，应为脱敏后的状态事件，不应保存完整工具入参或原始输出';
COMMENT ON COLUMN agent_tool_execution_event_outbox.payload_truncated IS 'payload 是否被安全策略截断或阻断；生产环境应优先阻断异常大事件而不是静默截断';
COMMENT ON COLUMN agent_tool_execution_event_outbox.next_retry_at IS '下一次允许重试投递时间，用于退避、限流和避免事件风暴';
COMMENT ON COLUMN agent_tool_execution_event_outbox.last_error IS '最近一次投递失败或阻断原因摘要，禁止保存敏感 payload 或完整堆栈';

CREATE INDEX IF NOT EXISTS idx_agent_tool_event_outbox_status_retry ON agent_tool_execution_event_outbox (status, next_retry_at, id);
CREATE INDEX IF NOT EXISTS idx_agent_tool_event_outbox_status_update ON agent_tool_execution_event_outbox (status, update_time, id);
CREATE INDEX IF NOT EXISTS idx_agent_tool_event_outbox_run_status ON agent_tool_execution_event_outbox (run_id, status, id);
CREATE INDEX IF NOT EXISTS idx_agent_tool_event_outbox_audit ON agent_tool_execution_event_outbox (audit_id);
CREATE INDEX IF NOT EXISTS idx_agent_tool_event_outbox_scope_time ON agent_tool_execution_event_outbox (tenant_id, project_id, occurred_at);

CREATE TABLE IF NOT EXISTS agent_async_task_command_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id VARCHAR(300) NOT NULL,
    command_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    schema_version VARCHAR(80) NOT NULL,
    command_type VARCHAR(80) NOT NULL,
    partition_key VARCHAR(160),
    command_topic VARCHAR(160),
    consumer_service VARCHAR(128),
    session_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    audit_id VARCHAR(128) NOT NULL,
    tool_code VARCHAR(128) NOT NULL,
    target_service VARCHAR(128) NOT NULL,
    target_endpoint VARCHAR(300),
    tenant_id BIGINT,
    project_id BIGINT,
    workspace_id BIGINT,
    actor_id VARCHAR(128),
    trace_id VARCHAR(128),
    payload_reference VARCHAR(512) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    payload_json TEXT NOT NULL,
    payload_size_bytes INTEGER NOT NULL DEFAULT 0,
    payload_truncated BOOLEAN NOT NULL DEFAULT FALSE,
    next_retry_at TIMESTAMP WITHOUT TIME ZONE,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    last_error VARCHAR(1024),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_async_command_outbox_id UNIQUE (outbox_id),
    CONSTRAINT uk_agent_async_command_id UNIQUE (command_id),
    CONSTRAINT uk_agent_async_command_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_agent_async_command_attempt CHECK (attempt_count >= 0 AND payload_size_bytes >= 0),
    CONSTRAINT ck_agent_async_command_status CHECK (status IN (
        'PENDING', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'BLOCKED', 'DEAD_LETTER', 'IGNORED'
    ))
);

COMMENT ON TABLE agent_async_task_command_outbox IS 'Agent ASYNC_TASK 命令 outbox 表，用于可靠投递创建下游任务的动作命令';
COMMENT ON COLUMN agent_async_task_command_outbox.command_id IS 'Agent Runtime 稳定命令 ID，task-management inbox 会按该值再次去重';
COMMENT ON COLUMN agent_async_task_command_outbox.idempotency_key IS '跨服务幂等键，Kafka 重投、dispatcher 重试和人工补偿必须复用相同值';
COMMENT ON COLUMN agent_async_task_command_outbox.command_type IS '命令类型，例如 AGENT_TOOL_ASYNC_TASK_REQUESTED 或受控工具动作命令';
COMMENT ON COLUMN agent_async_task_command_outbox.consumer_service IS '建议消费者服务，通常为 task-management';
COMMENT ON COLUMN agent_async_task_command_outbox.target_endpoint IS '目标端点模板；新受控动作可为空，避免外部输入变成内部任意调用路径';
COMMENT ON COLUMN agent_async_task_command_outbox.payload_reference IS '受控载荷引用，只保存服务端引用，不保存原始工具参数值';
COMMENT ON COLUMN agent_async_task_command_outbox.payload_json IS '待投递命令 envelope JSON 文本，只能保存低敏引用和参数名快照';
COMMENT ON COLUMN agent_async_task_command_outbox.status IS '命令 outbox 投递状态，由 dispatcher 领取、发送、重试、死信或忽略';

CREATE INDEX IF NOT EXISTS idx_agent_async_command_status_retry ON agent_async_task_command_outbox (status, next_retry_at, id);
CREATE INDEX IF NOT EXISTS idx_agent_async_command_run_status ON agent_async_task_command_outbox (run_id, status, id);
CREATE INDEX IF NOT EXISTS idx_agent_async_command_audit ON agent_async_task_command_outbox (audit_id);
CREATE INDEX IF NOT EXISTS idx_agent_async_command_scope_time ON agent_async_task_command_outbox (tenant_id, project_id, workspace_id, update_time);

CREATE TABLE IF NOT EXISTS agent_run_tool_dag_confirmation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confirmation_id VARCHAR(160) NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    selection_fingerprint VARCHAR(160) NOT NULL,
    selected_node_ids TEXT NOT NULL,
    selected_audit_ids TEXT NOT NULL,
    policy_versions TEXT NOT NULL,
    delegation_evidence TEXT NOT NULL,
    bridge_source_evidence TEXT,
    outbox_ids TEXT NOT NULL,
    command_ids TEXT NOT NULL,
    tenant_id BIGINT,
    project_id BIGINT,
    workspace_id BIGINT,
    actor_id VARCHAR(128),
    trace_id VARCHAR(128),
    confirmed BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(32) NOT NULL DEFAULT 'CONFIRMED',
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_dag_confirmation_id UNIQUE (confirmation_id),
    CONSTRAINT ck_agent_dag_confirmation_status CHECK (status IN ('CONFIRMED', 'EXPIRED', 'REVOKED', 'POLICY_CHANGED'))
);

COMMENT ON TABLE agent_run_tool_dag_confirmation IS 'Agent DAG selected-node 确认事实表，解释谁确认了哪版 dry-run 预案以及由此产生了哪些 command';
COMMENT ON COLUMN agent_run_tool_dag_confirmation.confirmation_id IS 'DAG 确认 ID，由 session、run、selectionFingerprint 和 auditId 集合稳定派生';
COMMENT ON COLUMN agent_run_tool_dag_confirmation.selection_fingerprint IS '确认瞬间服务端重新 dry-run 得到的选择指纹，用于证明调用方确认的是哪一版预案';
COMMENT ON COLUMN agent_run_tool_dag_confirmation.selected_node_ids IS '调用方显式选择的 DAG nodeId JSON 文本，只保存节点标识，不保存工具参数';
COMMENT ON COLUMN agent_run_tool_dag_confirmation.selected_audit_ids IS '服务端根据 dry-run 重新提取出的工具审计 ID 白名单，是实际允许入箱的范围';
COMMENT ON COLUMN agent_run_tool_dag_confirmation.policy_versions IS '确认瞬间命中的 permission-admin 策略版本摘要，用于执行前复核策略是否漂移';
COMMENT ON COLUMN agent_run_tool_dag_confirmation.delegation_evidence IS '服务账号委托授权证据摘要 JSON 文本，不保存工具参数或敏感载荷';
COMMENT ON COLUMN agent_run_tool_dag_confirmation.outbox_ids IS '本次确认关联的 command outbox ID 列表，便于从确认事实跳转到投递状态';
COMMENT ON COLUMN agent_run_tool_dag_confirmation.command_ids IS '本次确认关联的跨服务 commandId 列表，便于排查 Kafka、Inbox 和任务创建链路';
COMMENT ON COLUMN agent_run_tool_dag_confirmation.expires_at IS '确认有效期截止时间；过期不删除历史事实，但不应再作为近期执行确认使用';

CREATE INDEX IF NOT EXISTS idx_agent_dag_confirmation_run_time ON agent_run_tool_dag_confirmation (session_id, run_id, create_time);
CREATE INDEX IF NOT EXISTS idx_agent_dag_confirmation_scope_time ON agent_run_tool_dag_confirmation (tenant_id, project_id, workspace_id, create_time);
CREATE INDEX IF NOT EXISTS idx_agent_dag_confirmation_status_expire ON agent_run_tool_dag_confirmation (status, expires_at);

CREATE TABLE IF NOT EXISTS agent_skill_visibility_snapshot_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_key VARCHAR(512) NOT NULL,
    schema_version VARCHAR(80),
    source VARCHAR(128),
    event_type VARCHAR(128) NOT NULL,
    stage VARCHAR(128),
    message VARCHAR(1024),
    severity VARCHAR(32) DEFAULT 'info',
    tenant_id VARCHAR(128),
    project_id VARCHAR(128),
    actor_id VARCHAR(128),
    request_id VARCHAR(128),
    run_id VARCHAR(128),
    session_id VARCHAR(128),
    producer_sequence BIGINT,
    replay_sequence BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    consumed_at TIMESTAMP WITHOUT TIME ZONE,
    snapshot_type VARCHAR(80),
    snapshot_source VARCHAR(128),
    available BOOLEAN NOT NULL DEFAULT FALSE,
    available_skill_count INTEGER NOT NULL DEFAULT 0,
    visible_skill_count INTEGER NOT NULL DEFAULT 0,
    hidden_skill_count INTEGER NOT NULL DEFAULT 0,
    conditional_visible_skill_count INTEGER NOT NULL DEFAULT 0,
    permission_fact_source VARCHAR(80),
    actor_role_source VARCHAR(80),
    actor_role VARCHAR(80),
    granted_permission_count INTEGER NOT NULL DEFAULT 0,
    tenant_skill_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    workspace_risk_level VARCHAR(64),
    tenant_plan_code VARCHAR(80),
    policy_version VARCHAR(128),
    legacy_request_variables_detected BOOLEAN NOT NULL DEFAULT FALSE,
    model_gateway_available BOOLEAN NOT NULL DEFAULT FALSE,
    tool_budget_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    manifest_binding_status VARCHAR(80) DEFAULT 'UNBOUND_UNKNOWN',
    manifest_status VARCHAR(80) DEFAULT 'UNKNOWN',
    manifest_source VARCHAR(128) DEFAULT 'unknown',
    manifest_fingerprint VARCHAR(160),
    manifest_schema_version VARCHAR(80),
    manifest_skill_count INTEGER NOT NULL DEFAULT 0,
    manifest_ready_skill_count INTEGER NOT NULL DEFAULT 0,
    manifest_non_ready_skill_count INTEGER NOT NULL DEFAULT 0,
    manifest_fallback BOOLEAN NOT NULL DEFAULT FALSE,
    visible_skill_codes_json TEXT NOT NULL,
    visible_skill_codes_truncated_count INTEGER NOT NULL DEFAULT 0,
    hidden_skill_codes_json TEXT NOT NULL,
    hidden_skill_codes_truncated_count INTEGER NOT NULL DEFAULT 0,
    visible_risk_level_counts_json TEXT NOT NULL,
    visible_domain_counts_json TEXT NOT NULL,
    hidden_admission_status_counts_json TEXT NOT NULL,
    display_summary VARCHAR(2048),
    recommended_action_count INTEGER NOT NULL DEFAULT 0,
    attributes_json TEXT NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_skill_visibility_identity_key UNIQUE (identity_key),
    CONSTRAINT ck_agent_skill_visibility_counts CHECK (
        available_skill_count >= 0
        AND visible_skill_count >= 0
        AND hidden_skill_count >= 0
        AND conditional_visible_skill_count >= 0
        AND granted_permission_count >= 0
        AND manifest_skill_count >= 0
        AND manifest_ready_skill_count >= 0
        AND manifest_non_ready_skill_count >= 0
        AND visible_skill_codes_truncated_count >= 0
        AND hidden_skill_codes_truncated_count >= 0
        AND recommended_action_count >= 0
    )
);

COMMENT ON TABLE agent_skill_visibility_snapshot_index IS 'Agent Skill 可见性快照索引表，保存低敏聚合事实用于恢复、治理报表、灰度排查和 Marketplace 统计';
COMMENT ON COLUMN agent_skill_visibility_snapshot_index.identity_key IS 'runtime event 幂等键，用唯一约束拦截 Kafka 重复消费和人工补偿重放';
COMMENT ON COLUMN agent_skill_visibility_snapshot_index.request_id IS 'HTTP/Gateway 请求 ID，用于把一次 /agent/plans 请求与快照串联';
COMMENT ON COLUMN agent_skill_visibility_snapshot_index.replay_sequence IS 'Java 控制面写入 projection 后分配的稳定 replay 游标，用于增量查询和断线续传';
COMMENT ON COLUMN agent_skill_visibility_snapshot_index.available IS '本次快照是否成功得到可用 Skill 可见性结果';
COMMENT ON COLUMN agent_skill_visibility_snapshot_index.permission_fact_source IS '权限事实来源，例如 gateway-header、remote-permission-admin、fallback';
COMMENT ON COLUMN agent_skill_visibility_snapshot_index.manifest_fingerprint IS 'Skill Publication Manifest contentFingerprint，用于能力目录版本追踪、灰度、回滚和事故复盘';
COMMENT ON COLUMN agent_skill_visibility_snapshot_index.visible_skill_codes_json IS '可见 Skill code 摘要 JSON 文本，只保存 code，不保存描述、参数、prompt 或策略明细';
COMMENT ON COLUMN agent_skill_visibility_snapshot_index.hidden_skill_codes_json IS '隐藏 Skill code 摘要 JSON 文本，用于治理解释和调试，不是完整权限事实';
COMMENT ON COLUMN agent_skill_visibility_snapshot_index.attributes_json IS '原始低敏 attributes 快照，用于字段演进兼容，禁止写入敏感业务正文';

CREATE INDEX IF NOT EXISTS idx_agent_skill_visibility_run_replay ON agent_skill_visibility_snapshot_index (tenant_id, project_id, run_id, replay_sequence);
CREATE INDEX IF NOT EXISTS idx_agent_skill_visibility_session_replay ON agent_skill_visibility_snapshot_index (tenant_id, project_id, session_id, replay_sequence);
CREATE INDEX IF NOT EXISTS idx_agent_skill_visibility_request ON agent_skill_visibility_snapshot_index (request_id);
CREATE INDEX IF NOT EXISTS idx_agent_skill_visibility_actor_time ON agent_skill_visibility_snapshot_index (tenant_id, project_id, actor_id, create_time);
CREATE INDEX IF NOT EXISTS idx_agent_skill_visibility_manifest ON agent_skill_visibility_snapshot_index (manifest_fingerprint, manifest_binding_status, create_time);
CREATE INDEX IF NOT EXISTS idx_agent_skill_visibility_policy_source ON agent_skill_visibility_snapshot_index (permission_fact_source, policy_version, create_time);
CREATE INDEX IF NOT EXISTS idx_agent_skill_visibility_severity_time ON agent_skill_visibility_snapshot_index (severity, create_time);

CREATE TABLE IF NOT EXISTS agent_tool_action_resume_locator_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkpoint_id VARCHAR(160),
    thread_id VARCHAR(160),
    session_id VARCHAR(128),
    run_id VARCHAR(128),
    command_id VARCHAR(128),
    outbox_id VARCHAR(128),
    approval_fact_id VARCHAR(160),
    clarification_fact_id VARCHAR(160),
    tool_code VARCHAR(160),
    requested_policy_version VARCHAR(160),
    tenant_id VARCHAR(128),
    project_id VARCHAR(128),
    actor_id VARCHAR(128),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_resume_locator_checkpoint UNIQUE (checkpoint_id),
    CONSTRAINT uk_agent_resume_locator_thread UNIQUE (thread_id)
);

COMMENT ON TABLE agent_tool_action_resume_locator_index IS 'checkpoint/thread 到恢复事实定位符的低敏索引，支持暂停、审批、澄清、恢复前置验真';
COMMENT ON COLUMN agent_tool_action_resume_locator_index.checkpoint_id IS 'Python/LangGraph/OpenClaw checkpoint ID；恢复预检优先按该字段精确定位';
COMMENT ON COLUMN agent_tool_action_resume_locator_index.thread_id IS '线程或图运行上下文 ID；checkpointId 缺失时作为兜底恢复入口';
COMMENT ON COLUMN agent_tool_action_resume_locator_index.command_id IS 'Java command outbox 的 commandId，用于串联 task-management inbox 和 worker receipt';
COMMENT ON COLUMN agent_tool_action_resume_locator_index.outbox_id IS 'Java command outbox 的 outboxId，用于服务端精确回查 outbox 状态，不对外原文回显';
COMMENT ON COLUMN agent_tool_action_resume_locator_index.approval_fact_id IS 'permission-admin 审批事实 ID，只供服务端回查审批状态，不对外原文回显';
COMMENT ON COLUMN agent_tool_action_resume_locator_index.clarification_fact_id IS 'Human-in-the-loop 澄清事实 ID，只供服务端验真，不保存澄清正文';
COMMENT ON COLUMN agent_tool_action_resume_locator_index.requested_policy_version IS '恢复预检请求时观察到的策略版本，用于识别恢复时策略漂移';
COMMENT ON COLUMN agent_tool_action_resume_locator_index.tenant_id IS '租户边界快照，locator 命中后仍必须与访问上下文求交集';
COMMENT ON COLUMN agent_tool_action_resume_locator_index.updated_at IS '业务层最近一次观察或合并 locator 的时间，用于 TTL、清理和排序';

CREATE INDEX IF NOT EXISTS idx_agent_resume_locator_scope_run ON agent_tool_action_resume_locator_index (tenant_id, project_id, run_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_agent_resume_locator_scope_tool ON agent_tool_action_resume_locator_index (tenant_id, project_id, tool_code, updated_at);
CREATE INDEX IF NOT EXISTS idx_agent_resume_locator_command ON agent_tool_action_resume_locator_index (command_id);
CREATE INDEX IF NOT EXISTS idx_agent_resume_locator_outbox ON agent_tool_action_resume_locator_index (outbox_id);
CREATE INDEX IF NOT EXISTS idx_agent_resume_locator_approval ON agent_tool_action_resume_locator_index (approval_fact_id);
CREATE INDEX IF NOT EXISTS idx_agent_resume_locator_updated_at ON agent_tool_action_resume_locator_index (updated_at);

CREATE TABLE IF NOT EXISTS agent_tool_action_clarification_fact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clarification_fact_id VARCHAR(180) NOT NULL,
    session_id VARCHAR(180),
    run_id VARCHAR(180),
    command_id VARCHAR(180),
    tool_code VARCHAR(180),
    requested_policy_version VARCHAR(180),
    tenant_id VARCHAR(80) NOT NULL,
    project_id VARCHAR(80) NOT NULL,
    actor_id VARCHAR(120) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'AVAILABLE',
    evidence_codes_json TEXT NOT NULL,
    issue_codes_json TEXT NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_clarification_fact_id UNIQUE (clarification_fact_id),
    CONSTRAINT ck_agent_clarification_fact_status CHECK (status IN ('AVAILABLE', 'REVOKED', 'REJECTED'))
);

COMMENT ON TABLE agent_tool_action_clarification_fact IS 'Human-in-the-loop 澄清事实表，保存 pause -> clarify -> resume 链路中的低敏服务端事实';
COMMENT ON COLUMN agent_tool_action_clarification_fact.clarification_fact_id IS '澄清事实 ID；恢复预检按该字段回查服务端事实';
COMMENT ON COLUMN agent_tool_action_clarification_fact.command_id IS '受控工具动作 commandId；为空表示澄清发生在 command 生成前';
COMMENT ON COLUMN agent_tool_action_clarification_fact.requested_policy_version IS '工具治理策略版本，用于恢复预检识别策略漂移';
COMMENT ON COLUMN agent_tool_action_clarification_fact.evidence_codes_json IS '低敏证据码 JSON 文本，不包含用户澄清正文';
COMMENT ON COLUMN agent_tool_action_clarification_fact.issue_codes_json IS '低敏问题码 JSON 文本，不包含 prompt、SQL、payload 或工具参数';
COMMENT ON COLUMN agent_tool_action_clarification_fact.expires_at IS '事实过期时间；过期后恢复预检必须按不可采信处理';

CREATE INDEX IF NOT EXISTS idx_agent_clarification_fact_scope ON agent_tool_action_clarification_fact (tenant_id, project_id, actor_id, run_id, session_id, command_id, tool_code);
CREATE INDEX IF NOT EXISTS idx_agent_clarification_fact_status_expire ON agent_tool_action_clarification_fact (status, expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_clarification_fact_run ON agent_tool_action_clarification_fact (run_id, session_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_agent_clarification_fact_update_time ON agent_tool_action_clarification_fact (update_time);

CREATE TABLE IF NOT EXISTS agent_tool_action_worker_receipt_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_identity_key VARCHAR(240) NOT NULL,
    command_id VARCHAR(180) NOT NULL,
    tenant_id VARCHAR(80),
    project_id VARCHAR(80),
    actor_id VARCHAR(120),
    run_id VARCHAR(180),
    session_id VARCHAR(180),
    tool_code VARCHAR(180),
    task_status VARCHAR(80),
    outcome VARCHAR(120),
    pre_check_passed BOOLEAN NOT NULL DEFAULT FALSE,
    side_effect_executed BOOLEAN NOT NULL DEFAULT FALSE,
    error_code VARCHAR(160),
    replay_sequence BIGINT,
    consumed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    indexed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_worker_receipt_identity UNIQUE (event_identity_key)
);

COMMENT ON TABLE agent_tool_action_worker_receipt_index IS 'worker/dry-run receipt 低敏索引表，用于恢复事实包按 commandId 快速验真 worker 是否处理过该命令';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.event_identity_key IS 'runtime event projection 的低敏 identityKey，用于 worker receipt 幂等物化';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.command_id IS 'Java command outbox 的 commandId，恢复事实包按该字段查询 worker/dry-run receipt';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.tool_code IS '低敏工具编码，只用于工具目录校验，不保存工具参数或目标 endpoint';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.task_status IS 'task-management 任务状态摘要，例如 RUNNING、FAILED，仅用于状态解释和排障';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.outcome IS 'dry-run/worker 结果摘要，例如 DRY_RUN_PASSED、FAILED_PRECHECK，不保存人类 message';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.pre_check_passed IS '执行前复核是否通过；false 可能代表阻断、等待条件或失败预检';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.side_effect_executed IS '是否已经越过真实副作用边界；dry-run receipt 必须保持 false';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.replay_sequence IS 'Java runtime event projection 分配的回放游标，用于判断最新 receipt';

CREATE INDEX IF NOT EXISTS idx_agent_worker_receipt_command_scope ON agent_tool_action_worker_receipt_index (command_id, tenant_id, project_id, run_id, session_id, replay_sequence);
CREATE INDEX IF NOT EXISTS idx_agent_worker_receipt_scope_time ON agent_tool_action_worker_receipt_index (tenant_id, project_id, consumed_at);
CREATE INDEX IF NOT EXISTS idx_agent_worker_receipt_run ON agent_tool_action_worker_receipt_index (run_id, session_id, replay_sequence);
CREATE INDEX IF NOT EXISTS idx_agent_worker_receipt_tool_time ON agent_tool_action_worker_receipt_index (tenant_id, project_id, tool_code, consumed_at);
CREATE INDEX IF NOT EXISTS idx_agent_worker_receipt_update_time ON agent_tool_action_worker_receipt_index (update_time);

CREATE TABLE IF NOT EXISTS agent_command_worker_lease (
    lease_identity_key VARCHAR(260) PRIMARY KEY,
    session_id VARCHAR(180) NOT NULL,
    run_id VARCHAR(180) NOT NULL,
    command_id VARCHAR(180) NOT NULL,
    executor_id VARCHAR(160) NOT NULL,
    tenant_id VARCHAR(80),
    project_id VARCHAR(80),
    actor_id VARCHAR(120),
    fencing_token VARCHAR(128) NOT NULL,
    lease_version BIGINT NOT NULL,
    lease_expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    acquired_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_command_worker_lease_command UNIQUE (session_id, run_id, command_id),
    CONSTRAINT ck_agent_command_worker_lease_version CHECK (lease_version >= 0)
);

COMMENT ON TABLE agent_command_worker_lease IS 'Agent command worker lease 当前事实表，用 fencing token 约束哪个 worker 有资格处理某个 command';
COMMENT ON COLUMN agent_command_worker_lease.lease_identity_key IS 'sessionId/runId/commandId 拼出的稳定唯一键，是领取与回执校验的主定位符';
COMMENT ON COLUMN agent_command_worker_lease.command_id IS 'command outbox 指令 ID；一个 command 同一时刻最多只能有一个有效 worker lease';
COMMENT ON COLUMN agent_command_worker_lease.executor_id IS '当前持有 lease 的 worker 低敏身份，例如 agent-command-worker-01';
COMMENT ON COLUMN agent_command_worker_lease.fencing_token IS '内部 fencing token，只能用于 claim 响应和 receipt 校验，禁止投影到事件、日志或前端';
COMMENT ON COLUMN agent_command_worker_lease.lease_version IS '单调递增版本；过期后重新领取必须递增，旧 worker 的 token/version 会被拒绝';
COMMENT ON COLUMN agent_command_worker_lease.lease_expires_at IS '租约过期时间；worker 超过该时间写回 receipt 会被拒绝';

CREATE INDEX IF NOT EXISTS idx_agent_command_worker_lease_scope ON agent_command_worker_lease (tenant_id, project_id, actor_id, run_id, session_id);
CREATE INDEX IF NOT EXISTS idx_agent_command_worker_lease_expiry ON agent_command_worker_lease (lease_expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_command_worker_lease_executor ON agent_command_worker_lease (executor_id, lease_expires_at);

CREATE TABLE IF NOT EXISTS agent_artifact_body_read_grant_fact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_decision_reference VARCHAR(240) NOT NULL,
    command_id VARCHAR(180),
    artifact_reference VARCHAR(500),
    artifact_reference_type VARCHAR(80),
    read_purpose VARCHAR(120),
    requested_content_mode VARCHAR(120),
    max_readable_bytes INTEGER,
    tenant_id VARCHAR(80),
    project_id VARCHAR(80),
    actor_id VARCHAR(120),
    run_id VARCHAR(180),
    session_id VARCHAR(180),
    tool_code VARCHAR(180),
    matched_receipt_fingerprint VARCHAR(160),
    replay_sequence BIGINT,
    receipt_outcome VARCHAR(120),
    issued_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(40) NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    revoked_by VARCHAR(120),
    revoke_reason_code VARCHAR(120),
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_aabr_grant_reference UNIQUE (grant_decision_reference),
    CONSTRAINT ck_aabr_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'REVOKED')),
    CONSTRAINT ck_aabr_max_readable_bytes CHECK (max_readable_bytes IS NULL OR max_readable_bytes >= 0)
);

COMMENT ON TABLE agent_artifact_body_read_grant_fact IS 'Agent artifact 正文读取授权低敏事实表，支撑 final-check、object-store probe、管理员撤销和审计排障';
COMMENT ON COLUMN agent_artifact_body_read_grant_fact.grant_decision_reference IS '低敏 grant 决策引用，唯一键；它不是 bearer token，不能直接作为下载凭证';
COMMENT ON COLUMN agent_artifact_body_read_grant_fact.artifact_reference IS '低敏 artifact 引用，不是 bucket/key、真实路径或下载地址';
COMMENT ON COLUMN agent_artifact_body_read_grant_fact.read_purpose IS '正文读取目的，例如 TASK_RESULT_VIEW、AUDIT_REVIEW';
COMMENT ON COLUMN agent_artifact_body_read_grant_fact.requested_content_mode IS '请求读取形态，例如 SAFE_RENDERED_PREVIEW 或受控对象存储读取';
COMMENT ON COLUMN agent_artifact_body_read_grant_fact.max_readable_bytes IS '本次 grant 允许读取的最大字节数；下游仍需二次裁剪';
COMMENT ON COLUMN agent_artifact_body_read_grant_fact.matched_receipt_fingerprint IS 'worker receipt 低敏摘要指纹，不包含 receipt 原文';
COMMENT ON COLUMN agent_artifact_body_read_grant_fact.status IS 'grant fact 状态：ACTIVE、EXPIRED、REVOKED';
COMMENT ON COLUMN agent_artifact_body_read_grant_fact.revoked_by IS '执行撤销的低敏操作者标识，来自可信 Header 或服务账号';

CREATE INDEX IF NOT EXISTS idx_aabr_command_scope ON agent_artifact_body_read_grant_fact (command_id, tenant_id, project_id, run_id, session_id, issued_at);
CREATE INDEX IF NOT EXISTS idx_aabr_scope_status ON agent_artifact_body_read_grant_fact (tenant_id, project_id, status, issued_at);
CREATE INDEX IF NOT EXISTS idx_aabr_artifact_ref ON agent_artifact_body_read_grant_fact (artifact_reference, tenant_id, project_id);
CREATE INDEX IF NOT EXISTS idx_aabr_expiry_status ON agent_artifact_body_read_grant_fact (status, expires_at);
CREATE INDEX IF NOT EXISTS idx_aabr_update_time ON agent_artifact_body_read_grant_fact (update_time);

CREATE TABLE IF NOT EXISTS agent_tool_action_submission_fact (
    submission_identity_key VARCHAR(220) PRIMARY KEY,
    command_id VARCHAR(180) NOT NULL,
    idempotency_key VARCHAR(180),
    session_id VARCHAR(180),
    run_id VARCHAR(180),
    audit_id VARCHAR(200),
    tool_code VARCHAR(180),
    tenant_id VARCHAR(80),
    project_id VARCHAR(80),
    actor_id VARCHAR(120),
    payload_reference VARCHAR(260),
    confirmation_id VARCHAR(220),
    policy_version VARCHAR(120),
    target_service VARCHAR(120),
    target_endpoint VARCHAR(180),
    status VARCHAR(40) NOT NULL,
    side_effect_started BOOLEAN NOT NULL DEFAULT FALSE,
    side_effect_executed BOOLEAN NOT NULL DEFAULT FALSE,
    outcome VARCHAR(120),
    downstream_task_id BIGINT,
    downstream_task_status VARCHAR(80),
    error_code VARCHAR(160),
    issue_codes VARCHAR(900),
    recommended_actions VARCHAR(1000),
    low_sensitive_message VARCHAR(300),
    first_submitted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_tool_action_submission_command UNIQUE (command_id),
    CONSTRAINT ck_agent_tool_action_submission_status CHECK (status IN ('SUBMITTING', 'SUBMITTED', 'REJECTED', 'UNKNOWN'))
);

COMMENT ON TABLE agent_tool_action_submission_fact IS 'Agent 受控工具真实提交低敏事实表，用于防止 command replay 重复触发下游副作用';
COMMENT ON COLUMN agent_tool_action_submission_fact.submission_identity_key IS '受控工具提交事实唯一键，当前默认为 tool-action-submission:{commandId}';
COMMENT ON COLUMN agent_tool_action_submission_fact.command_id IS 'command outbox ID，是防重复提交的核心业务幂等键';
COMMENT ON COLUMN agent_tool_action_submission_fact.idempotency_key IS 'worker 或 command 侧幂等键；为空时服务端可回退 command_id';
COMMENT ON COLUMN agent_tool_action_submission_fact.payload_reference IS '服务端 payload 引用，不保存正文，读取时仍需重新校验租户、项目、run、tool、policy 和 TTL';
COMMENT ON COLUMN agent_tool_action_submission_fact.confirmation_id IS '审批确认事实 ID，用于证明真实副作用调用前已经获得确认';
COMMENT ON COLUMN agent_tool_action_submission_fact.status IS '提交状态；SUBMITTING/UNKNOWN 都不能盲目重放下游副作用';
COMMENT ON COLUMN agent_tool_action_submission_fact.side_effect_started IS '是否已经开始真实副作用调用，true 后重放必须先对账下游';
COMMENT ON COLUMN agent_tool_action_submission_fact.side_effect_executed IS '是否已确认副作用成功落地，可用 downstream_task_id 对账';
COMMENT ON COLUMN agent_tool_action_submission_fact.low_sensitive_message IS '低敏消息摘要，禁止保存下游 payloadPreview、样本、SQL、prompt 或模型输出';

CREATE INDEX IF NOT EXISTS idx_agent_tool_action_submission_idempotency ON agent_tool_action_submission_fact (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_agent_tool_action_submission_scope ON agent_tool_action_submission_fact (tenant_id, project_id, actor_id, run_id, session_id);
CREATE INDEX IF NOT EXISTS idx_agent_tool_action_submission_status ON agent_tool_action_submission_fact (status, last_updated_at);
CREATE INDEX IF NOT EXISTS idx_agent_tool_action_submission_downstream ON agent_tool_action_submission_fact (downstream_task_id);
