SET search_path TO agent_runtime, public;

CREATE TABLE IF NOT EXISTS agent_tool_execution_output (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id VARCHAR(128) NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    tool_code VARCHAR(128) NOT NULL,
    output_json JSONB NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_agent_tool_execution_output_audit_id UNIQUE (audit_id)
);

COMMENT ON TABLE agent_tool_execution_output IS
    'Durable structured tool outputs used by explicitly audited same-session Agent loop references.';
COMMENT ON COLUMN agent_tool_execution_output.output_json IS
    'Governed structured output only; raw credentials, prompts, stdout/stderr and hidden reasoning are forbidden.';

CREATE INDEX IF NOT EXISTS idx_agent_tool_execution_output_session_run
    ON agent_tool_execution_output (session_id, run_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_agent_tool_execution_output_session_tool
    ON agent_tool_execution_output (session_id, tool_code, create_time DESC);
