-- Agent command 最终态 callback worker 持久状态。
-- Java receipt index 始终是事实源；本迁移只保存低敏收敛状态、visibility lease、重试/死信和不可变历史，
-- 禁止保存命令正文、stdout/stderr、payload、prompt、凭据或内部下游地址。

ALTER TABLE agent_tool_action_worker_receipt_index
    ADD COLUMN IF NOT EXISTS task_id BIGINT,
    ADD COLUMN IF NOT EXISTS task_run_id BIGINT,
    ADD COLUMN IF NOT EXISTS executor_id VARCHAR(160),
    ADD COLUMN IF NOT EXISTS audit_id VARCHAR(200);

COMMENT ON COLUMN agent_tool_action_worker_receipt_index.task_id IS 'task-management 任务低敏关联 ID；自动 callback 不会根据 commandId 猜测该值';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.task_run_id IS 'task-management 任务运行低敏关联 ID，用于下游 lease/idempotency 校验';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.executor_id IS 'worker 低敏执行器编码；不保存主机地址、容器 ID 或内部 endpoint';
COMMENT ON COLUMN agent_tool_action_worker_receipt_index.audit_id IS 'Agent 工具审计低敏关联 ID，支撑最终态补偿与审计关联';

CREATE INDEX IF NOT EXISTS idx_agent_worker_receipt_final_callback_candidate
    ON agent_tool_action_worker_receipt_index (outcome, replay_sequence, consumed_at, id);

CREATE TABLE IF NOT EXISTS agent_command_task_final_callback_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(96) NOT NULL,
    source_receipt_identity_key VARCHAR(240) NOT NULL,
    source_replay_sequence BIGINT,
    command_id VARCHAR(180) NOT NULL,
    task_id BIGINT,
    task_run_id BIGINT,
    executor_id VARCHAR(160),
    audit_id VARCHAR(200),
    tenant_id VARCHAR(80),
    project_id VARCHAR(80),
    actor_id VARCHAR(120),
    run_id VARCHAR(180),
    session_id VARCHAR(180),
    tool_code VARCHAR(180),
    callback_status VARCHAR(32) NOT NULL,
    callback_idempotency_key VARCHAR(255) NOT NULL,
    requires_manual_compensation BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE,
    lease_owner VARCHAR(160),
    lease_token VARCHAR(128),
    lease_expires_at TIMESTAMP WITH TIME ZONE,
    failure_code VARCHAR(160),
    callback_delivered_at TIMESTAMP WITH TIME ZONE,
    create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_final_callback_job_id UNIQUE (job_id),
    CONSTRAINT uk_agent_final_callback_source_receipt UNIQUE (source_receipt_identity_key),
    CONSTRAINT ck_agent_final_callback_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_agent_final_callback_status CHECK (status IN (
        'PENDING', 'DISPATCHING', 'RETRY_WAIT', 'DELIVERED', 'SUPERSEDED', 'COMPENSATION_REQUIRED', 'DEAD_LETTER'
    )),
    CONSTRAINT ck_agent_final_callback_status_contract CHECK (
        callback_status IN ('SUCCEEDED', 'FAILED')
    )
);

COMMENT ON TABLE agent_command_task_final_callback_job IS 'Agent 异步任务最终态 callback durable job；只从 Java worker receipt 事实创建，负责幂等、visibility lease、重试与人工补偿收敛';
COMMENT ON COLUMN agent_command_task_final_callback_job.source_receipt_identity_key IS 'Java receipt 索引的唯一来源键；同源 receipt 只能创建一个 callback job';
COMMENT ON COLUMN agent_command_task_final_callback_job.callback_idempotency_key IS '下游 task-management callback 幂等键；进程崩溃后重试仍使用同一键';
COMMENT ON COLUMN agent_command_task_final_callback_job.lease_token IS '内部 visibility fence token；只用于条件更新，禁止写入日志、事件、指标或外部响应';
COMMENT ON COLUMN agent_command_task_final_callback_job.lease_expires_at IS 'UTC 绝对时刻；所有持有者写入都必须同时满足 owner、token 与尚未过期三个条件';
COMMENT ON COLUMN agent_command_task_final_callback_job.failure_code IS '低敏失败机器码；完整下游响应和异常堆栈只进入受控日志平台';

CREATE INDEX IF NOT EXISTS idx_agent_final_callback_job_due
    ON agent_command_task_final_callback_job (status, next_attempt_at, lease_expires_at, id);
CREATE INDEX IF NOT EXISTS idx_agent_final_callback_job_idempotency
    ON agent_command_task_final_callback_job (callback_idempotency_key);
CREATE INDEX IF NOT EXISTS idx_agent_final_callback_job_scope
    ON agent_command_task_final_callback_job (tenant_id, project_id, run_id, session_id, create_time);

CREATE TABLE IF NOT EXISTS agent_command_task_final_callback_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id VARCHAR(96) NOT NULL,
    job_id VARCHAR(96) NOT NULL,
    source_receipt_identity_key VARCHAR(240) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    reason_code VARCHAR(160),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    worker_id VARCHAR(160),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_final_callback_history_id UNIQUE (history_id),
    CONSTRAINT ck_agent_final_callback_history_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_agent_final_callback_history_status CHECK (status IN (
        'PENDING', 'DISPATCHING', 'RETRY_WAIT', 'DELIVERED', 'SUPERSEDED', 'COMPENSATION_REQUIRED', 'DEAD_LETTER'
    ))
);

COMMENT ON TABLE agent_command_task_final_callback_history IS '最终态 callback job 的低敏不可变历史，用于审计领取、heartbeat、退避、死信和补偿原因';
COMMENT ON COLUMN agent_command_task_final_callback_history.reason_code IS '低敏状态变更机器码，不保存命令、payload、下游响应正文或异常堆栈';

CREATE INDEX IF NOT EXISTS idx_agent_final_callback_history_source_time
    ON agent_command_task_final_callback_history (source_receipt_identity_key, occurred_at, id);
