-- ---------------------------------------------------------------------------
-- DataSmart Govern 初始化脚本
-- ---------------------------------------------------------------------------
-- 这份脚本承担两个职责：
-- 1. 初始化本地开发依赖的基础数据库。
-- 2. 初始化当前已落地模块的核心业务表结构。
--
-- 当前阶段仍采用集中式初始化脚本，是为了让学习、调试和环境重建成本更低。
-- 后续如果模块持续增多，可以再逐步演进为 Flyway / Liquibase 这类版本化迁移方案。
-- ---------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS nacos
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON nacos.* TO 'root'@'%' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS datasmart_govern
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE datasmart_govern;

-- ---------------------------------------------------------------------------
-- task-management：任务管理模块
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '任务主键',
    name VARCHAR(255) NOT NULL COMMENT '任务名称',
    description TEXT COMMENT '任务说明，便于运营和学习理解',
    type VARCHAR(50) NOT NULL COMMENT '任务类型，用于分类、路由或策略绑定',
    tenant_id BIGINT COMMENT '任务所属租户 ID，用于多租户数据隔离、租户级队列公平性、租户级 SLA 和审计查询；当前允许为空以兼容早期历史任务',
    owner_id BIGINT COMMENT '任务负责人 ID，用于我的任务、失败通知、责任归属、人工待办和运营排障；服务账号任务可写入规则 owner 或系统账号',
    project_id BIGINT COMMENT '任务所属项目 ID，用于租户内部二级隔离、项目级配额、项目级看板、项目负责人审批和成本审计',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '当前主状态，例如 PENDING、RUNNING、DEFERRED、DEAD_LETTER、SUCCESS、FAILED、CANCELLED',
    params TEXT COMMENT '任务输入参数，通常为 JSON',
    progress INT DEFAULT 0 COMMENT '执行进度百分比，范围 0 到 100',
    checkpoint TEXT COMMENT '断点续跑或重试所需的检查点信息',
    priority VARCHAR(10) DEFAULT 'MEDIUM' COMMENT '调度优先级',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '当前已发生的重试次数',
    max_retry_count INT NOT NULL DEFAULT 3 COMMENT '允许的最大重试次数',
    defer_count INT NOT NULL DEFAULT 0 COMMENT '当前连续延迟回队列次数，用于识别容量背压是否形成无限循环',
    max_defer_count INT NOT NULL DEFAULT 20 COMMENT '允许的最大连续延迟回队列次数，超过后进入 DEAD_LETTER',
    current_execution_run_id BIGINT COMMENT '当前执行记录 ID，用于快速定位正在运行的执行尝试',
    current_executor_id VARCHAR(128) COMMENT '当前认领任务的执行器实例 ID',
    queued_time DATETIME COMMENT '最近一次进入可调度队列的时间，用于计算排队时长',
    heartbeat_time DATETIME COMMENT '最近一次执行器心跳时间',
    lease_expire_time DATETIME COMMENT '当前执行租约过期时间',
    attention_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需要运营人员关注',
    timeout_seconds INT NOT NULL DEFAULT 3600 COMMENT '任务默认执行超时时间，单位秒',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '最后更新时间',
    start_time DATETIME COMMENT '开始执行时间',
    end_time DATETIME COMMENT '执行结束时间',
    result TEXT COMMENT '执行结果或失败摘要',
    INDEX idx_task_status (status),
    INDEX idx_task_type (type),
    INDEX idx_task_tenant_status_time (tenant_id, status, create_time),
    INDEX idx_task_owner_status_time (owner_id, status, create_time),
    INDEX idx_task_project_status_time (project_id, status, create_time),
    INDEX idx_task_create_time (create_time),
    INDEX idx_task_queue_claim (status, queued_time, priority, create_time),
    INDEX idx_task_tenant_queue_claim (tenant_id, status, queued_time, priority, create_time),
    INDEX idx_task_executor_lease (current_executor_id, lease_expire_time),
    INDEX idx_task_attention (attention_required, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务聚合主表';

CREATE TABLE IF NOT EXISTS task_draft (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '任务草稿主键；草稿不进入执行器认领队列',
    name VARCHAR(255) NOT NULL COMMENT '草稿名称，转换真实任务时通常作为 task.name',
    description TEXT COMMENT '草稿说明，描述目标、风险、审批依据和执行建议',
    type VARCHAR(50) NOT NULL COMMENT '目标任务类型，例如 DATA_QUALITY_SCAN、DATA_SYNC、MANUAL_REVIEW',
    tenant_id BIGINT COMMENT '草稿所属租户 ID，用于多租户隔离和审批范围收口',
    owner_id BIGINT COMMENT '草稿负责人 ID，转换真实任务时默认写入 task.owner_id',
    project_id BIGINT COMMENT '草稿所属项目 ID，用于 PROJECT 数据范围、项目审批和项目级队列治理',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '草稿状态：DRAFT、PENDING_APPROVAL、APPROVED、CONVERTING、REJECTED、CONVERTED；CONVERTING 用于并发转换门闩',
    params TEXT COMMENT '草稿参数 JSON；转换真实任务前仍需按任务类型做 schema 校验',
    priority VARCHAR(10) DEFAULT 'MEDIUM' COMMENT '建议任务优先级，转换时写入 task.priority',
    max_retry_count INT NOT NULL DEFAULT 3 COMMENT '建议最大重试次数，转换时写入 task.max_retry_count',
    max_defer_count INT NOT NULL DEFAULT 20 COMMENT '建议最大连续延迟次数，转换时写入 task.max_defer_count',
    source_type VARCHAR(32) DEFAULT 'MANUAL' COMMENT '草稿来源类型，例如 AGENT、TEMPLATE、MANUAL、API',
    source_ref VARCHAR(255) COMMENT '来源引用，例如 Agent auditId、任务模板 ID 或外部工单号',
    created_by BIGINT COMMENT '创建人 ID',
    submitted_by BIGINT COMMENT '提交审批人 ID',
    approved_by BIGINT COMMENT '审批人 ID',
    approval_comment TEXT COMMENT '提交、审批或拒绝说明',
    converted_task_id BIGINT COMMENT '转换得到的真实任务 ID；为空表示尚未转换',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '最后更新时间',
    submit_time DATETIME COMMENT '提交审批时间',
    approval_time DATETIME COMMENT '审批时间',
    convert_time DATETIME COMMENT '转换真实任务时间',
    INDEX idx_task_draft_status_time (status, create_time),
    INDEX idx_task_draft_tenant_status_time (tenant_id, status, create_time),
    INDEX idx_task_draft_project_status_time (project_id, status, create_time),
    INDEX idx_task_draft_owner_status_time (owner_id, status, create_time),
    INDEX idx_task_draft_source (source_type, source_ref),
    INDEX idx_task_draft_converted_task (converted_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务草稿表；用于 Agent/模板/人工配置生成待审批任务';

CREATE TABLE IF NOT EXISTS task_execution_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '日志主键',
    task_id BIGINT NOT NULL COMMENT '关联任务 ID',
    action VARCHAR(32) NOT NULL COMMENT '执行动作，例如 CREATE、RETRY',
    from_status VARCHAR(20) COMMENT '变更前状态',
    to_status VARCHAR(20) COMMENT '变更后状态',
    message VARCHAR(255) NOT NULL COMMENT '面向运营的摘要说明',
    operator VARCHAR(64) DEFAULT 'system' COMMENT '操作者或动作来源',
    details TEXT COMMENT '详细上下文信息',
    create_time DATETIME NOT NULL COMMENT '日志创建时间',
    INDEX idx_task_execution_log_task_time (task_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务执行日志表';

CREATE TABLE IF NOT EXISTS task_execution_run (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '执行记录主键',
    task_id BIGINT NOT NULL COMMENT '关联任务 ID',
    run_no BIGINT NOT NULL COMMENT '同一任务下的第几次执行',
    executor_id VARCHAR(128) NOT NULL COMMENT '执行器实例 ID，例如 worker、Pod 或 Agent Runtime 实例',
    state VARCHAR(32) NOT NULL COMMENT '执行状态，例如 RUNNING、SUCCESS、FAILED、DEFERRED、TIMEOUT、CANCELLED',
    trigger_type VARCHAR(64) NOT NULL COMMENT '触发类型，例如 EXECUTOR_CLAIM、MANUAL_RETRY、SCHEDULED',
    triggered_by BIGINT COMMENT '触发人或触发主体 ID',
    started_at DATETIME NOT NULL COMMENT '开始执行时间',
    finished_at DATETIME COMMENT '结束时间',
    heartbeat_at DATETIME COMMENT '最近一次心跳时间',
    lease_expire_time DATETIME COMMENT '执行租约过期时间',
    progress INT DEFAULT 0 COMMENT '本次执行进度',
    checkpoint TEXT COMMENT '本次执行最近检查点',
    error_message TEXT COMMENT '失败、超时或取消原因',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_task_execution_run_no (task_id, run_no),
    INDEX idx_task_execution_run_state_lease (state, lease_expire_time),
    INDEX idx_task_execution_run_executor (executor_id, state, lease_expire_time),
    INDEX idx_task_execution_run_task_time (task_id, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务执行尝试记录表';

CREATE TABLE IF NOT EXISTS task_callback_idempotency (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '执行器回调幂等记录主键，仅用于内部更新和排障定位',
    task_id BIGINT NOT NULL COMMENT '关联任务 ID；幂等必须绑定具体任务，避免不同任务的相同幂等键互相影响',
    action VARCHAR(32) NOT NULL COMMENT '回调动作编码，例如 PROGRESS、COMPLETE、FAIL、DEFER；动作参与唯一键以区分同一 run 下的不同行为',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '调用方生成的幂等键；同一次业务动作重试必须复用同一个键，新 run 或新动作必须换新键',
    run_id BIGINT NOT NULL COMMENT '回调所属执行 run ID，用于审计并与 task.current_execution_run_id 做一致性校验',
    executor_id VARCHAR(128) NOT NULL COMMENT '发起回调的执行器实例 ID，用于审计并与 task.current_executor_id 做租约一致性校验',
    request_digest VARCHAR(1000) COMMENT '请求摘要；保存排障所需的短文本，不保存完整大结果或敏感参数',
    callback_state VARCHAR(32) NOT NULL COMMENT '幂等处理状态：PROCESSING 表示处理中，SUCCEEDED 表示已成功落地，FAILED 为后续失败审计预留',
    response_summary VARCHAR(1000) COMMENT '首次成功处理后的响应或业务结果摘要，便于重复请求复用首次处理语义',
    error_message VARCHAR(1000) COMMENT '失败摘要；当前事务模型下失败通常回滚，该字段为后续独立失败审计预留',
    first_seen_time DATETIME NOT NULL COMMENT '首次看到该幂等键的时间，用于定位首个请求和后续保留策略',
    last_seen_time DATETIME NOT NULL COMMENT '最近一次看到该幂等键的时间；重复回调只刷新该字段，不再推进任务状态',
    create_time DATETIME NOT NULL COMMENT '记录创建时间',
    update_time DATETIME NOT NULL COMMENT '记录更新时间',
    UNIQUE KEY uk_task_callback_idempotency (task_id, action, idempotency_key),
    INDEX idx_task_callback_run_action (run_id, action),
    INDEX idx_task_callback_executor_time (executor_id, last_seen_time),
    INDEX idx_task_callback_state_time (callback_state, last_seen_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务执行器回调幂等记录表';

CREATE TABLE IF NOT EXISTS agent_async_task_command_inbox (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Agent 异步工具命令 Inbox 主键，仅用于表内更新和运维定位',
    command_id VARCHAR(128) NOT NULL COMMENT 'Agent Runtime 稳定生成的命令 ID；同一 session/run/audit 多次规划必须一致',
    idempotency_key VARCHAR(255) NOT NULL COMMENT '跨服务幂等键；Kafka 重投、消费者重启和人工重放必须复用相同值',
    schema_version VARCHAR(80) NOT NULL COMMENT '命令协议版本；消费侧只接受显式支持版本，避免升级后静默误执行',
    command_type VARCHAR(80) NOT NULL COMMENT '命令类型，例如 AGENT_TOOL_ASYNC_TASK_REQUESTED',
    audit_id VARCHAR(128) NOT NULL COMMENT 'Agent 工具执行审计 ID；用于回查参数快照和回写工具状态',
    session_id VARCHAR(128) NOT NULL COMMENT 'Agent 会话 ID',
    run_id VARCHAR(128) NOT NULL COMMENT 'Agent Run ID',
    tool_code VARCHAR(128) NOT NULL COMMENT '工具编码，例如 data-sync.execute、quality.scan.start',
    target_service VARCHAR(128) NOT NULL COMMENT '工具最终面向的业务模块',
    target_endpoint VARCHAR(300) NOT NULL COMMENT '工具目录声明的目标端点模板',
    tenant_id BIGINT NOT NULL COMMENT '租户隔离边界；异步自动化动作禁止缺失',
    project_id BIGINT NOT NULL COMMENT '项目隔离边界；用于项目级队列、公平性、权限和成本归集',
    workspace_id BIGINT NOT NULL COMMENT 'Agent 工作空间隔离边界；用于产物和载荷解析',
    actor_id VARCHAR(128) NOT NULL COMMENT '原始发起者，可以是用户、服务账号或 Agent 身份',
    trace_id VARCHAR(128) NOT NULL COMMENT '全链路追踪 ID',
    payload_reference VARCHAR(512) NOT NULL COMMENT '受控载荷引用；只允许保存安全引用，不保存原始工具参数值',
    argument_names JSON NOT NULL COMMENT '参数名 JSON 快照，不包含参数值',
    sensitive_argument_names JSON NOT NULL COMMENT '敏感参数名 JSON 快照，用于执行前脱敏、审批和审计复核',
    consume_state VARCHAR(32) NOT NULL COMMENT 'Inbox 消费状态：PROCESSING、TASK_CREATED',
    task_id BIGINT COMMENT '命令成功转换得到的 task.id',
    first_seen_time DATETIME NOT NULL COMMENT '首次收到命令时间',
    last_seen_time DATETIME NOT NULL COMMENT '最近收到命令时间；重复投递只刷新该字段',
    create_time DATETIME NOT NULL COMMENT '记录创建时间',
    update_time DATETIME NOT NULL COMMENT '记录更新时间',
    UNIQUE KEY uk_agent_async_task_command_id (command_id),
    UNIQUE KEY uk_agent_async_task_idempotency_key (idempotency_key),
    INDEX idx_agent_async_task_audit (audit_id),
    INDEX idx_agent_async_task_run (session_id, run_id, consume_state),
    INDEX idx_agent_async_task_scope_state (tenant_id, project_id, workspace_id, consume_state, update_time),
    INDEX idx_agent_async_task_task (task_id),
    INDEX idx_agent_async_task_state_time (consume_state, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 异步工具命令消费 Inbox；用于跨服务去重和任务创建回执';

CREATE TABLE IF NOT EXISTS agent_async_task_command_outbox (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键，仅用于表内排序和运维定位',
    outbox_id VARCHAR(300) NOT NULL COMMENT 'outbox 记录唯一 ID，建议由 command_id 派生',
    command_id VARCHAR(128) NOT NULL COMMENT 'Agent Runtime 稳定生成的命令 ID',
    idempotency_key VARCHAR(255) NOT NULL COMMENT '跨服务幂等键，task-management Inbox 会再次据此去重',
    schema_version VARCHAR(80) NOT NULL COMMENT '命令协议版本',
    command_type VARCHAR(80) NOT NULL COMMENT '命令类型，例如 AGENT_TOOL_ASYNC_TASK_REQUESTED',
    partition_key VARCHAR(160) DEFAULT NULL COMMENT '建议投递分区键，通常为 run_id',
    command_topic VARCHAR(160) DEFAULT NULL COMMENT '建议 Kafka topic',
    consumer_service VARCHAR(128) DEFAULT NULL COMMENT '建议消费者服务，默认 task-management',
    session_id VARCHAR(128) NOT NULL COMMENT 'Agent 会话 ID',
    run_id VARCHAR(128) NOT NULL COMMENT 'Agent Run ID',
    audit_id VARCHAR(128) NOT NULL COMMENT '工具执行审计 ID',
    tool_code VARCHAR(128) NOT NULL COMMENT '工具编码',
    target_service VARCHAR(128) NOT NULL COMMENT '工具最终目标服务',
    target_endpoint VARCHAR(300) NOT NULL COMMENT '目标端点模板',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户边界',
    project_id BIGINT DEFAULT NULL COMMENT '项目边界',
    workspace_id BIGINT DEFAULT NULL COMMENT '工作空间边界',
    actor_id VARCHAR(128) DEFAULT NULL COMMENT '原始发起者',
    trace_id VARCHAR(128) DEFAULT NULL COMMENT '链路追踪 ID',
    payload_reference VARCHAR(512) NOT NULL COMMENT '受控载荷引用，例如 agent-tool-audit://session/run/audit/plan-arguments',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '投递状态：PENDING/PUBLISHING/PUBLISHED/FAILED/BLOCKED/IGNORED',
    attempt_count INT NOT NULL DEFAULT 0 COMMENT '投递尝试次数',
    payload_json JSON NOT NULL COMMENT '待投递命令 envelope；不应包含原始敏感参数值',
    payload_size_bytes INT NOT NULL DEFAULT 0 COMMENT 'payload UTF-8 字节数',
    payload_truncated TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'payload 是否因超过安全上限被阻断或截断',
    next_retry_at DATETIME(3) DEFAULT NULL COMMENT '下一次允许重试时间',
    published_at DATETIME(3) DEFAULT NULL COMMENT '投递成功时间',
    last_error VARCHAR(1024) DEFAULT NULL COMMENT '最近一次失败或阻断原因',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'outbox 记录创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'outbox 记录更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_async_command_outbox_id (outbox_id),
    UNIQUE KEY uk_agent_async_command_id (command_id),
    UNIQUE KEY uk_agent_async_command_idempotency_key (idempotency_key),
    KEY idx_agent_async_command_status_retry (status, next_retry_at, id),
    KEY idx_agent_async_command_run_status (run_id, status, id),
    KEY idx_agent_async_command_audit (audit_id),
    KEY idx_agent_async_command_scope_time (tenant_id, project_id, workspace_id, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='agent-runtime ASYNC_TASK 命令 outbox 表';

CREATE TABLE IF NOT EXISTS agent_run_tool_dag_confirmation (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键，仅用于表内排序和运维定位',
    confirmation_id VARCHAR(160) NOT NULL COMMENT 'DAG selected-node 确认 ID，由 session_id、run_id、selection_fingerprint 和 auditId 集合稳定派生',
    session_id VARCHAR(128) NOT NULL COMMENT 'Agent 会话 ID，用于防止跨会话确认和审计聚合',
    run_id VARCHAR(128) NOT NULL COMMENT 'Agent Run ID，用于把确认记录挂到一次编排执行上下文',
    selection_fingerprint VARCHAR(160) NOT NULL COMMENT '确认瞬间服务端重新 dry-run 得到的选择指纹，用于证明调用方确认的是哪一版预案',
    selected_node_ids JSON NOT NULL COMMENT '调用方显式选择的 DAG nodeId 列表，仅保存节点标识，不保存工具参数',
    selected_audit_ids JSON NOT NULL COMMENT '服务端根据 dry-run 重新提取出的工具审计 ID 白名单，是实际允许入箱的范围',
    policy_versions JSON NOT NULL COMMENT '确认瞬间命中的 permission-admin 策略版本列表，用于执行前复核策略是否漂移',
    delegation_evidence JSON NOT NULL COMMENT '服务账号委托授权证据摘要列表，不保存工具参数或敏感载荷',
    bridge_source_evidence JSON DEFAULT NULL COMMENT 'handoff DAG bridge preview 来源证据摘要；只保存 sourceType、bridgeAction、fingerprint、节点 ID 和 traceId，不保存 prompt、SQL、工具参数或完整模板',
    outbox_ids JSON NOT NULL COMMENT '本次确认关联的 command outbox 记录 ID 列表，便于从确认事实跳转到投递状态',
    command_ids JSON NOT NULL COMMENT '本次确认关联的跨服务 commandId 列表，便于排查 Kafka、task-management Inbox 和任务创建链路',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户边界快照，用于审计查询、配额治理和多租户隔离',
    project_id BIGINT DEFAULT NULL COMMENT '项目边界快照，用于项目级审计、审批和成本归集',
    workspace_id BIGINT DEFAULT NULL COMMENT '工作空间边界快照，用于 Agent workspace 隔离与载荷解析',
    actor_id VARCHAR(128) DEFAULT NULL COMMENT '原始发起人或被代表主体 ID；SERVICE_ACCOUNT 场景下后续可配合 representedActorId 扩展',
    trace_id VARCHAR(128) DEFAULT NULL COMMENT 'HTTP 或网关链路追踪 ID，用于把确认请求、dry-run 事件和 outbox 写入串联起来',
    confirmed TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否已显式确认；当前入箱成功只写 true，字段预留给后续撤销/作废语义',
    status VARCHAR(32) NOT NULL DEFAULT 'CONFIRMED' COMMENT '确认记录状态；当前为 CONFIRMED，后续可扩展 EXPIRED/REVOKED/POLICY_CHANGED',
    expires_at DATETIME(3) DEFAULT NULL COMMENT '确认有效期截止时间；过期不删除历史事实，但不应再作为近期执行确认使用',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '确认记录创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '确认记录更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_dag_confirmation_id (confirmation_id),
    KEY idx_agent_dag_confirmation_run_time (session_id, run_id, create_time),
    KEY idx_agent_dag_confirmation_scope_time (tenant_id, project_id, workspace_id, create_time),
    KEY idx_agent_dag_confirmation_status_expire (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='agent-runtime DAG selected-node 确认事实表';

-- ---------------------------------------------------------------------------
-- datasource-management：数据源与数据同步模块
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS datasource_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '数据源主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户 ID，用于多租户隔离、审计、配额和成本统计',
    project_id BIGINT NOT NULL DEFAULT 1 COMMENT '项目 ID，用于 PROJECT 数据范围、项目级数据源列表和项目级权限边界',
    workspace_id BIGINT COMMENT '工作空间 ID，用于项目内研发/测试/生产等协作空间隔离',
    name VARCHAR(128) NOT NULL COMMENT '唯一数据源名称',
    type VARCHAR(32) NOT NULL COMMENT '数据源类型，例如 MYSQL、POSTGRESQL',
    jdbc_url VARCHAR(512) NOT NULL COMMENT '连接地址',
    username VARCHAR(128) NOT NULL COMMENT '连接用户名',
    password VARCHAR(256) NOT NULL COMMENT '连接密码，当前阶段先明文保存，后续应升级到密钥中心',
    driver_class_name VARCHAR(256) NOT NULL COMMENT 'JDBC 驱动类名',
    description VARCHAR(512) COMMENT '便于人工理解的数据源说明',
    status VARCHAR(32) NOT NULL COMMENT '生命周期状态',
    last_test_status VARCHAR(32) DEFAULT 'UNKNOWN' COMMENT '最近一次连接测试状态',
    last_test_message VARCHAR(512) COMMENT '最近一次连接测试说明',
    last_test_time DATETIME COMMENT '最近一次连接测试时间',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '最后更新时间',
    UNIQUE KEY uk_datasource_tenant_project_name (tenant_id, project_id, name),
    INDEX idx_datasource_tenant_project (tenant_id, project_id, status),
    INDEX idx_datasource_workspace (tenant_id, workspace_id, status),
    INDEX idx_datasource_type (type),
    INDEX idx_datasource_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据源配置表';

CREATE TABLE IF NOT EXISTS datasource_readonly_sql_execution_audit (
    datasource_tenant_id BIGINT COMMENT '被访问数据源所属租户 ID 快照；与 actor_tenant_id 分开保存，便于平台代操作和服务账号场景审计',
    datasource_project_id BIGINT COMMENT '被访问数据源所属项目 ID 快照；用于 PROJECT 数据范围、项目级 SQL 访问审计报表和合规追溯',
    datasource_workspace_id BIGINT COMMENT '被访问数据源所属工作空间 ID 快照；用于研发/测试/生产空间级 SQL 访问审计筛选',
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '受控只读 SQL 执行审计主键',
    datasource_id BIGINT NOT NULL COMMENT '被访问的数据源 ID',
    datasource_name VARCHAR(128) NOT NULL COMMENT '数据源名称快照，便于历史审计可读',
    datasource_type VARCHAR(32) NOT NULL COMMENT '数据源类型快照，例如 MYSQL、POSTGRESQL、SQLSERVER',
    purpose VARCHAR(128) COMMENT '访问目的，例如 QUALITY_METRIC_SCAN、QUALITY_ANOMALY_SAMPLE、DATA_ASSET_PROFILE',
    actor_tenant_id BIGINT COMMENT '发起访问的租户 ID，用于多租户审计隔离',
    actor_id BIGINT COMMENT '发起访问的操作者 ID 或服务账号 ID',
    actor_role VARCHAR(64) NOT NULL COMMENT '发起访问的操作者角色或服务账号角色',
    actor_type VARCHAR(64) COMMENT '操作者类型，例如 USER、SERVICE_ACCOUNT、AGENT',
    source_service VARCHAR(128) COMMENT '调用来源服务，例如 data-quality、data-asset、gateway',
    trace_id VARCHAR(128) COMMENT '链路追踪 ID，用于串联质量任务、SQL 执行和报告生成',
    sql_fingerprint VARCHAR(64) COMMENT 'SQL SHA-256 指纹，用于同类访问聚合且避免保存完整 SQL',
    sql_preview VARCHAR(1000) COMMENT '截断后的 SQL 预览，仅用于人工排查，生产环境后续应继续脱敏字面量',
    requested_max_rows INT COMMENT '调用方请求的最大返回行数',
    applied_max_rows INT COMMENT '服务端最终应用的最大返回行数',
    requested_query_timeout_seconds INT COMMENT '调用方请求的查询超时秒数',
    applied_query_timeout_seconds INT COMMENT '服务端最终应用的查询超时秒数',
    returned_row_count INT COMMENT '实际返回行数',
    column_count INT COMMENT '结果列数量',
    duration_ms BIGINT COMMENT '执行耗时毫秒',
    execution_status VARCHAR(32) NOT NULL COMMENT '执行状态：SUCCESS、FAILED',
    failure_message VARCHAR(1000) COMMENT '失败原因摘要，成功时为空',
    executed_at DATETIME NOT NULL COMMENT 'SQL 执行开始时间',
    create_time DATETIME NOT NULL COMMENT '审计记录创建时间',
    INDEX idx_datasource_readonly_audit_datasource_time (datasource_id, executed_at),
    INDEX idx_datasource_readonly_audit_purpose_time (purpose, executed_at),
    INDEX idx_datasource_readonly_audit_tenant_time (actor_tenant_id, executed_at),
    INDEX idx_datasource_readonly_audit_actor_time (actor_role, executed_at),
    INDEX idx_datasource_readonly_audit_project_time (datasource_tenant_id, datasource_project_id, executed_at),
    INDEX idx_datasource_readonly_audit_workspace_time (datasource_tenant_id, datasource_workspace_id, executed_at),
    INDEX idx_datasource_readonly_audit_trace_id (trace_id),
    INDEX idx_datasource_readonly_audit_status_time (execution_status, executed_at),
    INDEX idx_datasource_readonly_audit_sql_fingerprint (sql_fingerprint)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据源受控只读 SQL 执行审计表';

CREATE TABLE IF NOT EXISTS sync_template (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '同步模板主键',
    tenant_id BIGINT NOT NULL COMMENT '租户 ID，预留给多租户场景',
    project_id BIGINT NOT NULL DEFAULT 1 COMMENT '项目 ID，用于租户内部项目级同步模板隔离、项目看板和项目审计',
    workspace_id BIGINT COMMENT '工作空间 ID，用于项目内协作空间筛选和后续空间级权限',
    name VARCHAR(128) NOT NULL COMMENT '模板名称',
    description VARCHAR(512) COMMENT '模板说明',
    source_datasource_id BIGINT NOT NULL COMMENT '源端数据源 ID',
    source_schema_name VARCHAR(128) COMMENT '源端 schema 名称',
    source_object_name VARCHAR(128) NOT NULL COMMENT '源端对象名称，例如表名或视图名',
    target_datasource_id BIGINT NOT NULL COMMENT '目标端数据源 ID',
    target_schema_name VARCHAR(128) COMMENT '目标端 schema 名称',
    target_object_name VARCHAR(128) NOT NULL COMMENT '目标端对象名称',
    sync_mode VARCHAR(64) NOT NULL COMMENT '同步模式，例如 FULL、CDC、BACKFILL',
    write_strategy VARCHAR(64) NOT NULL DEFAULT 'APPEND' COMMENT '写入策略，例如 APPEND、UPSERT、INSERT_IGNORE、REPLACE、OVERWRITE',
    primary_key_field VARCHAR(128) COMMENT '主键字段，用于幂等、去重和冲突判断',
    incremental_field VARCHAR(128) COMMENT '增量字段，用于时间增量或 ID 增量模式',
    field_mapping_config TEXT COMMENT '字段映射配置 JSON',
    filter_config TEXT COMMENT '过滤条件配置 JSON',
    partition_config TEXT COMMENT '分片或分区配置 JSON',
    retry_policy TEXT COMMENT '重试策略 JSON',
    timeout_policy TEXT COMMENT '超时策略 JSON',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用模板',
    created_by BIGINT NOT NULL COMMENT '创建人 ID',
    updated_by BIGINT COMMENT '更新人 ID',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_sync_template_tenant_project_name (tenant_id, project_id, name),
    INDEX idx_sync_template_project_mode (tenant_id, project_id, sync_mode, enabled),
    INDEX idx_sync_template_workspace (tenant_id, workspace_id, update_time),
    INDEX idx_sync_template_source (tenant_id, source_datasource_id),
    INDEX idx_sync_template_target (tenant_id, target_datasource_id),
    INDEX idx_sync_template_enabled (tenant_id, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步模板表';

CREATE TABLE IF NOT EXISTS sync_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '同步任务主键',
    tenant_id BIGINT NOT NULL COMMENT '租户 ID',
    project_id BIGINT NOT NULL DEFAULT 1 COMMENT '项目 ID，通常继承自同步模板，用于项目级任务列表、调度看板和审计隔离',
    workspace_id BIGINT COMMENT '工作空间 ID，通常继承自同步模板，用于空间级运营台筛选',
    template_id BIGINT NOT NULL COMMENT '关联同步模板 ID',
    name VARCHAR(128) NOT NULL COMMENT '任务名称',
    description VARCHAR(512) COMMENT '任务说明',
    current_state VARCHAR(64) NOT NULL COMMENT '当前主状态',
    approval_state VARCHAR(64) NOT NULL COMMENT '审批状态',
    priority VARCHAR(32) NOT NULL COMMENT '优先级',
    run_mode VARCHAR(64) NOT NULL COMMENT '执行模式',
    trigger_type VARCHAR(64) NOT NULL COMMENT '触发类型',
    schedule_config TEXT COMMENT '调度配置 JSON',
    owner_id BIGINT NOT NULL COMMENT '负责人 ID',
    last_execution_id BIGINT COMMENT '最近一次执行记录 ID',
    next_run_at DATETIME COMMENT '下一次计划运行时间',
    queued_at DATETIME COMMENT '最近一次进入队列时间',
    current_executor_id VARCHAR(128) COMMENT '当前认领任务的执行器实例标识',
    dispatch_lease_expire_at DATETIME COMMENT '当前任务调度租约到期时间',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用任务',
    operator_attention_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需要人工关注',
    timeout_seconds INT NOT NULL COMMENT '任务超时秒数',
    max_retry_count INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '当前已重试次数',
    queue_attempt_count INT NOT NULL DEFAULT 0 COMMENT '累计入队次数',
    latest_error_summary VARCHAR(1024) COMMENT '最近一次错误摘要',
    incident_note VARCHAR(1024) COMMENT '人工处置说明或事件备注',
    created_by BIGINT NOT NULL COMMENT '创建人 ID',
    updated_by BIGINT COMMENT '更新人 ID',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_sync_task_tenant_project_name (tenant_id, project_id, name),
    INDEX idx_sync_task_project_state (tenant_id, project_id, current_state),
    INDEX idx_sync_task_workspace_state (tenant_id, workspace_id, current_state),
    INDEX idx_sync_task_state (tenant_id, current_state),
    INDEX idx_sync_task_owner (tenant_id, owner_id),
    INDEX idx_sync_task_approval (tenant_id, approval_state),
    INDEX idx_sync_task_next_run (tenant_id, next_run_at),
    INDEX idx_sync_task_queue (tenant_id, current_state, queued_at),
    INDEX idx_sync_task_executor (current_executor_id, dispatch_lease_expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步任务表';

CREATE TABLE IF NOT EXISTS sync_execution (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '执行记录主键',
    sync_task_id BIGINT NOT NULL COMMENT '关联同步任务 ID',
    execution_no BIGINT NOT NULL COMMENT '同一任务下的第几次执行',
    state VARCHAR(64) NOT NULL COMMENT '执行状态',
    started_at DATETIME COMMENT '开始执行时间',
    finished_at DATETIME COMMENT '结束时间',
    checkpoint_ref VARCHAR(256) COMMENT '当前检查点摘要或引用',
    records_read BIGINT DEFAULT 0 COMMENT '已读取记录数',
    records_written BIGINT DEFAULT 0 COMMENT '已写入记录数',
    failed_record_count BIGINT DEFAULT 0 COMMENT '失败记录数',
    error_summary TEXT COMMENT '错误摘要',
    triggered_by BIGINT COMMENT '触发人 ID',
    executor_id VARCHAR(128) COMMENT '执行器实例标识',
    heartbeat_at DATETIME COMMENT '最近一次执行器心跳时间',
    lease_expire_at DATETIME COMMENT '执行租约到期时间',
    trigger_reason VARCHAR(512) COMMENT '触发原因说明',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    INDEX idx_sync_execution_task_no (sync_task_id, execution_no),
    INDEX idx_sync_execution_state (sync_task_id, state),
    INDEX idx_sync_execution_started_at (started_at),
    INDEX idx_sync_execution_executor (executor_id, lease_expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步执行记录表';

CREATE TABLE IF NOT EXISTS sync_checkpoint (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '检查点主键',
    execution_id BIGINT NOT NULL COMMENT '关联执行记录 ID',
    checkpoint_type VARCHAR(64) NOT NULL COMMENT '检查点类型，例如时间水位、主键范围、offset',
    checkpoint_value TEXT NOT NULL COMMENT '检查点值',
    shard_or_partition VARCHAR(128) COMMENT '分片或分区标识',
    update_time DATETIME NOT NULL COMMENT '最后更新时间',
    INDEX idx_sync_checkpoint_execution_partition (execution_id, shard_or_partition)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步检查点表';

CREATE TABLE IF NOT EXISTS sync_audit_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '审计记录主键',
    tenant_id BIGINT NOT NULL COMMENT '租户 ID',
    sync_task_id BIGINT COMMENT '关联同步任务 ID',
    execution_id BIGINT COMMENT '关联执行记录 ID',
    action_type VARCHAR(64) NOT NULL COMMENT '动作类型',
    actor_id BIGINT NOT NULL COMMENT '操作者 ID',
    actor_role VARCHAR(64) NOT NULL COMMENT '操作者角色',
    action_payload TEXT COMMENT '动作载荷内容',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    INDEX idx_sync_audit_tenant_action (tenant_id, action_type),
    INDEX idx_sync_audit_task_time (sync_task_id, create_time),
    INDEX idx_sync_audit_execution_time (execution_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步审计记录表';

CREATE TABLE IF NOT EXISTS sync_permission_policy_binding (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '权限绑定主键',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '绑定作用域租户 ID，0 表示平台全局默认绑定',
    actor_role VARCHAR(64) NOT NULL COMMENT '被绑定的角色枚举名',
    binding_type VARCHAR(64) NOT NULL COMMENT '绑定类型，例如 MENU、ROUTE、DATA_SCOPE',
    binding_value VARCHAR(128) NOT NULL COMMENT '绑定值，例如菜单编码、路由策略枚举名、数据范围枚举名',
    binding_source VARCHAR(64) NOT NULL DEFAULT 'MANUAL' COMMENT '绑定来源，例如 MANUAL、BOOTSTRAP、IMPORT',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用当前绑定',
    priority INT NOT NULL DEFAULT 100 COMMENT '绑定优先级，数值越大越优先',
    note VARCHAR(512) COMMENT '绑定说明或变更原因',
    created_by BIGINT NOT NULL COMMENT '创建人 ID',
    updated_by BIGINT COMMENT '更新人 ID',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_sync_permission_binding_scope_role_type_value (tenant_id, actor_role, binding_type, binding_value),
    INDEX idx_sync_permission_binding_scope_role_type (tenant_id, actor_role, binding_type, enabled),
    INDEX idx_sync_permission_binding_priority (binding_type, priority, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='同步权限策略绑定表';

CREATE TABLE IF NOT EXISTS sync_permission_policy_change_request (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '权限变更申请主键',
    target_tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '目标作用域租户 ID，0 表示平台全局变更',
    requester_id BIGINT NOT NULL COMMENT '申请发起人 ID',
    requester_role VARCHAR(64) NOT NULL COMMENT '申请发起人角色',
    requester_tenant_id BIGINT COMMENT '申请发起人所属租户',
    target_role VARCHAR(64) NOT NULL COMMENT '被修改绑定的目标角色',
    binding_type VARCHAR(64) NOT NULL COMMENT '绑定类型，例如 MENU、ROUTE、DATA_SCOPE',
    binding_values_json TEXT NOT NULL COMMENT '本次申请希望写入的绑定值列表 JSON',
    requested_priority INT NOT NULL DEFAULT 100 COMMENT '本次申请希望使用的默认优先级',
    requested_binding_source VARCHAR(64) NOT NULL DEFAULT 'MANUAL' COMMENT '本次申请希望使用的绑定来源',
    request_reason VARCHAR(1000) NOT NULL COMMENT '申请原因说明',
    required_approver_roles_json TEXT COMMENT '提交申请时固化的审批角色快照 JSON',
    request_status VARCHAR(64) NOT NULL COMMENT '申请状态，例如 PENDING_APPROVAL、EXECUTED、REJECTED',
    approver_id BIGINT COMMENT '审批人 ID',
    approver_role VARCHAR(64) COMMENT '审批人角色',
    approval_mode VARCHAR(64) COMMENT '审批模式，例如 DIRECT_ROLE、DELEGATED_ROLE',
    delegated_from_approver_id BIGINT COMMENT '若属于委托代批，则记录原始审批人 ID',
    delegated_from_approver_role VARCHAR(64) COMMENT '若属于委托代批，则记录原始审批角色',
    approval_comment VARCHAR(1000) COMMENT '审批意见',
    approved_at DATETIME COMMENT '审批完成时间',
    executed_at DATETIME COMMENT '审批通过后真正执行落库的时间',
    execution_summary VARCHAR(1000) COMMENT '执行结果摘要',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    INDEX idx_sync_permission_change_scope_status (target_tenant_id, request_status, create_time),
    INDEX idx_sync_permission_change_role_type (target_role, binding_type, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='同步权限策略变更申请表';

CREATE TABLE IF NOT EXISTS sync_permission_approval_delegate_rule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '审批委托规则主键',
    target_tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '委托生效的目标租户范围，0 表示平台全局审批委托',
    delegator_id BIGINT NOT NULL COMMENT '原始审批人 ID',
    delegator_role VARCHAR(64) NOT NULL COMMENT '原始审批人角色',
    delegate_id BIGINT NOT NULL COMMENT '被委托审批的人 ID',
    delegate_role VARCHAR(64) NOT NULL COMMENT '被委托审批的人角色',
    effective_from DATETIME COMMENT '委托开始时间',
    effective_to DATETIME COMMENT '委托结束时间',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用当前委托规则',
    delegate_reason VARCHAR(1000) NOT NULL COMMENT '委托原因说明',
    created_by BIGINT NOT NULL COMMENT '规则创建人 ID',
    updated_by BIGINT COMMENT '规则最后更新人 ID',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    INDEX idx_sync_permission_delegate_scope_delegate (target_tenant_id, delegate_id, delegate_role, enabled),
    INDEX idx_sync_permission_delegate_scope_delegator (target_tenant_id, delegator_id, delegator_role, enabled),
    INDEX idx_sync_permission_delegate_effective_window (effective_from, effective_to, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='同步权限审批委托规则表';

CREATE TABLE IF NOT EXISTS sync_governance_alert (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '治理告警主键',
    tenant_id BIGINT COMMENT '告警所属租户 ID，全局告警可以为空',
    sync_task_id BIGINT COMMENT '关联同步任务 ID',
    alert_type VARCHAR(64) NOT NULL COMMENT '告警类型，例如 QUEUE_PRESSURE、QUEUE_AGING',
    severity VARCHAR(32) NOT NULL COMMENT '告警严重级别',
    alert_status VARCHAR(32) NOT NULL COMMENT '告警状态，例如 OPEN、ACKNOWLEDGED、RESOLVED',
    delivery_status VARCHAR(32) NOT NULL COMMENT '外部投递状态，例如 PENDING、SENT、FAILED、SKIPPED、DEAD_LETTER',
    delivery_channel VARCHAR(32) NOT NULL COMMENT '告警通道，例如 NONE、WEBHOOK、INTERNAL_LOG',
    alert_key VARCHAR(128) NOT NULL COMMENT '告警去重键，用于短时间窗口内折叠同类风险',
    summary VARCHAR(512) NOT NULL COMMENT '告警摘要',
    detail TEXT COMMENT '告警详情',
    source_resource VARCHAR(64) COMMENT '告警来源资源，例如 SYNC_QUEUE',
    triggered_by_action VARCHAR(64) COMMENT '触发告警的动作，例如 INSPECT_QUEUE_HEALTH',
    first_occurred_at DATETIME NOT NULL COMMENT '首次发生时间',
    last_occurred_at DATETIME NOT NULL COMMENT '最近一次发生时间',
    occurrence_count INT NOT NULL DEFAULT 1 COMMENT '在去重窗口内累计发生次数',
    acknowledged_by BIGINT COMMENT '确认人 ID',
    acknowledged_at DATETIME COMMENT '确认时间',
    resolved_by BIGINT COMMENT '解决人 ID',
    resolved_at DATETIME COMMENT '解决时间',
    last_delivery_at DATETIME COMMENT '最近一次投递时间',
    next_delivery_attempt_at DATETIME COMMENT '下一次允许重试投递的时间',
    delivery_attempt_count INT NOT NULL DEFAULT 0 COMMENT '投递尝试次数',
    last_delivery_error VARCHAR(1000) COMMENT '最近一次投递失败摘要',
    dead_lettered_at DATETIME COMMENT '进入死信的时间',
    dead_letter_reason VARCHAR(1000) COMMENT '进入死信的原因摘要',
    dispatch_lease_owner VARCHAR(128) COMMENT '当前认领这条告警 outbox 的调度实例标识',
    dispatch_lease_expire_at DATETIME COMMENT '当前 outbox 认领租约的过期时间',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_sync_governance_alert_key_open (alert_key, alert_status),
    INDEX idx_sync_alert_tenant_status_time (tenant_id, alert_status, last_occurred_at),
    INDEX idx_sync_alert_task_status_time (sync_task_id, alert_status, last_occurred_at),
    INDEX idx_sync_alert_delivery_status (delivery_status, last_occurred_at),
    INDEX idx_sync_alert_retry_time (delivery_status, next_delivery_attempt_at),
    INDEX idx_sync_alert_dispatch_lease (dispatch_lease_expire_at, delivery_status, next_delivery_attempt_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='同步治理告警表';

CREATE TABLE IF NOT EXISTS sync_alert_delivery_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '告警投递记录主键',
    tenant_id BIGINT COMMENT '所属租户 ID',
    alert_id BIGINT NOT NULL COMMENT '关联治理告警 ID',
    sync_task_id BIGINT COMMENT '关联同步任务 ID',
    attempt_no INT NOT NULL COMMENT '第几次投递尝试',
    channel VARCHAR(32) NOT NULL COMMENT '本次投递通道，例如 WEBHOOK、FEISHU_WEBHOOK、WECOM_WEBHOOK、INTERNAL_LOG',
    delivery_status VARCHAR(32) NOT NULL COMMENT '本次通道投递结果，例如 SENT、FAILED、SKIPPED',
    target_endpoint VARCHAR(256) COMMENT '目标地址摘要或内部通道标识',
    manual_dispatch TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否为人工触发投递',
    operator_id BIGINT COMMENT '触发本次投递的操作者 ID',
    operator_role VARCHAR(64) COMMENT '触发本次投递的操作者角色',
    response_summary VARCHAR(1000) COMMENT '通道返回摘要',
    error_summary VARCHAR(1000) COMMENT '失败原因摘要',
    started_at DATETIME NOT NULL COMMENT '投递开始时间',
    finished_at DATETIME NOT NULL COMMENT '投递结束时间',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    INDEX idx_sync_alert_delivery_alert_attempt (alert_id, attempt_no),
    INDEX idx_sync_alert_delivery_tenant_time (tenant_id, create_time),
    INDEX idx_sync_alert_delivery_channel_status (channel, delivery_status, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='同步治理告警投递记录表';

-- ---------------------------------------------------------------------------
-- data-sync：数据同步模块
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS data_sync_template (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '同步模板主键',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户 ID，所有同步配置必须具备租户边界',
    project_id BIGINT COMMENT '项目 ID，用于租户内部二级隔离、项目级权限、项目级同步看板、项目级配额和成本审计',
    workspace_id BIGINT COMMENT '工作空间 ID，用于多团队协作空间、空间级筛选和后续空间级配额',
    name VARCHAR(128) NOT NULL COMMENT '模板名称，例如 CRM 客户表每日同步到数仓',
    description VARCHAR(512) COMMENT '模板说明，描述业务目的、数据范围和使用注意事项',
    source_datasource_id BIGINT NOT NULL COMMENT '源数据源 ID，引用 datasource-management 登记的数据源',
    target_datasource_id BIGINT NOT NULL COMMENT '目标数据源 ID，引用 datasource-management 登记的数据源',
    sync_mode VARCHAR(64) NOT NULL COMMENT '同步模式：FULL、INCREMENTAL_TIME、INCREMENTAL_ID、CDC_STREAMING、SCHEDULED_BATCH、ONE_TIME_MIGRATION、REPLAY、BACKFILL、OFFLINE_IMPORT、OFFLINE_EXPORT',
    field_mapping_config TEXT COMMENT '字段映射配置 JSON，包含源字段、目标字段、类型转换、默认值、脱敏规则等',
    filter_config TEXT COMMENT '过滤条件配置 JSON，例如业务日期、租户字段、状态字段过滤',
    partition_config TEXT COMMENT '分区与并发配置 JSON，例如日期分区、ID range、hash 分片',
    retry_policy TEXT COMMENT '重试策略 JSON，例如最大重试次数、退避间隔、可重试错误类型',
    timeout_policy TEXT COMMENT '超时策略 JSON，例如单批读取超时、整体执行超时、目标写入超时',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '模板是否启用，禁用后不应创建新的同步任务',
    created_by BIGINT COMMENT '创建人 ID',
    updated_by BIGINT COMMENT '最近更新人 ID',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    INDEX idx_data_sync_template_tenant_mode (tenant_id, sync_mode, enabled),
    INDEX idx_data_sync_template_project_mode (tenant_id, project_id, sync_mode, enabled),
    INDEX idx_data_sync_template_workspace (tenant_id, workspace_id, update_time),
    INDEX idx_data_sync_template_source (source_datasource_id),
    INDEX idx_data_sync_template_target (target_datasource_id),
    INDEX idx_data_sync_template_update_time (update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步模板表';

CREATE TABLE IF NOT EXISTS data_sync_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '同步任务主键',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户 ID，用于同步任务查询、权限、配额和审计隔离',
    project_id BIGINT COMMENT '项目 ID，通常继承自同步模板，用于项目负责人可见性、项目级配额、项目级 SLA 和成本统计',
    workspace_id BIGINT COMMENT '工作空间 ID，通常继承自同步模板，用于空间级运营台筛选和多团队协作',
    template_id BIGINT NOT NULL COMMENT '关联同步模板 ID',
    name VARCHAR(128) NOT NULL COMMENT '同步任务名称',
    current_state VARCHAR(64) NOT NULL COMMENT '任务主状态：DRAFT、CONFIGURED、PENDING_APPROVAL、SCHEDULED、QUEUED、RUNNING、PAUSED、RETRYING、PARTIALLY_SUCCEEDED、SUCCEEDED、FAILED、AWAITING_OPERATOR_ACTION、CANCELLED、ARCHIVED',
    approval_state VARCHAR(64) NOT NULL COMMENT '审批状态：NOT_REQUIRED、PENDING、APPROVED、REJECTED',
    priority VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT '任务优先级：HIGH、MEDIUM、LOW',
    schedule_config TEXT COMMENT '调度配置 JSON，例如 cron、固定间隔、维护窗口、时区和错峰策略',
    run_mode VARCHAR(64) NOT NULL DEFAULT 'TEMPLATE' COMMENT '运行模式，例如 TEMPLATE、MANUAL、BACKFILL、REPLAY',
    trigger_type VARCHAR(64) NOT NULL DEFAULT 'MANUAL' COMMENT '最近触发方式：MANUAL、SCHEDULED、API、SYSTEM、BACKFILL、REPLAY',
    owner_id BIGINT COMMENT '负责人 ID，用于我的同步任务、项目运营、失败通知和 SLA 归属',
    last_execution_id BIGINT COMMENT '最近一次同步执行记录 ID，后续接入 sync_execution 表后回写',
    attention_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需要人工介入，通常由超过最大退避次数、反复租约过期或执行环境异常触发',
    attention_reason VARCHAR(1000) COMMENT '人工介入原因摘要，用于运营台、告警和后续工单流转',
    description VARCHAR(512) COMMENT '任务说明',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    INDEX idx_data_sync_task_tenant_state (tenant_id, current_state, update_time),
    INDEX idx_data_sync_task_project_state (tenant_id, project_id, current_state, update_time),
    INDEX idx_data_sync_task_workspace_state (tenant_id, workspace_id, current_state, update_time),
    INDEX idx_data_sync_task_template (template_id),
    INDEX idx_data_sync_task_owner_state (tenant_id, owner_id, current_state),
    INDEX idx_data_sync_task_approval (tenant_id, approval_state, update_time),
    INDEX idx_data_sync_task_trigger (trigger_type, update_time),
    INDEX idx_data_sync_task_attention (tenant_id, attention_required, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步任务表';

CREATE TABLE IF NOT EXISTS data_sync_execution (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '同步执行记录主键',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户 ID，冗余保存便于执行历史按租户快速过滤',
    project_id BIGINT COMMENT '项目 ID，冗余自同步任务，用于项目级执行历史、失败率、成本和容量分析',
    workspace_id BIGINT COMMENT '工作空间 ID，冗余自同步任务，用于空间级运行证据筛选',
    sync_task_id BIGINT NOT NULL COMMENT '关联同步任务 ID',
    execution_no BIGINT NOT NULL COMMENT '同一任务下第几次执行',
    execution_state VARCHAR(64) NOT NULL COMMENT '执行状态：QUEUED、RUNNING、PAUSED、RETRYING、PARTIALLY_SUCCEEDED、SUCCEEDED、FAILED、CANCELLED',
    trigger_type VARCHAR(64) NOT NULL COMMENT '触发方式：MANUAL、SCHEDULED、API、SYSTEM、BACKFILL、REPLAY',
    queued_at DATETIME COMMENT '进入执行队列时间',
    started_at DATETIME COMMENT '真实开始执行时间，由执行器认领后写入',
    finished_at DATETIME COMMENT '执行完成时间，成功、失败或取消时写入',
    checkpoint_ref VARCHAR(256) COMMENT '最近 checkpoint 引用，可保存 checkpoint 表主键或外部状态引用',
    records_read BIGINT NOT NULL DEFAULT 0 COMMENT '已读取记录数',
    records_written BIGINT NOT NULL DEFAULT 0 COMMENT '已写入记录数',
    failed_record_count BIGINT NOT NULL DEFAULT 0 COMMENT '失败记录数',
    error_summary VARCHAR(1000) COMMENT '错误摘要，详细错误样本进入 data_sync_error_sample',
    triggered_by BIGINT COMMENT '触发人 ID',
    executor_id VARCHAR(128) COMMENT '执行器实例 ID，worker 认领后写入',
    heartbeat_time DATETIME COMMENT '最近一次执行器心跳时间，用于判断执行器是否仍然存活',
    lease_expire_time DATETIME COMMENT '当前执行租约过期时间，超过该时间可进入恢复或重新认领流程',
    defer_count INT NOT NULL DEFAULT 0 COMMENT '当前执行记录被延迟回队列次数，用于识别长期被退避的任务',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_data_sync_execution_task_no (sync_task_id, execution_no),
    INDEX idx_data_sync_execution_task_state (sync_task_id, execution_state, create_time),
    INDEX idx_data_sync_execution_tenant_state (tenant_id, execution_state, create_time),
    INDEX idx_data_sync_execution_project_state (tenant_id, project_id, execution_state, create_time),
    INDEX idx_data_sync_execution_workspace_state (tenant_id, workspace_id, execution_state, create_time),
    INDEX idx_data_sync_execution_trigger (trigger_type, create_time),
    INDEX idx_data_sync_execution_executor (executor_id, started_at),
    INDEX idx_data_sync_execution_lease (execution_state, lease_expire_time),
    INDEX idx_data_sync_execution_queue (execution_state, queued_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步执行记录表';

CREATE TABLE IF NOT EXISTS data_sync_callback_idempotency (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'data-sync 回调与租约动作幂等记录主键，仅用于内部更新和排障定位',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户 ID，避免不同租户复用相同幂等键时互相影响',
    sync_task_id BIGINT COMMENT '关联同步任务 ID；恢复类全局动作可为空',
    execution_id BIGINT COMMENT '关联执行记录 ID；恢复类全局动作可为空',
    scope_key VARCHAR(128) NOT NULL COMMENT '幂等作用域，例如 taskId:executionId 或 RECOVERY:ALL；避免 MySQL 唯一索引中 NULL 字段失效',
    action VARCHAR(64) NOT NULL COMMENT '动作编码：START、CHECKPOINT、COMPLETE、FAIL、HEARTBEAT、DEFER、RECOVER_EXPIRED_LEASE',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '调用方生成的幂等键；同一次业务动作重试必须复用同一个键',
    executor_id VARCHAR(128) COMMENT '执行器实例 ID；系统恢复类动作可使用 SERVICE_ACCOUNT 或为空',
    request_digest VARCHAR(1000) COMMENT '请求摘要；用于排障，不保存完整大结果、SQL、密钥或敏感样本',
    callback_state VARCHAR(32) NOT NULL COMMENT '幂等处理状态：PROCESSING、SUCCEEDED、FAILED',
    response_summary VARCHAR(1000) COMMENT '首次成功处理后的响应摘要，便于重复请求复用首次处理语义',
    error_message VARCHAR(1000) COMMENT '失败摘要，当前事务模型下失败通常回滚，该字段为后续独立失败审计预留',
    first_seen_time DATETIME NOT NULL COMMENT '首次看到该幂等键的时间',
    last_seen_time DATETIME NOT NULL COMMENT '最近一次看到该幂等键的时间；重复请求只刷新该字段，不再推进状态',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_data_sync_callback_idempotency (tenant_id, action, scope_key, idempotency_key),
    INDEX idx_data_sync_callback_execution (execution_id, action, last_seen_time),
    INDEX idx_data_sync_callback_task (sync_task_id, action, last_seen_time),
    INDEX idx_data_sync_callback_executor (executor_id, last_seen_time),
    INDEX idx_data_sync_callback_retention (last_seen_time, id),
    INDEX idx_data_sync_callback_state (callback_state, last_seen_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='data-sync 执行器回调与租约动作幂等记录表';

CREATE TABLE IF NOT EXISTS data_sync_checkpoint (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '同步 checkpoint 主键',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户 ID',
    project_id BIGINT COMMENT '项目 ID，冗余自同步任务，用于项目级断点恢复视图和数据保留策略',
    workspace_id BIGINT COMMENT '工作空间 ID，冗余自同步任务，用于空间级运行证据筛选',
    sync_task_id BIGINT NOT NULL COMMENT '关联同步任务 ID',
    execution_id BIGINT NOT NULL COMMENT '关联执行记录 ID',
    checkpoint_type VARCHAR(64) NOT NULL COMMENT 'checkpoint 类型：TIME_FIELD、ID_RANGE、KAFKA_OFFSET、FILE_POSITION、PARTITION_WINDOW 等',
    checkpoint_value TEXT NOT NULL COMMENT 'checkpoint 值，例如时间戳、最大 ID、Kafka offset 或 JSON 结构',
    shard_or_partition VARCHAR(128) COMMENT '分片或分区标识，支持并行任务保存多条 checkpoint',
    records_read BIGINT NOT NULL DEFAULT 0 COMMENT '该 checkpoint 对应已读取记录数',
    records_written BIGINT NOT NULL DEFAULT 0 COMMENT '该 checkpoint 对应已写入记录数',
    checkpoint_time DATETIME NOT NULL COMMENT 'checkpoint 生成时间',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    INDEX idx_data_sync_checkpoint_task (sync_task_id, checkpoint_time),
    INDEX idx_data_sync_checkpoint_execution (execution_id, checkpoint_time),
    INDEX idx_data_sync_checkpoint_type (tenant_id, checkpoint_type, checkpoint_time),
    INDEX idx_data_sync_checkpoint_project (tenant_id, project_id, checkpoint_time),
    INDEX idx_data_sync_checkpoint_partition (sync_task_id, shard_or_partition),
    INDEX idx_data_sync_checkpoint_retention (checkpoint_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步 checkpoint 表';

CREATE TABLE IF NOT EXISTS data_sync_error_sample (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '同步错误样本主键',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户 ID',
    project_id BIGINT COMMENT '项目 ID，冗余自同步任务，用于项目级错误样本筛选和质量复盘',
    workspace_id BIGINT COMMENT '工作空间 ID，冗余自同步任务，用于空间级错误治理看板',
    sync_task_id BIGINT NOT NULL COMMENT '关联同步任务 ID',
    execution_id BIGINT NOT NULL COMMENT '关联执行记录 ID',
    error_type VARCHAR(64) NOT NULL COMMENT '错误类型，例如 SOURCE_READ_ERROR、TARGET_WRITE_ERROR、TYPE_CONVERSION_ERROR',
    error_code VARCHAR(128) COMMENT '外部系统或内部标准错误码',
    error_message VARCHAR(1000) COMMENT '错误摘要，避免把完整堆栈塞入业务表',
    source_record_key VARCHAR(256) COMMENT '源端记录定位，例如主键、文件行号、Kafka topic/partition/offset',
    target_record_key VARCHAR(256) COMMENT '目标端记录定位，例如目标主键或写入批次',
    sample_payload VARCHAR(4000) COMMENT '脱敏并截断后的样本载荷',
    retryable TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否可重试',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    INDEX idx_data_sync_error_task (sync_task_id, create_time),
    INDEX idx_data_sync_error_execution (execution_id, create_time),
    INDEX idx_data_sync_error_type (tenant_id, error_type, create_time),
    INDEX idx_data_sync_error_project (tenant_id, project_id, error_type, create_time),
    INDEX idx_data_sync_error_retryable (retryable, create_time),
    INDEX idx_data_sync_error_retention (create_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步错误样本表';

CREATE TABLE IF NOT EXISTS data_sync_incident_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '同步事故记录主键',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户 ID，用于事故隔离、运营台筛选和后续 SLA 统计',
    project_id BIGINT COMMENT '项目 ID，用于项目级事故工作台、SLA 统计和项目负责人可见性控制',
    workspace_id BIGINT COMMENT '工作空间 ID，用于空间级事故筛选和多团队运营协作',
    sync_task_id BIGINT NOT NULL COMMENT '关联同步任务 ID',
    execution_id BIGINT COMMENT '关联最近执行记录 ID，可为空',
    incident_type VARCHAR(64) NOT NULL COMMENT '事故类型：EXECUTOR_UNSTABLE、CONNECTOR_FAILURE、TARGET_THROTTLED、CONFIGURATION_ERROR、DATA_CONTRACT_BROKEN 等',
    severity VARCHAR(32) NOT NULL DEFAULT 'P3' COMMENT '事故严重级别：P1、P2、P3、P4',
    incident_status VARCHAR(32) NOT NULL DEFAULT 'OPEN' COMMENT '事故状态：OPEN、ACKNOWLEDGED、RESOLVED、CLOSED',
    title VARCHAR(256) NOT NULL COMMENT '事故标题，用于运营台列表、通知和工单摘要',
    description VARCHAR(2000) COMMENT '事故描述，保存脱敏后的排障说明，不保存密钥、完整 SQL 或敏感样本',
    operator_id BIGINT COMMENT '创建事故的操作者 ID',
    operator_role VARCHAR(64) COMMENT '创建事故的操作者角色',
    assigned_operator_id BIGINT COMMENT '当前事故负责人 ID，用于运营分派、SLA 跟踪和我的事故列表',
    assigned_operator_role VARCHAR(64) COMMENT '当前事故负责人角色，后续可扩展为运营组、值班组或外部工单队列',
    resolution_summary VARCHAR(2000) COMMENT '事故解决摘要，后续事故处理闭环时填写',
    acknowledged_at DATETIME COMMENT '事故被确认接手的时间',
    resolved_at DATETIME COMMENT '事故被标记解决的时间',
    closed_at DATETIME COMMENT '事故被关闭的时间',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    INDEX idx_data_sync_incident_task (sync_task_id, create_time),
    INDEX idx_data_sync_incident_tenant_status (tenant_id, incident_status, severity, create_time),
    INDEX idx_data_sync_incident_project_status (tenant_id, project_id, incident_status, severity, create_time),
    INDEX idx_data_sync_incident_workspace_status (tenant_id, workspace_id, incident_status, create_time),
    INDEX idx_data_sync_incident_execution (execution_id),
    INDEX idx_data_sync_incident_operator (operator_id, create_time),
    INDEX idx_data_sync_incident_assignee (assigned_operator_id, incident_status, create_time),
    INDEX idx_data_sync_incident_retention (incident_status, closed_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步事故记录表';

CREATE TABLE IF NOT EXISTS data_sync_audit_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '数据同步审计记录主键',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户 ID',
    project_id BIGINT COMMENT '项目 ID，可为空；用于未来项目级审计报表和权限证据查询',
    workspace_id BIGINT COMMENT '工作空间 ID，可为空；用于未来空间级审计筛选',
    template_id BIGINT COMMENT '关联同步模板 ID，可为空；模板创建、校验、禁用等动作通常没有 sync_task_id',
    sync_task_id BIGINT COMMENT '关联同步任务 ID，可为空，例如仅操作模板时',
    execution_id BIGINT COMMENT '关联执行记录 ID，可为空',
    action_type VARCHAR(64) NOT NULL COMMENT '审计动作类型，例如 CREATE_TEMPLATE、CREATE_TASK、RUN_TASK、UPDATE_CHECKPOINT',
    actor_id BIGINT COMMENT '操作者 ID',
    actor_role VARCHAR(64) COMMENT '操作者角色',
    action_payload VARCHAR(2000) COMMENT '动作载荷摘要，应保存脱敏后的轻量信息',
    result VARCHAR(32) NOT NULL COMMENT '动作结果，例如 SUCCESS、FAILED、REJECTED',
    trace_id VARCHAR(128) COMMENT '链路追踪 ID',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    INDEX idx_data_sync_audit_task_time (sync_task_id, create_time),
    INDEX idx_data_sync_audit_template_time (template_id, create_time),
    INDEX idx_data_sync_audit_execution_time (execution_id, create_time),
    INDEX idx_data_sync_audit_tenant_action (tenant_id, action_type, create_time),
    INDEX idx_data_sync_audit_project_action (tenant_id, project_id, action_type, create_time),
    INDEX idx_data_sync_audit_actor (actor_id, create_time),
    INDEX idx_data_sync_audit_trace (trace_id),
    INDEX idx_data_sync_audit_retention (create_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步审计记录表';

CREATE TABLE IF NOT EXISTS sync_permission_governance_notification (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '权限治理通知主键',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '通知作用域租户 ID，0 表示平台全局',
    change_request_id BIGINT NOT NULL COMMENT '关联权限变更申请 ID',
    notification_type VARCHAR(64) NOT NULL COMMENT '通知类型，例如 APPROVAL_PENDING、APPROVAL_REMINDER、APPROVAL_ESCALATED、APPROVAL_APPROVED、APPROVAL_REJECTED',
    recipient_actor_id BIGINT COMMENT '具体接收人 ID',
    recipient_actor_role VARCHAR(64) COMMENT '接收人角色，用于角色待办通知',
    notification_channel VARCHAR(32) NOT NULL COMMENT '通知通道，例如 INTERNAL_LOG、NONE',
    notification_status VARCHAR(32) NOT NULL COMMENT '通知状态，例如 PENDING_DISPATCH、SENT、READ、FAILED、SKIPPED',
    summary VARCHAR(512) NOT NULL COMMENT '通知摘要',
    detail VARCHAR(2000) COMMENT '通知详情',
    next_dispatch_at DATETIME COMMENT '下一次允许投递时间',
    dispatch_attempt_count INT NOT NULL DEFAULT 0 COMMENT '通知投递尝试次数',
    dispatched_at DATETIME COMMENT '最近一次投递时间',
    last_dispatch_error VARCHAR(1000) COMMENT '最近一次投递失败摘要',
    read_by BIGINT COMMENT '已读操作者 ID',
    read_at DATETIME COMMENT '已读时间',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    INDEX idx_sync_permission_notification_scope_role (tenant_id, recipient_actor_role, notification_status, create_time),
    INDEX idx_sync_permission_notification_scope_actor (tenant_id, recipient_actor_id, notification_status, create_time),
    INDEX idx_sync_permission_notification_change_request (change_request_id, notification_type, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='权限治理通知表';

-- ---------------------------------------------------------------------------
-- data-quality：数据质量模块
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS quality_rule (
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户 ID，用于质量规则租户隔离、租户级配额、审计导出和规则模板共享边界',
    project_id BIGINT NOT NULL DEFAULT 1 COMMENT '项目 ID，用于 PROJECT 数据范围、项目级质量规则列表、质量大盘和项目负责人权限边界',
    workspace_id BIGINT COMMENT '工作空间 ID，用于项目内研发/测试/生产等协作空间隔离和空间级质量看板',
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '规则主键',
    name VARCHAR(128) NOT NULL COMMENT '唯一规则名称',
    rule_type VARCHAR(32) NOT NULL COMMENT '规则分类',
    target_object VARCHAR(256) NOT NULL COMMENT '被检测对象，例如表、字段或指标',
    target_type VARCHAR(64) NOT NULL DEFAULT 'GENERIC' COMMENT '检测目标类型：GENERIC、RELATIONAL_TABLE、RELATIONAL_FIELD、KAFKA_TOPIC、FILE_OBJECT、API_ENDPOINT',
    data_source_id BIGINT COMMENT '关联数据源 ID，关系型目标通常需要绑定 datasource-management 中登记的数据源',
    database_name VARCHAR(128) COMMENT '数据库名称，例如 MySQL database',
    schema_name VARCHAR(128) COMMENT 'Schema 名称，例如 PostgreSQL schema',
    table_name VARCHAR(128) COMMENT '表名，关系型表或字段规则使用',
    field_name VARCHAR(128) COMMENT '字段名，字段级规则使用',
    scan_strategy VARCHAR(64) COMMENT '目标校验后写入的扫描策略编码',
    target_validation_status VARCHAR(32) NOT NULL DEFAULT 'UNVALIDATED' COMMENT '目标校验状态：UNVALIDATED、VALIDATED、INVALID、UNSUPPORTED',
    target_validation_message VARCHAR(1000) COMMENT '最近一次目标校验说明',
    target_validated_time DATETIME COMMENT '最近一次目标校验时间',
    comparison_operator VARCHAR(16) NOT NULL COMMENT '比较运算符，例如 GT、LTE',
    expected_value DECIMAL(20,4) NOT NULL COMMENT '期望值或阈值',
    severity VARCHAR(16) NOT NULL COMMENT '业务严重级别',
    description VARCHAR(512) COMMENT '规则说明',
    status VARCHAR(32) NOT NULL COMMENT '生命周期状态：DRAFT、ACTIVE、INACTIVE、ARCHIVED、DELETED',
    rule_version INT NOT NULL DEFAULT 1 COMMENT '规则版本号，每次修改规则定义时递增',
    last_check_time DATETIME COMMENT '最近一次检测时间',
    last_check_status VARCHAR(16) COMMENT '最近一次检测结果：PASSED 或 FAILED',
    last_report_id BIGINT COMMENT '最近一次检测报告 ID',
    archived_time DATETIME COMMENT '归档时间',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '最后更新时间',
    UNIQUE KEY uk_quality_rule_tenant_project_name (tenant_id, project_id, name),
    INDEX idx_quality_rule_tenant_project_status (tenant_id, project_id, status),
    INDEX idx_quality_rule_workspace_status (tenant_id, workspace_id, status),
    INDEX idx_quality_rule_type (rule_type),
    INDEX idx_quality_rule_target_type (target_type),
    INDEX idx_quality_rule_datasource (data_source_id),
    INDEX idx_quality_rule_table_field (table_name, field_name),
    INDEX idx_quality_rule_validation_status (target_validation_status),
    INDEX idx_quality_rule_status (status),
    INDEX idx_quality_rule_last_check (last_check_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='质量规则表';

CREATE TABLE IF NOT EXISTS quality_check_execution (
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户 ID，冗余自质量规则，用于租户级执行失败率、耗时和资源消耗统计',
    project_id BIGINT NOT NULL DEFAULT 1 COMMENT '项目 ID，冗余自质量规则，用于项目级执行历史、SLA、质量看板和排障隔离',
    workspace_id BIGINT COMMENT '工作空间 ID，冗余自质量规则，用于空间级运行证据筛选',
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '质量检测执行记录主键',
    rule_id BIGINT NOT NULL COMMENT '关联规则 ID',
    execution_no BIGINT NOT NULL COMMENT '同一规则下第几次执行',
    trigger_type VARCHAR(64) NOT NULL COMMENT '触发类型，例如 MANUAL、SCHEDULED、TASK_TRIGGERED',
    execution_state VARCHAR(32) NOT NULL COMMENT '执行状态：RUNNING、SUCCESS、FAILED',
    operator VARCHAR(128) COMMENT '触发主体，例如 system、service-account、用户 ID',
    task_id BIGINT COMMENT '关联 task-management 任务 ID，人工执行时为空',
    task_run_id BIGINT COMMENT '关联 task-management 单次执行记录 ID，用于区分同一任务的多次重试运行',
    executor_id VARCHAR(128) COMMENT '实际执行器实例 ID，用于排查实例级失败率、耗时和版本问题',
    started_at DATETIME NOT NULL COMMENT '开始时间',
    finished_at DATETIME COMMENT '结束时间',
    duration_ms BIGINT COMMENT '执行耗时，单位毫秒',
    report_id BIGINT COMMENT '生成的质量检测报告 ID',
    scan_plan_snapshot TEXT COMMENT '本次执行使用的扫描计划快照 JSON，用于历史报告解释和审计复盘',
    message VARCHAR(1000) COMMENT '执行说明或失败原因',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_quality_execution_rule_no (rule_id, execution_no),
    INDEX idx_quality_execution_rule_state (rule_id, execution_state, started_at),
    INDEX idx_quality_execution_state_time (execution_state, started_at),
    INDEX idx_quality_execution_task_id (task_id),
    INDEX idx_quality_execution_task_run_id (task_run_id),
    INDEX idx_quality_execution_project_state (tenant_id, project_id, execution_state, started_at),
    INDEX idx_quality_execution_workspace_state (tenant_id, workspace_id, execution_state, started_at),
    INDEX idx_quality_execution_executor (executor_id, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='质量检测执行记录表';

CREATE TABLE IF NOT EXISTS quality_check_report (
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户 ID，冗余自质量规则，用于租户级质量评分、审计导出和保留周期清理',
    project_id BIGINT NOT NULL DEFAULT 1 COMMENT '项目 ID，冗余自质量规则，用于项目级报告检索、质量大盘、失败报告筛选和权限隔离',
    workspace_id BIGINT COMMENT '工作空间 ID，冗余自质量规则，用于空间级质量趋势和生产/测试空间隔离',
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '报告主键',
    rule_id BIGINT NOT NULL COMMENT '关联规则 ID',
    execution_id BIGINT COMMENT '关联质量检测执行记录 ID',
    rule_version INT COMMENT '规则版本快照',
    rule_name VARCHAR(128) NOT NULL COMMENT '规则名称快照',
    rule_type VARCHAR(32) COMMENT '规则类型快照，用于报告横向检索和历史语义保留',
    target_object VARCHAR(256) NOT NULL COMMENT '检测对象快照',
    severity VARCHAR(16) COMMENT '严重级别快照',
    measured_value DECIMAL(20,4) NOT NULL COMMENT '实际观测值',
    expected_value DECIMAL(20,4) NOT NULL COMMENT '期望值快照',
    comparison_operator VARCHAR(16) NOT NULL COMMENT '比较运算符快照',
    check_status VARCHAR(16) NOT NULL COMMENT '检测结果，PASSED 或 FAILED',
    sample_size INT NOT NULL COMMENT '参与检测的样本量',
    exception_count INT NOT NULL COMMENT '异常记录数量',
    pass_rate DECIMAL(10,4) COMMENT '通过率，按样本量和异常数计算',
    trigger_type VARCHAR(64) COMMENT '触发类型，例如 MANUAL、SCHEDULED、TASK_TRIGGERED',
    summary VARCHAR(1024) NOT NULL COMMENT '结果摘要',
    notes VARCHAR(1024) COMMENT '补充说明',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    INDEX idx_quality_report_rule_id (rule_id),
    INDEX idx_quality_report_project_status_time (tenant_id, project_id, check_status, create_time),
    INDEX idx_quality_report_workspace_time (tenant_id, workspace_id, create_time),
    INDEX idx_quality_report_rule_type (rule_type),
    INDEX idx_quality_report_execution_id (execution_id),
    INDEX idx_quality_report_status (check_status),
    INDEX idx_quality_report_severity (severity),
    INDEX idx_quality_report_target_object (target_object),
    INDEX idx_quality_report_trigger_type (trigger_type),
    INDEX idx_quality_report_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='质量检测报告表';

CREATE TABLE IF NOT EXISTS quality_anomaly_detail (
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户 ID，冗余自质量规则/报告，用于异常样本租户隔离、脱敏导出和保留策略',
    project_id BIGINT NOT NULL DEFAULT 1 COMMENT '项目 ID，冗余自质量规则/报告，用于异常工作台、清洗任务创建、根因分析和 PROJECT 权限过滤',
    workspace_id BIGINT COMMENT '工作空间 ID，冗余自质量规则/报告，用于空间级异常治理和运营告警隔离',
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '异常明细主键',
    report_id BIGINT NOT NULL COMMENT '关联质量检测报告 ID',
    rule_id BIGINT NOT NULL COMMENT '关联质量规则 ID，冗余保存便于按规则统计异常分布',
    target_object VARCHAR(256) NOT NULL COMMENT '检测对象快照，例如库表、字段或业务指标',
    anomaly_type VARCHAR(64) COMMENT '异常类型，例如 NULL_VALUE、DUPLICATE_VALUE、OUT_OF_RANGE',
    field_name VARCHAR(128) COMMENT '异常字段名称，表级或指标级规则可为空',
    record_identifier VARCHAR(256) COMMENT '记录定位信息，例如主键、文件行号、Kafka offset 或消息 key',
    observed_value VARCHAR(1024) COMMENT '实际观测值，使用字符串兼容数字、文本、日期、枚举和 JSON 摘要',
    expected_value VARCHAR(1024) COMMENT '期望值或规则描述，可保存阈值、枚举、正则或自然语言说明',
    severity VARCHAR(16) COMMENT '单条异常严重级别，默认可继承规则严重级别',
    recommendation VARCHAR(1024) COMMENT '清洗或处理建议，后续可由质量智能体生成',
    sample_payload VARCHAR(4000) COMMENT '脱敏且截断后的样本上下文，避免详情页必须重新扫描原始数据',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    INDEX idx_quality_anomaly_report_id (report_id),
    INDEX idx_quality_anomaly_rule_id (rule_id),
    INDEX idx_quality_anomaly_project_type_time (tenant_id, project_id, anomaly_type, create_time),
    INDEX idx_quality_anomaly_workspace_time (tenant_id, workspace_id, create_time),
    INDEX idx_quality_anomaly_type (anomaly_type),
    INDEX idx_quality_anomaly_field_name (field_name),
    INDEX idx_quality_anomaly_severity (severity),
    INDEX idx_quality_anomaly_target_object (target_object),
    INDEX idx_quality_anomaly_rule_field_time (rule_id, field_name, create_time),
    INDEX idx_quality_anomaly_report_type_time (report_id, anomaly_type, create_time),
    INDEX idx_quality_anomaly_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='质量异常明细表';
